project:
  type: website
  output-dir: docs
  resources:
    - SOCIAL_SEMESTER_BOOK_EN.pdf
    - .nojekyll
    - 2025-2026-classes/
    - slides/
    - assets/

website:
  site-url: "https://kostadinoff.github.io"
  description: Kostadin Kostadinov | Assistant Professor at the Medical University of Plovdiv

  page-footer:
    left: "Email me at <a href='mailto:kostadinr.kostadinov@mu-plovdiv.bg'>kostadinr.kostadinov@mu-plovdiv.bg</a> or book a <a href='https://tinyurl.com/whentomeetme' target='_blank'>meeting</a>"
    right: "Built with <a href='https://quarto.org' target='_blank'>Quarto</a>"
  title: "Kostadin Kostadinov"
  favicon: favicon.png

  twitter-card:
    creator: "@https://x.com/kostadinoffMD"
  navbar:
    right:
      - icon: github
        href: https://github.com/kostadinoff
      - icon: twitter
        href: https://x.com/kostadinoffMD
      - icon: linkedin
        href: https://www.linkedin.com/in/kostadinovmd/
      - icon: rss
        href: epinews.xml
    background: primary
    search: true
    left:
      - href: index.qmd
        text: Home
      - href: CV.qmd
        text: CV
      - text: Teaching
        menu:
          - href: slides.qmd
            text: Teaching materials
          - href: learning.qmd
            text: 15-minute learning
          - href: tasks.qmd
            text: Learning tasks
          - href: study-guide.qmd
            text: Social medicine study guide
      - href: epinews.qmd
        text: Epi News
      - href: kkstatfun.qmd
        text: kkstatfun
      - href: lab.qmd
        text: Lab

format:
  html:
    theme:
      light:
        - cosmo
        - theme-light.scss
      dark:
        - cosmo
        - theme-dark.scss
    respect-user-color-scheme: true
    css: styles.css
    toc: true
    title-block-banner: true
editor: source
