---
title: "Teaching materials"
listing: 
  id: blog-listing
  categories: true
  filter-ui: true
  feed: true
  sort-ui: [date]
  sort: "date desc"
  contents:
  - "teaching-posts/!(template|blog-image|references).qmd"
  fields: [title, date, author, description, categories]
  type: grid
  grid-columns: 1
  image-height: "12em"
---

This page contains a collection of teaching materials that I have developed over the years. They cover a range of topics, primarily statistics, social medicine, public health, and medical ethics, with occasional materials on other subjects. The posts are available in both Bulgarian and English, and you can filter them by category, discipline, date, or language (hopefully, that feature works as intended).

The materials have been created with reference to the work and contributions of my colleagues, whose input has greatly enriched their quality and scope. However, I bear full responsibility for any errors or omissions. I am currently in the process of updating and adding references, so the citations included are not yet complete.

::: {#blog-listing}
:::