<!DOCTYPE html>
<html xmlns="http://www.w3.org/1999/xhtml" lang="en" xml:lang="en"><head>

<meta charset="utf-8">
<meta name="generator" content="quarto-1.10.18">

<meta name="viewport" content="width=device-width, initial-scale=1.0, user-scalable=yes">

<meta name="author" content="Kostadin Kostadinov">
<meta name="dcterms.date" content="2026-09-13">
<meta name="description" content="A 75-minute group exercise after the 15-minute reading: correct common misconceptions, interpret DMFT and the care index for three districts, classify preventive measures, and allocate a limited prevention budget. Includes collapsible model answers.">

<title>Dental Public Health, Class 1: Reading a Population and Spending a Budget – Kostadin Kostadinov</title>
<style>
/* Default styles provided by pandoc.
** See https://pandoc.org/MANUAL.html#variables-for-html for config info.
*/
span.smallcaps{font-variant: small-caps;}
div.columns{display: flex; gap: 1.5em;}
div.column{flex: auto;}
@media screen {
div.columns{gap: min(4vw, 1.5em);}
div.column{overflow-x: auto;}
}
div.hanging-indent{margin-left: 1.5em; text-indent: -1.5em;}
ul.task-list{list-style: none;}
ul.task-list li input[type="checkbox"] {
  width: 0.8em;
  margin: 0 0.8em 0.2em -1em; /* quarto-specific, see https://github.com/quarto-dev/quarto-cli/issues/4556 */ 
  vertical-align: middle;
}
</style>


<script src="../site_libs/quarto-nav/quarto-nav.js"></script>
<script src="../site_libs/quarto-nav/headroom.min.js"></script>
<script src="../site_libs/clipboard/clipboard.min.js"></script>
<script src="../site_libs/quarto-search/autocomplete.umd.js"></script>
<script src="../site_libs/quarto-search/fuse.min.js"></script>
<script src="../site_libs/quarto-search/quarto-search.js"></script>
<meta name="quarto:offset" content="../">
<link href="../favicon.png" rel="icon" type="image/png">
<script src="../site_libs/quarto-html/quarto.js" type="module"></script>
<script src="../site_libs/quarto-html/tabsets/tabsets.js" type="module"></script>
<script src="../site_libs/quarto-html/popper.min.js"></script>
<script src="../site_libs/quarto-html/tippy.umd.min.js"></script>
<script src="../site_libs/quarto-html/anchor.min.js"></script>
<link href="../site_libs/quarto-html/tippy.css" rel="stylesheet">
<link href="../site_libs/quarto-html/quarto-syntax-highlighting-f1dc749df20b1e08b3a4856047134027.css" rel="stylesheet" class="quarto-color-scheme" id="quarto-text-highlighting-styles">
<link href="../site_libs/quarto-html/quarto-syntax-highlighting-dark-55d0e057869ad88b5495b2227f7019fc.css" rel="stylesheet" class="quarto-color-scheme quarto-color-alternate" id="quarto-text-highlighting-styles">
<link href="../site_libs/quarto-html/quarto-syntax-highlighting-f1dc749df20b1e08b3a4856047134027.css" rel="stylesheet" class="quarto-color-scheme-extra" id="quarto-text-highlighting-styles">
<script src="../site_libs/bootstrap/bootstrap.min.js"></script>
<link href="../site_libs/bootstrap/bootstrap-icons.css" rel="stylesheet">
<link href="../site_libs/bootstrap/bootstrap-a77c49f3ea693e0a5303c258335e3cb3.min.css" rel="stylesheet" append-hash="true" class="quarto-color-scheme" id="quarto-bootstrap" data-mode="light">
<link href="../site_libs/bootstrap/bootstrap-dark-9428e41df4ea88ae9660976a99a1885d.min.css" rel="stylesheet" append-hash="true" class="quarto-color-scheme quarto-color-alternate" id="quarto-bootstrap" data-mode="dark">
<link href="../site_libs/bootstrap/bootstrap-a77c49f3ea693e0a5303c258335e3cb3.min.css" rel="stylesheet" append-hash="true" class="quarto-color-scheme-extra" id="quarto-bootstrap" data-mode="light">
<script id="quarto-search-options" type="application/json">{
  "location": "navbar",
  "copy-button": false,
  "collapse-after": 3,
  "panel-placement": "end",
  "type": "overlay",
  "limit": 50,
  "keyboard-shortcut": [
    "f",
    "/",
    "s"
  ],
  "show-item-context": false,
  "language": {
    "search-no-results-text": "No results",
    "search-matching-documents-text": "matching documents",
    "search-copy-link-title": "Copy link to search",
    "search-hide-matches-text": "Hide additional matches",
    "search-more-match-text": "more match in this document",
    "search-more-matches-text": "more matches in this document",
    "search-clear-button-title": "Clear",
    "search-text-placeholder": "",
    "search-detached-cancel-button-title": "Cancel",
    "search-submit-button-title": "Submit",
    "search-label": "Search"
  }
}</script>


<link rel="stylesheet" href="../styles.css">
<link rel="stylesheet" href="../assets/teaching.css">
<meta name="twitter:title" content="Dental Public Health, Class 1: Reading a Population and Spending a Budget – Kostadin Kostadinov">
<meta name="twitter:description" content="A 75-minute group exercise after the 15-minute reading: correct common misconceptions, interpret DMFT and the care index for three districts, classify preventive measures, and allocate a limited prevention budget. Includes collapsible model answers.">
<meta name="twitter:creator" content="@https://x.com/kostadinoffMD">
<meta name="twitter:card" content="summary">
</head>

<body class="nav-fixed quarto-light"><script id="quarto-html-before-body" type="application/javascript">
    const toggleBodyColorMode = (bsSheetEl) => {
      const mode = bsSheetEl.getAttribute("data-mode");
      const bodyEl = window.document.querySelector("body");
      if (mode === "dark") {
        bodyEl.classList.add("quarto-dark");
        bodyEl.classList.remove("quarto-light");
      } else {
        bodyEl.classList.add("quarto-light");
        bodyEl.classList.remove("quarto-dark");
      }
    }
    const toggleBodyColorPrimary = () => {
      const bsSheetEl = window.document.querySelector("link#quarto-bootstrap:not([rel=disabled-stylesheet])");
      if (bsSheetEl) {
        toggleBodyColorMode(bsSheetEl);
      }
    }
    const setColorSchemeToggle = (alternate) => {
      const toggles = window.document.querySelectorAll('.quarto-color-scheme-toggle');
      for (let i=0; i < toggles.length; i++) {
        const toggle = toggles[i];
        if (toggle) {
          if (alternate) {
            toggle.classList.add("alternate");
          } else {
            toggle.classList.remove("alternate");
          }
        }
      }
    };
    const toggleColorMode = (alternate) => {
      // Switch the stylesheets
      const primaryStylesheets = window.document.querySelectorAll('link.quarto-color-scheme:not(.quarto-color-alternate)');
      const alternateStylesheets = window.document.querySelectorAll('link.quarto-color-scheme.quarto-color-alternate');
      manageTransitions('#quarto-margin-sidebar .nav-link', false);
      if (alternate) {
        // note: dark is layered on light, we don't disable primary!
        enableStylesheet(alternateStylesheets);
        for (const sheetNode of alternateStylesheets) {
          if (sheetNode.id === "quarto-bootstrap") {
            toggleBodyColorMode(sheetNode);
          }
        }
      } else {
        disableStylesheet(alternateStylesheets);
        enableStylesheet(primaryStylesheets)
        toggleBodyColorPrimary();
      }
      manageTransitions('#quarto-margin-sidebar .nav-link', true);
      // Switch the toggles
      setColorSchemeToggle(alternate)
      // Hack to workaround the fact that safari doesn't
      // properly recolor the scrollbar when toggling (#1455)
      if (navigator.userAgent.indexOf('Safari') > 0 && navigator.userAgent.indexOf('Chrome') == -1) {
        manageTransitions("body", false);
        window.scrollTo(0, 1);
        setTimeout(() => {
          window.scrollTo(0, 0);
          manageTransitions("body", true);
        }, 40);
      }
    }
    const disableStylesheet = (stylesheets) => {
      for (let i=0; i < stylesheets.length; i++) {
        const stylesheet = stylesheets[i];
        stylesheet.rel = 'disabled-stylesheet';
      }
    }
    const enableStylesheet = (stylesheets) => {
      for (let i=0; i < stylesheets.length; i++) {
        const stylesheet = stylesheets[i];
        if(stylesheet.rel !== 'stylesheet') { // for Chrome, which will still FOUC without this check
          stylesheet.rel = 'stylesheet';
        }
      }
    }
    const manageTransitions = (selector, allowTransitions) => {
      const els = window.document.querySelectorAll(selector);
      for (let i=0; i < els.length; i++) {
        const el = els[i];
        if (allowTransitions) {
          el.classList.remove('notransition');
        } else {
          el.classList.add('notransition');
        }
      }
    }
    const isFileUrl = () => {
      return window.location.protocol === 'file:';
    }
    const hasAlternateSentinel = () => {
      let styleSentinel = getColorSchemeSentinel();
      if (styleSentinel !== null) {
        return styleSentinel === "alternate";
      } else {
        return false;
      }
    }
    const setStyleSentinel = (alternate) => {
      const value = alternate ? "alternate" : "default";
      if (!isFileUrl()) {
        window.localStorage.setItem("quarto-color-scheme", value);
      } else {
        localAlternateSentinel = value;
      }
    }
    const getColorSchemeSentinel = () => {
      if (!isFileUrl()) {
        const storageValue = window.localStorage.getItem("quarto-color-scheme");
        return storageValue != null ? storageValue : localAlternateSentinel;
      } else {
        return localAlternateSentinel;
      }
    }
    const toggleGiscusIfUsed = (isAlternate, darkModeDefault) => {
      const baseTheme = document.querySelector('#giscus-base-theme')?.value ?? 'light';
      const alternateTheme = document.querySelector('#giscus-alt-theme')?.value ?? 'dark';
      let newTheme = '';
      if(authorPrefersDark) {
        newTheme = isAlternate ? baseTheme : alternateTheme;
      } else {
        newTheme = isAlternate ? alternateTheme : baseTheme;
      }
      const changeGiscusTheme = () => {
        // From: https://github.com/giscus/giscus/issues/336
        const sendMessage = (message) => {
          const iframe = document.querySelector('iframe.giscus-frame');
          if (!iframe) return;
          iframe.contentWindow.postMessage({ giscus: message }, 'https://giscus.app');
        }
        sendMessage({
          setConfig: {
            theme: newTheme
          }
        });
      }
      const isGiscussLoaded = window.document.querySelector('iframe.giscus-frame') !== null;
      if (isGiscussLoaded) {
        changeGiscusTheme();
      }
    };
    const authorPrefersDark = false;
    const queryPrefersDark = window.matchMedia('(prefers-color-scheme: dark)');
    const darkModeDefault = queryPrefersDark.matches;
      document.querySelector('link#quarto-text-highlighting-styles.quarto-color-scheme-extra').rel = 'disabled-stylesheet';
      document.querySelector('link#quarto-bootstrap.quarto-color-scheme-extra').rel = 'disabled-stylesheet';
    let localAlternateSentinel = darkModeDefault ? 'alternate' : 'default';
    // Dark / light mode switch
    window.quartoToggleColorScheme = () => {
      // Read the current dark / light value
      let toAlternate = !hasAlternateSentinel();
      toggleColorMode(toAlternate);
      setStyleSentinel(toAlternate);
      toggleGiscusIfUsed(toAlternate, darkModeDefault);
      window.dispatchEvent(new Event('resize'));
    };
    queryPrefersDark.addEventListener("change", e => {
      if(window.localStorage.getItem("quarto-color-scheme") !== null)
        return;
      const alternate = e.matches
      toggleColorMode(alternate);
      localAlternateSentinel = e.matches ? 'alternate' : 'default'; // this is used alongside local storage!
      toggleGiscusIfUsed(alternate, darkModeDefault);
    });
    // Switch to dark mode if need be
    if (hasAlternateSentinel()) {
      toggleColorMode(true);
    } else {
      toggleColorMode(false);
    }
  </script>

<div id="quarto-search-results"></div>
  <header id="quarto-header" class="headroom fixed-top quarto-banner">
    <nav class="navbar navbar-expand-lg " data-bs-theme="dark">
      <div class="navbar-container container-fluid">
      <div class="navbar-brand-container mx-auto">
    <a class="navbar-brand" href="../index.html">
    <span class="navbar-title">Kostadin Kostadinov</span>
    </a>
  </div>
            <div id="quarto-search" class="" title="Search"></div>
          <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarCollapse" aria-controls="navbarCollapse" role="menu" aria-expanded="false" aria-label="Toggle navigation" onclick="if (window.quartoToggleHeadroom) { window.quartoToggleHeadroom(); }">
  <span class="navbar-toggler-icon"></span>
</button>
          <div class="collapse navbar-collapse" id="navbarCollapse">
            <ul class="navbar-nav navbar-nav-scroll me-auto">
  <li class="nav-item">
    <a class="nav-link" href="../index.html"> 
<span class="menu-text">Home</span></a>
  </li>  
  <li class="nav-item">
    <a class="nav-link" href="../CV.html"> 
<span class="menu-text">CV</span></a>
  </li>  
  <li class="nav-item dropdown ">
    <a class="nav-link dropdown-toggle" href="#" id="nav-menu-teaching" role="link" data-bs-toggle="dropdown" aria-expanded="false">
 <span class="menu-text">Teaching</span>
    </a>
    <ul class="dropdown-menu" aria-labelledby="nav-menu-teaching">    
        <li>
    <a class="dropdown-item" href="../slides.html">
 <span class="dropdown-text">Teaching materials</span></a>
  </li>  
        <li>
    <a class="dropdown-item" href="../learning.html">
 <span class="dropdown-text">15-minute learning</span></a>
  </li>  
        <li>
    <a class="dropdown-item" href="../tasks.html">
 <span class="dropdown-text">Learning tasks</span></a>
  </li>  
        <li>
    <a class="dropdown-item" href="../study-guide.html">
 <span class="dropdown-text">Study guides</span></a>
  </li>  
    </ul>
  </li>
  <li class="nav-item">
    <a class="nav-link" href="../blog.html"> 
<span class="menu-text">Blog</span></a>
  </li>  
  <li class="nav-item">
    <a class="nav-link" href="../epinews.html"> 
<span class="menu-text">Epi News</span></a>
  </li>  
  <li class="nav-item">
    <a class="nav-link" href="../kkstatfun.html"> 
<span class="menu-text">kkstatfun</span></a>
  </li>  
  <li class="nav-item">
    <a class="nav-link" href="../lab.html"> 
<span class="menu-text">Lab</span></a>
  </li>  
</ul>
            <ul class="navbar-nav navbar-nav-scroll ms-auto">
  <li class="nav-item compact">
    <a class="nav-link" href="https://github.com/kostadinoff"> <i class="bi bi-github" role="img">
</i> 
<span class="menu-text"></span></a>
  </li>  
  <li class="nav-item compact">
    <a class="nav-link" href="https://x.com/kostadinoffMD"> <i class="bi bi-twitter" role="img">
</i> 
<span class="menu-text"></span></a>
  </li>  
  <li class="nav-item compact">
    <a class="nav-link" href="https://www.linkedin.com/in/kostadinovmd/"> <i class="bi bi-linkedin" role="img">
</i> 
<span class="menu-text"></span></a>
  </li>  
  <li class="nav-item compact">
    <a class="nav-link" href="../epinews.xml"> <i class="bi bi-rss" role="img">
</i> 
<span class="menu-text"></span></a>
  </li>  
</ul>
          </div> <!-- /navcollapse -->
            <div class="quarto-navbar-tools">
  <a href="" class="quarto-color-scheme-toggle quarto-navigation-tool  px-1" onclick="window.quartoToggleColorScheme(); return false;" title="Toggle dark mode"><i class="bi"></i></a>
</div>
      </div> <!-- /container-fluid -->
    </nav>
</header>
<!-- content -->
<header id="title-block-header" class="quarto-title-block default page-columns page-full">
  <div class="quarto-title-banner page-columns page-full">
    <div class="quarto-title column-body">
      <h1 class="title">Dental Public Health, Class 1: Reading a Population and Spending a Budget</h1>
                  <div>
        <div class="description">
          A 75-minute group exercise after the 15-minute reading: correct common misconceptions, interpret DMFT and the care index for three districts, classify preventive measures, and allocate a limited prevention budget. Includes collapsible model answers.
        </div>
      </div>
                          <div class="quarto-categories">
                <div class="quarto-category">English</div>
                <div class="quarto-category">Dental Public Health</div>
                <div class="quarto-category">Assignment</div>
                <div class="quarto-category">Dental Medicine</div>
                <div class="quarto-category">2026/2027</div>
              </div>
                  </div>
  </div>
    
  
  <div class="quarto-title-meta">

      <div>
      <div class="quarto-title-meta-heading">Author</div>
      <div class="quarto-title-meta-contents">
               <p>Kostadin Kostadinov </p>
            </div>
    </div>
      
      <div>
      <div class="quarto-title-meta-heading">Published</div>
      <div class="quarto-title-meta-contents">
        <p class="date">September 13, 2026</p>
      </div>
    </div>
    
      
    </div>
    
  
  </header><div id="quarto-content" class="quarto-container page-columns page-rows-contents page-layout-article page-navbar">
<!-- sidebar -->
<!-- margin-sidebar -->
    <div id="quarto-margin-sidebar" class="sidebar margin-sidebar">
        <nav id="TOC" role="doc-toc" class="toc-active">
    <h2 id="toc-title">On this page</h2>
   
  <ul>
  <li><a href="#how-to-work" id="toc-how-to-work" class="nav-link active" data-scroll-target="#how-to-work">How to work</a></li>
  <li><a href="#activity-1.-repair-the-statement-10-minutes" id="toc-activity-1.-repair-the-statement-10-minutes" class="nav-link" data-scroll-target="#activity-1.-repair-the-statement-10-minutes">Activity 1. Repair the statement — 10 minutes</a></li>
  <li><a href="#activity-2.-reading-a-population-20-minutes" id="toc-activity-2.-reading-a-population-20-minutes" class="nav-link" data-scroll-target="#activity-2.-reading-a-population-20-minutes">Activity 2. Reading a population — 20 minutes</a>
  <ul class="collapse">
  <li><a href="#a-school-survey-of-12-year-olds-in-three-districts-near-plovdiv" id="toc-a-school-survey-of-12-year-olds-in-three-districts-near-plovdiv" class="nav-link" data-scroll-target="#a-school-survey-of-12-year-olds-in-three-districts-near-plovdiv">A school survey of 12-year-olds in three districts near Plovdiv</a></li>
  </ul></li>
  <li><a href="#activity-3.-sorting-the-measures-15-minutes" id="toc-activity-3.-sorting-the-measures-15-minutes" class="nav-link" data-scroll-target="#activity-3.-sorting-the-measures-15-minutes">Activity 3. Sorting the measures — 15 minutes</a></li>
  <li><a href="#activity-4.-spending-a-prevention-budget-15-minutes" id="toc-activity-4.-spending-a-prevention-budget-15-minutes" class="nav-link" data-scroll-target="#activity-4.-spending-a-prevention-budget-15-minutes">Activity 4. Spending a prevention budget — 15 minutes</a>
  <ul class="collapse">
  <li><a href="#a-district-programme-for-one-school-year" id="toc-a-district-programme-for-one-school-year" class="nav-link" data-scroll-target="#a-district-programme-for-one-school-year">A district programme for one school year</a></li>
  </ul></li>
  <li><a href="#cross-group-discussion-10-minutes" id="toc-cross-group-discussion-10-minutes" class="nav-link" data-scroll-target="#cross-group-discussion-10-minutes">Cross-group discussion — 10 minutes</a></li>
  <li><a href="#individual-exit-ticket-5-minutes" id="toc-individual-exit-ticket-5-minutes" class="nav-link" data-scroll-target="#individual-exit-ticket-5-minutes">Individual exit ticket — 5 minutes</a>
  <ul class="collapse">
  <li><a href="#feedback-criteria" id="toc-feedback-criteria" class="nav-link" data-scroll-target="#feedback-criteria">Feedback criteria</a></li>
  </ul></li>
  </ul>
</nav>
    </div>
<!-- main -->
<main class="content quarto-banner-title-block" id="quarto-document-content">






<p><a href="../15-minute-learning/dental-public-health-introduction.html">15-minute reading</a> · <a href="../2026-2027-classes/dental-01-bg.pdf">Slides (PDF)</a></p>
<section id="how-to-work" class="level2">
<h2 class="anchored" data-anchor-id="how-to-work">How to work</h2>
<p>Complete the reading first, then work in groups of three or four. The reading takes <strong>15 minutes</strong> and the activities below take <strong>75 minutes</strong>, making a 90-minute session. Assign a facilitator, a recorder and a spokesperson, and rotate the roles between activities. Every group completes all four activities. Open each model answer only after you have written down your own.</p>
<p>The districts are real place names used to make the setting familiar. <strong>All survey figures, costs, effect sizes and programmes below are fictional</strong> and do not describe actual practice in these areas. Bring a calculator; the arithmetic is deliberately simple, and it is the interpretation that is assessed.</p>
<p><strong>Submit one group sheet</strong> containing the corrected statements, the completed survey table with your calculations, the classification of measures, your budget allocation with the figures supporting it, and the group’s final rule. Each student also completes the exit ticket individually.</p>
</section>
<section id="activity-1.-repair-the-statement-10-minutes" class="level2">
<h2 class="anchored" data-anchor-id="activity-1.-repair-the-statement-10-minutes">Activity 1. Repair the statement — 10 minutes</h2>
<p>Rewrite each statement in one or two sentences so that it becomes defensible, and say in one clause what was wrong with the original.</p>
<ol type="1">
<li>“Dental public health is what a dentist does when there are no patients to treat.”</li>
<li>“If the mean DMFT of a district falls, the programme worked.”</li>
<li>“The most efficient programme is the one that targets the children at highest risk.”</li>
<li>“Oral health means having no untreated caries.”</li>
<li>“Planning a dental service means looking at how many patients we see and extrapolating.”</li>
<li>“Preventing oral disease is a matter for dentists.”</li>
</ol>
<div class="callout callout-style-default callout-note callout-titled" title="Model answer: repairing the statements">
<div class="callout-header d-flex align-content-center collapsed" data-bs-toggle="collapse" data-bs-target=".callout-1-contents" aria-controls="callout-1" aria-expanded="false" aria-label="Toggle callout">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-title-container flex-fill">
<span class="screen-reader-only">Note</span>Model answer: repairing the statements
</div>
<div class="callout-btn-toggle d-inline-block border-0 py-1 ps-1 pe-0 float-end"><i class="callout-toggle"></i></div>
</div>
<div id="callout-1" class="callout-1-contents callout-collapse collapse">
<div class="callout-body-container callout-body">
<p><strong>1.</strong> Dental public health is a distinct discipline whose patient is the community: it assesses the oral health of populations, plans services and programmes, and evaluates them. It is not clinical dentistry performed in spare time, and it uses methods — surveys, statistics, policy, financing — that chairside practice does not.</p>
<p><strong>2.</strong> A falling mean is consistent with a programme that improved outcomes only in the already advantaged, while the gap widened. Evaluation must ask who was reached and how the distribution changed, not only what happened to the average.</p>
<p><strong>3.</strong> Targeting is often efficient per child, but a high-risk strategy cannot reach the disease held by the large moderate-risk majority — the prevention paradox. Efficiency per child and impact on the population are different questions, and the cost of <em>finding</em> the high-risk group is frequently omitted from the comparison.</p>
<p><strong>4.</strong> The FDI definition covers speaking, smiling, tasting, chewing, swallowing and conveying emotion, with confidence and without pain or discomfort. A mouth can be caries-free and still fail on function, comfort or appearance.</p>
<p><strong>5.</strong> Activity data describe the people who already attend. Those with the greatest untreated need are systematically the least represented in it, so planning from the appointment book serves attenders better and never discovers the rest. Need must be measured in the population.</p>
<p><strong>6.</strong> Oral diseases share their main risk factors — sugar, tobacco, alcohol, poor diet — with the major chronic diseases, so the most powerful measures are taxation, school food policy and tobacco control, none of which a dentist controls. This is the common risk factor approach, and it is the argument for working with people outside dentistry.</p>
</div>
</div>
</div>
</section>
<section id="activity-2.-reading-a-population-20-minutes" class="level2">
<h2 class="anchored" data-anchor-id="activity-2.-reading-a-population-20-minutes">Activity 2. Reading a population — 20 minutes</h2>
<section id="a-school-survey-of-12-year-olds-in-three-districts-near-plovdiv" class="level3">
<h3 class="anchored" data-anchor-id="a-school-survey-of-12-year-olds-in-three-districts-near-plovdiv">A school survey of 12-year-olds in three districts near Plovdiv</h3>
<p>A fictional survey applies WHO methodology to 12-year-olds in three districts. D, M and F are the <strong>total counts of teeth</strong> in each category across all children examined. SiC is the Significant Caries Index — the mean DMFT of the third of children with the highest scores — and is supplied for you.</p>
<div class="table-responsive">
<table class="caption-top table">
<thead>
<tr class="header">
<th>District</th>
<th style="text-align: right;">Children examined</th>
<th style="text-align: right;">D</th>
<th style="text-align: right;">M</th>
<th style="text-align: right;">F</th>
<th style="text-align: right;">Caries-free</th>
<th style="text-align: right;">SiC</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td>Rodopi</td>
<td style="text-align: right;">200</td>
<td style="text-align: right;">300</td>
<td style="text-align: right;">20</td>
<td style="text-align: right;">80</td>
<td style="text-align: right;">38%</td>
<td style="text-align: right;">4.8</td>
</tr>
<tr class="even">
<td>Trakiya</td>
<td style="text-align: right;">150</td>
<td style="text-align: right;">120</td>
<td style="text-align: right;">15</td>
<td style="text-align: right;">165</td>
<td style="text-align: right;">45%</td>
<td style="text-align: right;">3.6</td>
</tr>
<tr class="odd">
<td>Maritsa</td>
<td style="text-align: right;">250</td>
<td style="text-align: right;">600</td>
<td style="text-align: right;">50</td>
<td style="text-align: right;">100</td>
<td style="text-align: right;">22%</td>
<td style="text-align: right;">6.9</td>
</tr>
</tbody>
</table>
</div>
<ol type="1">
<li>Calculate the mean DMFT for each district. Compare each with the WHO goal of a DMFT of 3 or below at age 12.</li>
<li>Calculate the <strong>care index</strong> (F ÷ DMFT × 100) for each district. State in one sentence what a low value indicates.</li>
<li>Rodopi and Trakiya have the same mean DMFT. Identify what differs between them, and state what different action each district needs. Do not propose the same programme for both.</li>
<li>Compare the mean with the SiC in each district. What does a large gap tell you about how the disease is distributed, and why would a district-wide average mislead a planner here?</li>
<li>Name two pieces of information the table does not contain that you would need before recommending a programme. Explain why the arithmetic alone cannot rank the districts by priority.</li>
</ol>
<div class="callout callout-style-default callout-note callout-titled" title="Model answer: interpreting the survey">
<div class="callout-header d-flex align-content-center collapsed" data-bs-toggle="collapse" data-bs-target=".callout-2-contents" aria-controls="callout-2" aria-expanded="false" aria-label="Toggle callout">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-title-container flex-fill">
<span class="screen-reader-only">Note</span>Model answer: interpreting the survey
</div>
<div class="callout-btn-toggle d-inline-block border-0 py-1 ps-1 pe-0 float-end"><i class="callout-toggle"></i></div>
</div>
<div id="callout-2" class="callout-2-contents callout-collapse collapse">
<div class="callout-body-container callout-body">
<p><strong>Mean DMFT.</strong> Rodopi (300 + 20 + 80) ÷ 200 = <strong>2.0</strong>. Trakiya (120 + 15 + 165) ÷ 150 = <strong>2.0</strong>. Maritsa (600 + 50 + 100) ÷ 250 = <strong>3.0</strong>. Rodopi and Trakiya meet the WHO goal; Maritsa sits at its limit and fails it for the average child.</p>
<p><strong>Care index.</strong> Rodopi 80 ÷ 400 = <strong>20%</strong>. Trakiya 165 ÷ 300 = <strong>55%</strong>. Maritsa 100 ÷ 750 = <strong>13.3%</strong>. A low care index means the disease that exists has largely not been treated — an access, affordability or attendance problem rather than a purely preventive one.</p>
<p><strong>Same mean, different districts.</strong> In Rodopi three-quarters of the score is untreated decay; in Trakiya more than half has been restored. Trakiya has the same accumulated disease experience but a functioning treatment pathway, so its priority is prevention — why is disease still occurring in a district that treats it? Rodopi’s priority is access: the disease is being neither prevented nor treated, and a prevention-only programme there would leave 300 untreated lesions in place.</p>
<p><strong>Mean versus SiC.</strong> The gap shows skew: the disease is concentrated in a minority. Rodopi’s mean of 2.0 against a SiC of 4.8 means the worst-affected third carries well over twice the district average, and a planner reading only “2.0, goal met” would conclude that Rodopi needs nothing. Maritsa is both the worst on average and the most severe at the top (SiC 6.9). Averages hide the children who most need the programme.</p>
<p><strong>Missing information.</strong> Reasonable answers include: the age distribution of untreated lesions and whether any are causing pain or sepsis; the number and distribution of dentists and whether they treat children; travel distance and transport; fluoride exposure; socioeconomic composition of each district; whether the survey examiners were calibrated; and whether the three samples are comparable. Ranking by DMFT alone treats a district with poor access and one with poor prevention as the same problem, and they are not.</p>
</div>
</div>
</div>
</section>
</section>
<section id="activity-3.-sorting-the-measures-15-minutes" class="level2">
<h2 class="anchored" data-anchor-id="activity-3.-sorting-the-measures-15-minutes">Activity 3. Sorting the measures — 15 minutes</h2>
<p>Classify each measure in the table. For “level”, use primary, secondary or tertiary prevention. For “acts on”, state whether it changes an individual’s behaviour or changes the environment in which everybody makes choices.</p>
<div class="table-responsive">
<table class="caption-top table">
<colgroup>
<col style="width: 25%">
<col style="width: 25%">
<col style="width: 25%">
<col style="width: 25%">
</colgroup>
<thead>
<tr class="header">
<th>Measure</th>
<th>Level</th>
<th>Who must act</th>
<th>Acts on</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td>Sealing a first permanent molar</td>
<td></td>
<td></td>
<td></td>
</tr>
<tr class="even">
<td>Fluoride varnish twice a year in a school</td>
<td></td>
<td></td>
<td></td>
</tr>
<tr class="odd">
<td>Removing sugary drinks from school canteens</td>
<td></td>
<td></td>
<td></td>
</tr>
<tr class="even">
<td>Restoring a cavitated lesion</td>
<td></td>
<td></td>
<td></td>
</tr>
<tr class="odd">
<td>Examining the oral mucosa of a 60-year-old smoker at a routine check-up</td>
<td></td>
<td></td>
<td></td>
</tr>
<tr class="even">
<td>A tax on sugar-sweetened beverages</td>
<td></td>
<td></td>
<td></td>
</tr>
<tr class="odd">
<td>Providing a denture to an edentulous patient</td>
<td></td>
<td></td>
<td></td>
</tr>
<tr class="even">
<td>Training teachers to supervise daily toothbrushing</td>
<td></td>
<td></td>
<td></td>
</tr>
<tr class="odd">
<td>Extending the insurance package to two check-ups a year for children</td>
<td></td>
<td></td>
<td></td>
</tr>
</tbody>
</table>
</div>
<ol type="1">
<li>Complete the table.</li>
<li>Identify the two measures that would improve outcomes beyond the mouth, and name the condition they would also affect.</li>
<li>Two measures require no action at all from the child or family in order to work. Identify them and explain why that property matters for inequalities.</li>
<li>Choose one measure you classified as acting on the environment and describe who, outside dentistry, would have to be persuaded.</li>
</ol>
<div class="callout callout-style-default callout-note callout-titled" title="Model answer: classification">
<div class="callout-header d-flex align-content-center collapsed" data-bs-toggle="collapse" data-bs-target=".callout-3-contents" aria-controls="callout-3" aria-expanded="false" aria-label="Toggle callout">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-title-container flex-fill">
<span class="screen-reader-only">Note</span>Model answer: classification
</div>
<div class="callout-btn-toggle d-inline-block border-0 py-1 ps-1 pe-0 float-end"><i class="callout-toggle"></i></div>
</div>
<div id="callout-3" class="callout-3-contents callout-collapse collapse">
<div class="callout-body-container callout-body">
<p>Sealant — primary, dentist or therapist, individual. School varnish — primary, dental service with the school, individual but delivered at population scale. Removing sugary drinks — primary, school and municipality, environment. Restoration — secondary (limiting progression of established disease), dentist, individual. Mucosal examination — secondary (early detection), dentist, individual. Sugar tax — primary, parliament and ministry of finance, environment. Denture — tertiary (restoring function after disease), dentist and technician, individual. Supervised brushing — primary, school and dental service, individual behaviour delivered through an environment. Insurance extension — enables mostly secondary prevention, insurance fund and ministry, environment.</p>
<p><strong>Beyond the mouth.</strong> The sugar tax and the canteen policy also affect obesity, type 2 diabetes and cardiovascular disease; tobacco measures would qualify equally. This is the common risk factor approach in practice.</p>
<p><strong>No action required from the family.</strong> The sugar tax and the canteen policy work whether or not a parent is informed, motivated, literate or available. Measures that require the family to act — attend, register, buy, remember — are taken up first by those with the most time, money and information, so they can widen the gap even while improving the average. Measures built into the environment reach everyone by default, which is why they tend to be the most equitable.</p>
<p><strong>Outside dentistry.</strong> For the canteen policy: the head teacher, the parents’ council, the municipal education department and the catering contractor. For the tax: the ministry of finance, which will want revenue and compliance arguments rather than DMFT figures — which is why the general-health framing matters.</p>
</div>
</div>
</div>
</section>
<section id="activity-4.-spending-a-prevention-budget-15-minutes" class="level2">
<h2 class="anchored" data-anchor-id="activity-4.-spending-a-prevention-budget-15-minutes">Activity 4. Spending a prevention budget — 15 minutes</h2>
<section id="a-district-programme-for-one-school-year" class="level3">
<h3 class="anchored" data-anchor-id="a-district-programme-for-one-school-year">A district programme for one school year</h3>
<p>A district has <strong>2,400 twelve-year-olds</strong> and a prevention budget of <strong>12,000 BGN</strong> for one school year. All figures below are fictional teaching values.</p>
<p>Without any programme, the distribution of new disease is uneven: the highest-risk 10% (240 children) develop on average <strong>1.5</strong> lesions each, and the remaining 2,160 children develop <strong>0.33</strong> each — about <strong>1,070 new lesions</strong> across the cohort each year.</p>
<div class="table-responsive">
<table class="caption-top table">
<colgroup>
<col style="width: 21%">
<col style="width: 28%">
<col style="width: 28%">
<col style="width: 21%">
</colgroup>
<thead>
<tr class="header">
<th>Option</th>
<th style="text-align: right;">Cost per child</th>
<th style="text-align: right;">Lesions averted per child</th>
<th>Eligible group</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td>A · Sealants for the highest-risk children</td>
<td style="text-align: right;">20 BGN</td>
<td style="text-align: right;">0.60</td>
<td>the highest-risk 10% only</td>
</tr>
<tr class="even">
<td>B · Fluoride varnish, two applications</td>
<td style="text-align: right;">12 BGN</td>
<td style="text-align: right;">0.18</td>
<td>any child</td>
</tr>
<tr class="odd">
<td>C · Supervised toothbrushing and education</td>
<td style="text-align: right;">5 BGN</td>
<td style="text-align: right;">0.10</td>
<td>any child, delivered whole-class</td>
</tr>
</tbody>
</table>
</div>
<ol type="1">
<li>Confirm that the highest-risk 10% account for 360 of the roughly 1,070 lesions. If a programme prevented <strong>every</strong> lesion in that group, what proportion of the district’s disease would remain? What does your answer illustrate?</li>
<li>For each option used alone within the 12,000 BGN budget, calculate the children reached, the lesions averted and the cost per lesion averted. Note where the budget, not the option, is the binding constraint.</li>
<li>Propose a mixed allocation that spends exactly 12,000 BGN. Report its lesions averted, children reached and cost per lesion averted, and compare it with the best single option.</li>
<li>Option A requires knowing which children are in the highest-risk 10%. Identifying them requires screening the whole cohort at <strong>2 BGN per child</strong>, a cost not included in the table. Recalculate the allocation from question 3 with this cost included. Does your recommendation change?</li>
<li>Recommend an allocation and defend it in 100–150 words. State which consideration other than lesions averted carried weight, and name one fact that would make you change your mind.</li>
</ol>
<div class="callout callout-style-default callout-note callout-titled" title="Model answer: the arithmetic and the judgement">
<div class="callout-header d-flex align-content-center collapsed" data-bs-toggle="collapse" data-bs-target=".callout-4-contents" aria-controls="callout-4" aria-expanded="false" aria-label="Toggle callout">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-title-container flex-fill">
<span class="screen-reader-only">Note</span>Model answer: the arithmetic and the judgement
</div>
<div class="callout-btn-toggle d-inline-block border-0 py-1 ps-1 pe-0 float-end"><i class="callout-toggle"></i></div>
</div>
<div id="callout-4" class="callout-4-contents callout-collapse collapse">
<div class="callout-body-container callout-body">
<p><strong>1.</strong> 240 × 1.5 = <strong>360</strong> lesions; 2,160 × 0.33 ≈ <strong>710</strong>. Preventing all 360 would still leave about 710 of 1,070 — roughly <strong>two-thirds</strong> — in place. This is the prevention paradox: the large moderate-risk majority carries most of the disease, so a strategy aimed only at the extreme cannot move the district’s total very far.</p>
<p><strong>2.</strong> Option A is limited by the eligible group, not the budget: 240 children × 20 = <strong>4,800 BGN</strong>, averting 240 × 0.60 = <strong>144</strong> lesions at <strong>33.33 BGN</strong> per lesion, with 7,200 BGN unspent. Option B is limited by the budget: 12,000 ÷ 12 = <strong>1,000 children</strong>, averting 180 lesions at <strong>66.67 BGN</strong> each. Option C covers the whole cohort exactly: 2,400 × 5 = <strong>12,000 BGN</strong>, averting 240 lesions at <strong>50.00 BGN</strong> each.</p>
<p><strong>3.</strong> A defensible mix is A for all 240 high-risk children (4,800 BGN, 144 lesions) plus C for 1,440 further children with the remaining 7,200 BGN (144 lesions). Total <strong>288 lesions averted</strong>, <strong>1,680 children reached</strong>, <strong>41.67 BGN</strong> per lesion — better than any single option on lesions averted, but it leaves 720 children with nothing, and someone must decide which schools they are.</p>
<p><strong>4.</strong> Screening the cohort costs 2,400 × 2 = <strong>4,800 BGN</strong>. Option A now costs 9,600 BGN for 144 lesions (<strong>66.67</strong> per lesion), leaving 2,400 BGN, which buys toothbrushing for 480 children and 48 further lesions: <strong>192 lesions, 720 children reached</strong>. Universal toothbrushing alone now dominates it on both counts — 240 lesions and 2,400 children for the same money. The cost of <em>finding</em> the high-risk group is what defeats targeting here, and it is routinely left out of such comparisons.</p>
<p><strong>5.</strong> On the figures as given, universal supervised toothbrushing is the strongest single answer once identification costs are counted: it averts the most lesions, reaches every child, requires nothing of the family, and builds a habit whose benefit continues after the year ends — none of which the one-year arithmetic captures. A group that prefers the mixed allocation of question 3 can defend it, provided it states that 720 children are excluded and explains how those schools were chosen. Facts that would change the recommendation include a cheaper way to identify high-risk children (for instance, existing school or social data), a much larger effect from sealants in this cohort, a district where most children already brush under supervision, or evidence that the untreated decay in the survey needs treatment before prevention is meaningful.</p>
</div>
</div>
</div>
</section>
</section>
<section id="cross-group-discussion-10-minutes" class="level2">
<h2 class="anchored" data-anchor-id="cross-group-discussion-10-minutes">Cross-group discussion — 10 minutes</h2>
<p>Each group states its allocation in one minute and names the strongest objection to it.</p>
<p>Then consider the connection between the two halves of the session. Rodopi in Activity 2 had a care index of 20% — three-quarters of its disease untreated. Would you spend a prevention budget there at all, or does untreated disease have a prior claim? Agree on a four-sentence class rule covering <strong>what to measure, who to involve, how to decide between efficiency and coverage, and how to check afterwards whether the programme widened or narrowed the gap</strong>.</p>
<div class="callout callout-style-default callout-note callout-titled" title="Discussion guide">
<div class="callout-header d-flex align-content-center collapsed" data-bs-toggle="collapse" data-bs-target=".callout-5-contents" aria-controls="callout-5" aria-expanded="false" aria-label="Toggle callout">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-title-container flex-fill">
<span class="screen-reader-only">Note</span>Discussion guide
</div>
<div class="callout-btn-toggle d-inline-block border-0 py-1 ps-1 pe-0 float-end"><i class="callout-toggle"></i></div>
</div>
<div id="callout-5" class="callout-5-contents callout-collapse collapse">
<div class="callout-body-container callout-body">
<p>There is no single correct answer to the prevention-versus-treatment question, but the weak answers are recognisable: they treat “prevention is better than cure” as settling a question about a district that already has 300 untreated lesions in 200 children, some of which are causing pain now. A strong answer separates the two budgets and the two claims, notes that a prevention programme in a district with no access pathway produces children who are identified but not treated, and asks who is accountable for the resulting referrals.</p>
<p>Good class rules specify a measurement before and after, name the non-dental partners, state the efficiency–coverage trade-off explicitly rather than hiding it in a ratio, and commit to reporting uptake by socioeconomic group — because a programme that improves the average while widening the gradient has failed at something the average cannot show.</p>
</div>
</div>
</div>
</section>
<section id="individual-exit-ticket-5-minutes" class="level2">
<h2 class="anchored" data-anchor-id="individual-exit-ticket-5-minutes">Individual exit ticket — 5 minutes</h2>
<p>Write three short answers without reopening the model answers:</p>
<ol type="1">
<li>Two districts have the same mean DMFT. Name the single figure you would ask for next, and why.</li>
<li>State one cost that is usually left out when a targeted programme is compared with a universal one.</li>
<li>Write one sentence you could say to a head teacher, without using the word “caries”, to persuade them to change the school’s canteen.</li>
</ol>
<section id="feedback-criteria" class="level3">
<h3 class="anchored" data-anchor-id="feedback-criteria">Feedback criteria</h3>
<p>A complete response calculates correctly, distinguishes what an indicator measures from what it hides, connects a proposed measure to the level of prevention and the actor who controls it, and defends an allocation by naming the trade-off rather than concealing it in a single ratio. Quoting the definition of dental public health, listing the four principles of prevention, or asserting that prevention is always better than treatment does not meet the task.</p>


</section>
</section>

</main> <!-- /main -->
<script id="quarto-html-after-body" type="application/javascript">
  window.document.addEventListener("DOMContentLoaded", function (event) {
    // Ensure there is a toggle, if there isn't float one in the top right
    if (window.document.querySelector('.quarto-color-scheme-toggle') === null) {
      const a = window.document.createElement('a');
      a.classList.add('top-right');
      a.classList.add('quarto-color-scheme-toggle');
      a.href = "";
      a.onclick = function() { try { window.quartoToggleColorScheme(); } catch {} return false; };
      const i = window.document.createElement("i");
      i.classList.add('bi');
      a.appendChild(i);
      window.document.body.appendChild(a);
    }
    setColorSchemeToggle(hasAlternateSentinel())
    const icon = "";
    const anchorJS = new window.AnchorJS();
    anchorJS.options = {
      placement: 'right',
      icon: icon
    };
    anchorJS.add('.anchored');
    const isCodeAnnotation = (el) => {
      for (const clz of el.classList) {
        if (clz.startsWith('code-annotation-')) {                     
          return true;
        }
      }
      return false;
    }
    const onCopySuccess = function(e) {
      // button target
      const button = e.trigger;
      // don't keep focus
      button.blur();
      // flash "checked"
      button.classList.add('code-copy-button-checked');
      var currentTitle = button.getAttribute("title");
      button.setAttribute("title", "Copied!");
      let tooltip;
      if (window.bootstrap) {
        button.setAttribute("data-bs-toggle", "tooltip");
        button.setAttribute("data-bs-placement", "left");
        button.setAttribute("data-bs-title", "Copied!");
        tooltip = new bootstrap.Tooltip(button, 
          { trigger: "manual", 
            customClass: "code-copy-button-tooltip",
            offset: [0, -8]});
        tooltip.show();    
      }
      setTimeout(function() {
        if (tooltip) {
          tooltip.hide();
          button.removeAttribute("data-bs-title");
          button.removeAttribute("data-bs-toggle");
          button.removeAttribute("data-bs-placement");
        }
        button.setAttribute("title", currentTitle);
        button.classList.remove('code-copy-button-checked');
      }, 1000);
      // clear code selection
      e.clearSelection();
    }
    const getTextToCopy = function(trigger) {
      const outerScaffold = trigger.parentElement.cloneNode(true);
      const codeEl = outerScaffold.querySelector('code');
      for (const childEl of codeEl.children) {
        if (isCodeAnnotation(childEl)) {
          childEl.remove();
        }
      }
      return codeEl.innerText;
    }
    const clipboard = new window.ClipboardJS('.code-copy-button:not([data-in-quarto-modal])', {
      text: getTextToCopy
    });
    clipboard.on('success', onCopySuccess);
    if (window.document.getElementById('quarto-embedded-source-code-modal')) {
      const clipboardModal = new window.ClipboardJS('.code-copy-button[data-in-quarto-modal]', {
        text: getTextToCopy,
        container: window.document.getElementById('quarto-embedded-source-code-modal')
      });
      clipboardModal.on('success', onCopySuccess);
    }
      var localhostRegex = new RegExp(/^(?:http|https):\/\/localhost\:?[0-9]*\//);
      var mailtoRegex = new RegExp(/^mailto:/);
        var filterRegex = new RegExp("https:\/\/kostadinoff\.github\.io");
      var isInternal = (href) => {
          return filterRegex.test(href) || localhostRegex.test(href) || mailtoRegex.test(href);
      }
      // Inspect non-navigation links and adorn them if external
     var links = window.document.querySelectorAll('a[href]:not(.nav-link):not(.navbar-brand):not(.toc-action):not(.sidebar-link):not(.sidebar-item-toggle):not(.pagination-link):not(.no-external):not([aria-hidden]):not(.dropdown-item):not(.quarto-navigation-tool):not(.about-link)');
      for (var i=0; i<links.length; i++) {
        const link = links[i];
        if (!isInternal(link.href)) {
          // undo the damage that might have been done by quarto-nav.js in the case of
          // links that we want to consider external
          if (link.dataset.originalHref !== undefined) {
            link.href = link.dataset.originalHref;
          }
        }
      }
    function tippyHover(el, contentFn, onTriggerFn, onUntriggerFn) {
      const config = {
        allowHTML: true,
        maxWidth: 500,
        delay: 100,
        arrow: false,
        appendTo: function(el) {
            return el.parentElement;
        },
        interactive: true,
        interactiveBorder: 10,
        theme: 'quarto',
        placement: 'bottom-start',
      };
      if (contentFn) {
        config.content = contentFn;
      }
      if (onTriggerFn) {
        config.onTrigger = onTriggerFn;
      }
      if (onUntriggerFn) {
        config.onUntrigger = onUntriggerFn;
      }
      window.tippy(el, config); 
    }
    const noterefs = window.document.querySelectorAll('a[role="doc-noteref"]');
    for (var i=0; i<noterefs.length; i++) {
      const ref = noterefs[i];
      tippyHover(ref, function() {
        // use id or data attribute instead here
        let href = ref.getAttribute('data-footnote-href') || ref.getAttribute('href');
        try { href = new URL(href).hash; } catch {}
        const id = href.replace(/^#\/?/, "");
        const note = window.document.getElementById(id);
        if (note) {
          return note.innerHTML;
        } else {
          return "";
        }
      });
    }
    const xrefs = window.document.querySelectorAll('a.quarto-xref');
    const processXRef = (id, note) => {
      // Strip column container classes
      const stripColumnClz = (el) => {
        el.classList.remove("page-full", "page-columns");
        if (el.children) {
          for (const child of el.children) {
            stripColumnClz(child);
          }
        }
      }
      stripColumnClz(note)
      if (id === null || id.startsWith('sec-')) {
        // Special case sections, only their first couple elements
        const container = document.createElement("div");
        if (note.children && note.children.length > 2) {
          container.appendChild(note.children[0].cloneNode(true));
          for (let i = 1; i < note.children.length; i++) {
            const child = note.children[i];
            if (child.tagName === "P" && child.innerText === "") {
              continue;
            } else {
              container.appendChild(child.cloneNode(true));
              break;
            }
          }
          if (window.Quarto?.typesetMath) {
            window.Quarto.typesetMath(container);
          }
          return container.innerHTML
        } else {
          if (window.Quarto?.typesetMath) {
            window.Quarto.typesetMath(note);
          }
          return note.innerHTML;
        }
      } else {
        // Remove any anchor links if they are present
        const anchorLink = note.querySelector('a.anchorjs-link');
        if (anchorLink) {
          anchorLink.remove();
        }
        if (window.Quarto?.typesetMath) {
          window.Quarto.typesetMath(note);
        }
        if (note.classList.contains("callout")) {
          return note.outerHTML;
        } else {
          return note.innerHTML;
        }
      }
    }
    for (var i=0; i<xrefs.length; i++) {
      const xref = xrefs[i];
      tippyHover(xref, undefined, function(instance) {
        instance.disable();
        let url = xref.getAttribute('href');
        let hash = undefined; 
        if (url.startsWith('#')) {
          hash = url;
        } else {
          try { hash = new URL(url).hash; } catch {}
        }
        if (hash) {
          const id = hash.replace(/^#\/?/, "");
          const note = window.document.getElementById(id);
          if (note !== null) {
            try {
              const html = processXRef(id, note.cloneNode(true));
              instance.setContent(html);
            } finally {
              instance.enable();
              instance.show();
            }
          } else {
            // See if we can fetch this
            fetch(url.split('#')[0])
            .then(res => res.text())
            .then(html => {
              const parser = new DOMParser();
              const htmlDoc = parser.parseFromString(html, "text/html");
              const note = htmlDoc.getElementById(id);
              if (note !== null) {
                const html = processXRef(id, note);
                instance.setContent(html);
              } 
            }).finally(() => {
              instance.enable();
              instance.show();
            });
          }
        } else {
          // See if we can fetch a full url (with no hash to target)
          // This is a special case and we should probably do some content thinning / targeting
          fetch(url)
          .then(res => res.text())
          .then(html => {
            const parser = new DOMParser();
            const htmlDoc = parser.parseFromString(html, "text/html");
            const note = htmlDoc.querySelector('main.content');
            if (note !== null) {
              // This should only happen for chapter cross references
              // (since there is no id in the URL)
              // remove the first header
              if (note.children.length > 0 && note.children[0].tagName === "HEADER") {
                note.children[0].remove();
              }
              const html = processXRef(null, note);
              instance.setContent(html);
            } 
          }).finally(() => {
            instance.enable();
            instance.show();
          });
        }
      }, function(instance) {
      });
    }
        let selectedAnnoteEl;
        const selectorForAnnotation = ( cell, annotation) => {
          let cellAttr = 'data-code-cell="' + cell + '"';
          let lineAttr = 'data-code-annotation="' +  annotation + '"';
          const selector = 'span[' + cellAttr + '][' + lineAttr + ']';
          return selector;
        }
        const selectCodeLines = (annoteEl) => {
          const doc = window.document;
          const targetCell = annoteEl.getAttribute("data-target-cell");
          const targetAnnotation = annoteEl.getAttribute("data-target-annotation");
          const annoteSpan = window.document.querySelector(selectorForAnnotation(targetCell, targetAnnotation));
          const lines = annoteSpan.getAttribute("data-code-lines").split(",");
          const lineIds = lines.map((line) => {
            return targetCell + "-" + line;
          })
          let top = null;
          let height = null;
          let parent = null;
          if (lineIds.length > 0) {
              //compute the position of the single el (top and bottom and make a div)
              const el = window.document.getElementById(lineIds[0]);
              top = el.offsetTop;
              height = el.offsetHeight;
              parent = el.parentElement.parentElement;
            if (lineIds.length > 1) {
              const lastEl = window.document.getElementById(lineIds[lineIds.length - 1]);
              const bottom = lastEl.offsetTop + lastEl.offsetHeight;
              height = bottom - top;
            }
            if (top !== null && height !== null && parent !== null) {
              // cook up a div (if necessary) and position it 
              let div = window.document.getElementById("code-annotation-line-highlight");
              if (div === null) {
                div = window.document.createElement("div");
                div.setAttribute("id", "code-annotation-line-highlight");
                div.style.position = 'absolute';
                parent.appendChild(div);
              }
              div.style.top = top - 2 + "px";
              div.style.height = height + 4 + "px";
              div.style.left = 0;
              let gutterDiv = window.document.getElementById("code-annotation-line-highlight-gutter");
              if (gutterDiv === null) {
                gutterDiv = window.document.createElement("div");
                gutterDiv.setAttribute("id", "code-annotation-line-highlight-gutter");
                gutterDiv.style.position = 'absolute';
                const codeCell = window.document.getElementById(targetCell);
                const gutter = codeCell.querySelector('.code-annotation-gutter');
                gutter.appendChild(gutterDiv);
              }
              gutterDiv.style.top = top - 2 + "px";
              gutterDiv.style.height = height + 4 + "px";
            }
            selectedAnnoteEl = annoteEl;
          }
        };
        const unselectCodeLines = () => {
          const elementsIds = ["code-annotation-line-highlight", "code-annotation-line-highlight-gutter"];
          elementsIds.forEach((elId) => {
            const div = window.document.getElementById(elId);
            if (div) {
              div.remove();
            }
          });
          selectedAnnoteEl = undefined;
        };
          // Handle positioning of the toggle
      window.addEventListener(
        "resize",
        throttle(() => {
          elRect = undefined;
          if (selectedAnnoteEl) {
            selectCodeLines(selectedAnnoteEl);
          }
        }, 10)
      );
      function throttle(fn, ms) {
      let throttle = false;
      let timer;
        return (...args) => {
          if(!throttle) { // first call gets through
              fn.apply(this, args);
              throttle = true;
          } else { // all the others get throttled
              if(timer) clearTimeout(timer); // cancel #2
              timer = setTimeout(() => {
                fn.apply(this, args);
                timer = throttle = false;
              }, ms);
          }
        };
      }
        // Attach click handler to the DT
        const annoteDls = window.document.querySelectorAll('dt[data-target-cell]');
        for (const annoteDlNode of annoteDls) {
          annoteDlNode.addEventListener('click', (event) => {
            const clickedEl = event.target;
            if (clickedEl !== selectedAnnoteEl) {
              unselectCodeLines();
              const activeEl = window.document.querySelector('dt[data-target-cell].code-annotation-active');
              if (activeEl) {
                activeEl.classList.remove('code-annotation-active');
              }
              selectCodeLines(clickedEl);
              clickedEl.classList.add('code-annotation-active');
            } else {
              // Unselect the line
              unselectCodeLines();
              clickedEl.classList.remove('code-annotation-active');
            }
          });
        }
    const findCites = (el) => {
      const parentEl = el.parentElement;
      if (parentEl) {
        const cites = parentEl.dataset.cites;
        if (cites) {
          return {
            el,
            cites: cites.split(' ')
          };
        } else {
          return findCites(el.parentElement)
        }
      } else {
        return undefined;
      }
    };
    var bibliorefs = window.document.querySelectorAll('a[role="doc-biblioref"]');
    for (var i=0; i<bibliorefs.length; i++) {
      const ref = bibliorefs[i];
      const citeInfo = findCites(ref);
      if (citeInfo) {
        tippyHover(citeInfo.el, function() {
          var popup = window.document.createElement('div');
          citeInfo.cites.forEach(function(cite) {
            var citeDiv = window.document.createElement('div');
            citeDiv.classList.add('hanging-indent');
            citeDiv.classList.add('csl-entry');
            var biblioDiv = window.document.getElementById('ref-' + cite);
            if (biblioDiv) {
              citeDiv.innerHTML = biblioDiv.innerHTML;
            }
            popup.appendChild(citeDiv);
          });
          return popup.innerHTML;
        });
      }
    }
  });
  </script>
</div> <!-- /content -->
<footer class="footer">
  <div class="nav-footer">
    <div class="nav-footer-left">
<p>Email me at <a href="mailto:kostadinr.kostadinov@mu-plovdiv.bg">kostadinr.kostadinov@mu-plovdiv.bg</a> or book a <a href="https://tinyurl.com/whentomeetme" target="_blank">meeting</a></p>
</div>   
    <div class="nav-footer-center">
      &nbsp;
    </div>
    <div class="nav-footer-right">
<p>Built with <a href="https://quarto.org" target="_blank">Quarto</a></p>
</div>
  </div>
</footer>




</body></html>