<!DOCTYPE html>
<html xmlns="http://www.w3.org/1999/xhtml" lang="en" xml:lang="en"><head>

<meta charset="utf-8">
<meta name="generator" content="quarto-1.7.17">

<meta name="viewport" content="width=device-width, initial-scale=1.0, user-scalable=yes">

<meta name="author" content="Костадин Костадинов">
<meta name="dcterms.date" content="2024-11-08">
<meta name="description" content="Материалът представя основни понятия и базови познания за описание на извадкови статистики и изграждане на интервал на доверителност">

<title>Дескриптивна и инферентна статистика – Kostadin Kostadinov</title>
<style>
code{white-space: pre-wrap;}
span.smallcaps{font-variant: small-caps;}
div.columns{display: flex; gap: min(4vw, 1.5em);}
div.column{flex: auto; overflow-x: auto;}
div.hanging-indent{margin-left: 1.5em; text-indent: -1.5em;}
ul.task-list{list-style: none;}
ul.task-list li input[type="checkbox"] {
  width: 0.8em;
  margin: 0 0.8em 0.2em -1em; /* quarto-specific, see https://github.com/quarto-dev/quarto-cli/issues/4556 */ 
  vertical-align: middle;
}
</style>


<script src="../site_libs/quarto-nav/quarto-nav.js"></script>
<script src="../site_libs/quarto-nav/headroom.min.js"></script>
<script src="../site_libs/clipboard/clipboard.min.js"></script>
<script src="../site_libs/quarto-search/autocomplete.umd.js"></script>
<script src="../site_libs/quarto-search/fuse.min.js"></script>
<script src="../site_libs/quarto-search/quarto-search.js"></script>
<meta name="quarto:offset" content="../">
<script src="../site_libs/quarto-html/quarto.js" type="module"></script>
<script src="../site_libs/quarto-html/tabsets/tabsets.js" type="module"></script>
<script src="../site_libs/quarto-html/popper.min.js"></script>
<script src="../site_libs/quarto-html/tippy.umd.min.js"></script>
<script src="../site_libs/quarto-html/anchor.min.js"></script>
<link href="../site_libs/quarto-html/tippy.css" rel="stylesheet">
<link href="../site_libs/quarto-html/quarto-syntax-highlighting-da03d714c310c60cec1d83284c92da2c.css" rel="stylesheet" id="quarto-text-highlighting-styles">
<script src="../site_libs/bootstrap/bootstrap.min.js"></script>
<link href="../site_libs/bootstrap/bootstrap-icons.css" rel="stylesheet">
<link href="../site_libs/bootstrap/bootstrap-f1222f18e1d9b43d11ea295a1a746451.min.css" rel="stylesheet" append-hash="true" id="quarto-bootstrap" data-mode="light">
<script id="quarto-search-options" type="application/json">{
  "location": "navbar",
  "copy-button": false,
  "collapse-after": 3,
  "panel-placement": "end",
  "type": "overlay",
  "limit": 50,
  "keyboard-shortcut": [
    "f",
    "/",
    "s"
  ],
  "show-item-context": false,
  "language": {
    "search-no-results-text": "Без резултат",
    "search-matching-documents-text": "matching documents",
    "search-copy-link-title": "Копирай линка за търсене",
    "search-hide-matches-text": "Hide additional matches",
    "search-more-match-text": "more match in this document",
    "search-more-matches-text": "more matches in this document",
    "search-clear-button-title": "Clear",
    "search-text-placeholder": "",
    "search-detached-cancel-button-title": "Cancel",
    "search-submit-button-title": "Submit",
    "search-label": "Search"
  }
}</script>

  <script src="https://cdnjs.cloudflare.com/polyfill/v3/polyfill.min.js?features=es6"></script>
  <script src="https://cdn.jsdelivr.net/npm/mathjax@3/es5/tex-chtml-full.js" type="text/javascript"></script>

<script type="text/javascript">
const typesetMath = (el) => {
  if (window.MathJax) {
    // MathJax Typeset
    window.MathJax.typeset([el]);
  } else if (window.katex) {
    // KaTeX Render
    var mathElements = el.getElementsByClassName("math");
    var macros = [];
    for (var i = 0; i < mathElements.length; i++) {
      var texText = mathElements[i].firstChild;
      if (mathElements[i].tagName == "SPAN") {
        window.katex.render(texText.data, mathElements[i], {
          displayMode: mathElements[i].classList.contains('display'),
          throwOnError: false,
          macros: macros,
          fleqn: false
        });
      }
    }
  }
}
window.Quarto = {
  typesetMath
};
</script>

<link rel="stylesheet" href="../styles.css">
<meta name="twitter:title" content="Дескриптивна и инферентна статистика – Kostadin Kostadinov">
<meta name="twitter:description" content="Материалът представя основни понятия и базови познания за описание на извадкови статистики и изграждане на интервал на доверителност">
<meta name="twitter:image" content="images/02-fig_1.jpeg">
<meta name="twitter:creator" content="@https://x.com/kostadinoffMD">
<meta name="twitter:card" content="summary_large_image">
</head>

<body class="nav-fixed quarto-light">

<div id="quarto-search-results"></div>
  <header id="quarto-header" class="headroom fixed-top">
    <nav class="navbar navbar-expand-lg " data-bs-theme="dark">
      <div class="navbar-container container-fluid">
      <div class="navbar-brand-container mx-auto">
    <a class="navbar-brand" href="../index.html">
    <span class="navbar-title">Kostadin Kostadinov</span>
    </a>
  </div>
            <div id="quarto-search" class="" title="Search"></div>
          <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarCollapse" aria-controls="navbarCollapse" role="menu" aria-expanded="false" aria-label="Toggle navigation" onclick="if (window.quartoToggleHeadroom) { window.quartoToggleHeadroom(); }">
  <span class="navbar-toggler-icon"></span>
</button>
          <div class="collapse navbar-collapse" id="navbarCollapse">
            <ul class="navbar-nav navbar-nav-scroll me-auto">
  <li class="nav-item">
    <a class="nav-link" href="../index.html"> 
<span class="menu-text">Home</span></a>
  </li>  
  <li class="nav-item">
    <a class="nav-link" href="../CV.html"> 
<span class="menu-text">CV</span></a>
  </li>  
  <li class="nav-item">
    <a class="nav-link" href="../teaching.html"> 
<span class="menu-text">Teaching</span></a>
  </li>  
</ul>
            <ul class="navbar-nav navbar-nav-scroll ms-auto">
  <li class="nav-item compact">
    <a class="nav-link" href="https://github.com/kostadinoff"> <i class="bi bi-github" role="img">
</i> 
<span class="menu-text"></span></a>
  </li>  
  <li class="nav-item compact">
    <a class="nav-link" href="https://x.com/kostadinoffMD"> <i class="bi bi-twitter" role="img">
</i> 
<span class="menu-text"></span></a>
  </li>  
  <li class="nav-item compact">
    <a class="nav-link" href="https://www.linkedin.com/in/kostadinovmd/"> <i class="bi bi-linkedin" role="img">
</i> 
<span class="menu-text"></span></a>
  </li>  
</ul>
          </div> <!-- /navcollapse -->
            <div class="quarto-navbar-tools">
</div>
      </div> <!-- /container-fluid -->
    </nav>
</header>
<!-- content -->
<div id="quarto-content" class="quarto-container page-columns page-rows-contents page-layout-article page-navbar">
<!-- sidebar -->
<!-- margin-sidebar -->
    <div id="quarto-margin-sidebar" class="sidebar margin-sidebar">
        <nav id="TOC" role="doc-toc" class="toc-active">
    <h2 id="toc-title">На тази страница</h2>
   
  <ul>
  <li><a href="#увод" id="toc-увод" class="nav-link active" data-scroll-target="#увод">Увод</a></li>
  <li><a href="#основни-понятия" id="toc-основни-понятия" class="nav-link" data-scroll-target="#основни-понятия">Основни понятия</a>
  <ul class="collapse">
  <li><a href="#статистически-променливи" id="toc-статистически-променливи" class="nav-link" data-scroll-target="#статистически-променливи">Статистически променливи</a></li>
  <li><a href="#скали-за-измерване" id="toc-скали-за-измерване" class="nav-link" data-scroll-target="#скали-за-измерване">Скали за измерване</a></li>
  </ul></li>
  <li><a href="#дескриптивен-статистически-анализ" id="toc-дескриптивен-статистически-анализ" class="nav-link" data-scroll-target="#дескриптивен-статистически-анализ">Дескриптивен статистически анализ</a>
  <ul class="collapse">
  <li><a href="#показатели-за-централна-тенденция" id="toc-показатели-за-централна-тенденция" class="nav-link" data-scroll-target="#показатели-за-централна-тенденция">Показатели за централна тенденция</a>
  <ul class="collapse">
  <li><a href="#средна-аритметична" id="toc-средна-аритметична" class="nav-link" data-scroll-target="#средна-аритметична">Средна аритметична</a></li>
  </ul></li>
  <li><a href="#други-показатели-за-централна-тенденция" id="toc-други-показатели-за-централна-тенденция" class="nav-link" data-scroll-target="#други-показатели-за-централна-тенденция">Други показатели за централна тенденция</a></li>
  <li><a href="#относителен-дял" id="toc-относителен-дял" class="nav-link" data-scroll-target="#относителен-дял">Относителен дял</a></li>
  </ul></li>
  <li><a href="#показатели-за-разсейване" id="toc-показатели-за-разсейване" class="nav-link" data-scroll-target="#показатели-за-разсейване">Показатели за разсейване</a>
  <ul class="collapse">
  <li><a href="#размах" id="toc-размах" class="nav-link" data-scroll-target="#размах">Размах</a></li>
  <li><a href="#стандартно-отклонение" id="toc-стандартно-отклонение" class="nav-link" data-scroll-target="#стандартно-отклонение">Стандартно отклонение</a>
  <ul class="collapse">
  <li><a href="#стандартно-отклонение-при-негрупирани-данни" id="toc-стандартно-отклонение-при-негрупирани-данни" class="nav-link" data-scroll-target="#стандартно-отклонение-при-негрупирани-данни">Стандартно отклонение при негрупирани данни</a></li>
  <li><a href="#стандартно-отклонение-при-данни-групирани-в-интервален-ред" id="toc-стандартно-отклонение-при-данни-групирани-в-интервален-ред" class="nav-link" data-scroll-target="#стандартно-отклонение-при-данни-групирани-в-интервален-ред">Стандартно отклонение при данни групирани в интервален ред</a></li>
  </ul></li>
  <li><a href="#интерквартилен-размах" id="toc-интерквартилен-размах" class="nav-link" data-scroll-target="#интерквартилен-размах">Интерквартилен размах</a></li>
  </ul></li>
  <li><a href="#инферентна-статистика" id="toc-инферентна-статистика" class="nav-link" data-scroll-target="#инферентна-статистика">Инферентна статистика</a>
  <ul class="collapse">
  <li><a href="#стандартна-грешка-на-средната-аритметична-sem" id="toc-стандартна-грешка-на-средната-аритметична-sem" class="nav-link" data-scroll-target="#стандартна-грешка-на-средната-аритметична-sem">Стандартна грешка на средната аритметична (SEM)</a></li>
  <li><a href="#интервал-на-доверителност-средна-аритметична" id="toc-интервал-на-доверителност-средна-аритметична" class="nav-link" data-scroll-target="#интервал-на-доверителност-средна-аритметична">Интервал на доверителност средна аритметична</a></li>
  <li><a href="#стандартна-грешка-и-интервал-на-доверителност-за-пропорция" id="toc-стандартна-грешка-и-интервал-на-доверителност-за-пропорция" class="nav-link" data-scroll-target="#стандартна-грешка-и-интервал-на-доверителност-за-пропорция">Стандартна грешка и интервал на доверителност за пропорция</a>
  <ul class="collapse">
  <li><a href="#важно-1" id="toc-важно-1" class="nav-link" data-scroll-target="#важно-1">Важно</a></li>
  </ul></li>
  </ul></li>
  <li><a href="#задачи-и-тестове-за-самоподготовка" id="toc-задачи-и-тестове-за-самоподготовка" class="nav-link" data-scroll-target="#задачи-и-тестове-за-самоподготовка">Задачи и тестове за самоподготовка</a>
  <ul class="collapse">
  <li><a href="#задача-1" id="toc-задача-1" class="nav-link" data-scroll-target="#задача-1">Задача 1</a></li>
  <li><a href="#задача-2" id="toc-задача-2" class="nav-link" data-scroll-target="#задача-2">Задача 2</a></li>
  <li><a href="#задача-3" id="toc-задача-3" class="nav-link" data-scroll-target="#задача-3">Задача 3</a></li>
  <li><a href="#задача-4" id="toc-задача-4" class="nav-link" data-scroll-target="#задача-4">Задача 4</a></li>
  <li><a href="#тестове" id="toc-тестове" class="nav-link" data-scroll-target="#тестове">Тестове</a></li>
  </ul></li>
  </ul>
</nav>
    </div>
<!-- main -->
<main class="content page-columns page-full" id="quarto-document-content">

<header id="title-block-header" class="quarto-title-block default">
<div class="quarto-title">
<h1 class="title">Дескриптивна и инферентна статистика</h1>
  <div class="quarto-categories">
    <div class="quarto-category">Bulgarian</div>
    <div class="quarto-category">Medical Statistics</div>
    <div class="quarto-category">Medicine | 2nd year</div>
    <div class="quarto-category">Dental medicine | 2nd year</div>
  </div>
  </div>

<div>
  <div class="description">
    Материалът представя основни понятия и базови познания за описание на извадкови статистики и изграждане на интервал на доверителност
  </div>
</div>


<div class="quarto-title-meta">

    <div>
    <div class="quarto-title-meta-heading">Автор</div>
    <div class="quarto-title-meta-contents">
             <p>Костадин Костадинов </p>
          </div>
  </div>
    
    <div>
    <div class="quarto-title-meta-heading">Публикувано</div>
    <div class="quarto-title-meta-contents">
      <p class="date">November 8, 2024</p>
    </div>
  </div>
  
    
  </div>
  


</header>


<section id="увод" class="level1">
<h1>Увод</h1>
<p>Провеждането на едно статистическо изследване е трудоемък процес, в който се изискват множество финансови, човешки и времеви ресурси. Много често не е възможно изследването на всички индивиди, които са обект на интерес. Немислимо е например да се прегледат всички пациенти със сърдечна недостатъчност, за да се установи дали ново лекарство намалява пулса им. В помощ на науката идва статистиката. Тя ни позволява изследваме малък брой единици (<strong>извадка</strong>), а резултатите от тях да обобщаваме за всички (<strong>генералната съвкупност</strong> <a href="#fn1" class="footnote-ref" id="fnref1" role="doc-noteref"><sup>1</sup></a>). На фигура <a href="#fig-sample" class="quarto-xref">Фигура&nbsp;1</a> са представени схематично посочените термини.</p>
<div id="fig-sample" class="quarto-float quarto-figure quarto-figure-center anchored" data-fig-align="center">
<figure class="quarto-float quarto-float-fig figure">
<div aria-describedby="fig-sample-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
<img src="images/02-fig_1.jpeg" class="img-fluid quarto-figure quarto-figure-center figure-img" width="401">
</div>
<figcaption class="quarto-float-caption-bottom quarto-float-caption quarto-float-fig" id="fig-sample-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
Фигура&nbsp;1: Генерална съвкупност и извадка
</figcaption>
</figure>
</div>
</section>
<section id="основни-понятия" class="level1 page-columns page-full">
<h1>Основни понятия</h1>
<div class="callout callout-style-default callout-warning callout-titled">
<div class="callout-header d-flex align-content-center">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-title-container flex-fill">
Дескриптивна и инферентна статистика
</div>
</div>
<div class="callout-body-container callout-body">
<p>Дескриптивна (описателна) статистика представлява анализ и описание на статистическите явления <strong>в извадка</strong>. Инферентна статистика е процесът на генерализация (обобщение) на получените резултати в <strong>генералната съвкупност</strong></p>
</div>
</div>
<section id="статистически-променливи" class="level2 page-columns page-full">
<h2 class="anchored" data-anchor-id="статистически-променливи">Статистически променливи</h2>
<p>Статистическите данни се “вземат” чрез измерване на определена характеристика върху група от обекти. Тъй като измерванията могат да приемат различни числови или нечислови стойности, те се наричат още <strong>променливи</strong>. За една група студенти от втори курс например, може да се установи, че се различават по пол, възраст, успех, отношение към определен проблем и редица други <strong>характеристики</strong>. Следователно изброените са наблюдавани <strong>променливи</strong>. От друга страна, ако характеристиката е една и съща за всеки член на групата, тя се нарича <strong>константа</strong>.</p>
<div class="column-page-right">
<div class="callout callout-style-default callout-warning callout-titled">
<div class="callout-header d-flex align-content-center" data-bs-toggle="collapse" data-bs-target=".callout-2-contents" aria-controls="callout-2" aria-expanded="true" aria-label="Toggle callout">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-title-container flex-fill">
Статистическият признак
</div>
<div class="callout-btn-toggle d-inline-block border-0 py-1 ps-1 pe-0 float-end"><i class="callout-toggle"></i></div>
</div>
<div id="callout-2" class="callout-2-contents callout-collapse collapse show">
<div class="callout-body-container callout-body">
<p>Представлява отличителна черта, белег на една или повече единици - обекти на статистически изследвания.</p>
</div>
</div>
</div>
</div>
<p>Статистическите признаци се различават по вид, което налага различен подход при статистическото им изучаване. Основното им разделяне е на <strong>вариационни</strong> и <strong>категорийни</strong>. Вариационните, наричани още <strong>количествени</strong>, са тези, които се изразяват с <strong>числа</strong>. Те могат да бъдат <strong>прекъснати (дискретни)</strong> и <strong>непрекъснати (континюитетни)</strong>. Прекъснатите могат да приемат отделни, изолирани една от друга числови стойности. Такива са броят на членовете на отделно домакинство, броят боледувания за една година, брой живородени деца и др. <a href="#fn2" class="footnote-ref" id="fnref2" role="doc-noteref"><sup>2</sup></a>. Непрекъснати са признаците, които могат да получават всякакви характеристики в даден числов интервал. Такива са: теглото, температурата, кръвното налягане. Посочените характеристики могат да бъдат измервани с изключителна точност след десетичната запетая. Категорийните признаци, наричани още атрибутивни или качествени са тези, чиито характеристики нямат числов израз. За тях се използват “етикети” или описателно наименование. Такива са например пол, семейно положение, кръвна група, вид заболяване и др.</p>
<div style="page-break-after: always;"></div>
<div class="column-page-right">
<div class="callout callout-style-default callout-warning callout-titled">
<div class="callout-header d-flex align-content-center" data-bs-toggle="collapse" data-bs-target=".callout-3-contents" aria-controls="callout-3" aria-expanded="true" aria-label="Toggle callout">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-title-container flex-fill">
Признаците биват два основни типа: <em>количествени и качествени</em>.
</div>
<div class="callout-btn-toggle d-inline-block border-0 py-1 ps-1 pe-0 float-end"><i class="callout-toggle"></i></div>
</div>
<div id="callout-3" class="callout-3-contents callout-collapse collapse show">
<div class="callout-body-container callout-body">
<p><strong>Количествени</strong> са тези променливи, които могат да бъдат изразени числено, а <strong>качествени</strong> са тези, които нямат числено значение.</p>
</div>
</div>
</div>
</div>
</section>
<section id="скали-за-измерване" class="level2">
<h2 class="anchored" data-anchor-id="скали-за-измерване">Скали за измерване</h2>
<p>Скалата, по която се измерва една статистическа променлива, е фактор от голямо значение при определянето на подходящи методи за анализ. Разделянето на скалите за измерване се извършва в съответствие със степента на точност, която използват <a href="#fn3" class="footnote-ref" id="fnref3" role="doc-noteref"><sup>3</sup></a>. Качествените променливи се измерват на <strong>номинална, рангова и ординална</strong> скала, а количествените - в <strong>интервална и/или пропорционална</strong> скала (скала на отношенията). Първите две скали се наричат неметрични и се определят като “слаби, неточни скали” а вторите две — метрични или “силни, точни скали”. Описание на скалите с примери от медицинската статистика са представени в <a href="#tbl-variables" class="quarto-xref">Таблица&nbsp;1</a></p>
<div id="tbl-variables" class="quarto-float quarto-figure quarto-figure-center anchored" data-tbl-colwidths="[30,35,35]">
<figure class="quarto-float quarto-float-tbl figure">
<figcaption class="quarto-float-caption-top quarto-float-caption quarto-float-tbl" id="tbl-variables-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
Таблица&nbsp;1: Видове признаци и скали на измерване
</figcaption>
<div aria-describedby="tbl-variables-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
<table class="caption-top table">
<colgroup>
<col style="width: 30%">
<col style="width: 35%">
<col style="width: 35%">
</colgroup>
<thead>
<tr class="header">
<th>Скала</th>
<th>Характеристика</th>
<th>Пример</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td>Номинална</td>
<td>Категории, “наименования, етикети”.</td>
<td>Диагноза, кръвна група</td>
</tr>
<tr class="even">
<td><em>Дихотомна</em></td>
<td><em>Вид номинална скала за признаци само две възможни стойности</em>.</td>
<td><em>пол</em></td>
</tr>
<tr class="odd">
<td>Ординална</td>
<td>Качествени променливи, които имат логически (нарастващ или намаляващ) ред. Не е възможно изчисление на пропорция или разлика</td>
<td>Степен на тежест на сърдечна недостатъчност (лека, умерена, тежка), стадии на онкологично заболяване (I-ви, II-ри ..)</td>
</tr>
<tr class="even">
<td><em>Рангова</em></td>
<td><em>Вид ординална скала при която единиците се записват с рангове (поредни места) от 1 до п.</em></td>
<td><em>Оценки “слаб 2”, “среден 3” и т.н.</em></td>
</tr>
<tr class="odd">
<td></td>
<td></td>
<td></td>
</tr>
<tr class="even">
<td>Интервална</td>
<td>Количествени променливи. Стойността “0” не означава липса на признака, тя е допустима наред с други позитивни и отрицателни стойности. Не позволява отношения</td>
<td>Температура ( NB: Ако днес е 10 градуса по-топло от вчера, няма как да изчислим “колко процента по-топло е”)</td>
</tr>
<tr class="odd">
<td>Пропорционална</td>
<td>Количествени променливи. Стойността “0” означава липса на признака. Позволява съотношения</td>
<td>Тегло (можем да го измерим с голяма точност след десетичната запетая).</td>
</tr>
</tbody>
</table>
</div>
</figure>
</div>
</section>
</section>
<section id="дескриптивен-статистически-анализ" class="level1 page-columns page-full">
<h1>Дескриптивен статистически анализ</h1>
<p>Статистическият анализ обхваща проучване посредством подходящи методи на <strong>обобщаващи числови характеристики</strong> и смисловото им интерпретиране. Тези характеристики се разделят на два вида - описващи <strong>централната тенденция</strong> и <strong>разсейването</strong> в изследваната извадка <a href="#fn4" class="footnote-ref" id="fnref4" role="doc-noteref"><sup>4</sup></a>. Централната тенденция при променливите, които се измерват на <strong>пропорционална</strong> или <strong>интервална</strong> се описва посредством <strong>средната аритметична</strong> и <strong>медианата</strong>. Разсейването при тези променливи се онагледява чрез стойността на <strong>стандартното отклонение</strong> или <strong>интерквартилния размах</strong>. За променливите измервани на <strong>номинална</strong> и <strong>ординална</strong> скала се използва единствено индикаторът относителен дял.</p>
<section id="показатели-за-централна-тенденция" class="level2 page-columns page-full">
<h2 class="anchored" data-anchor-id="показатели-за-централна-тенденция">Показатели за централна тенденция</h2>
<section id="средна-аритметична" class="level3 page-columns page-full">
<h3 class="anchored" data-anchor-id="средна-аритметична">Средна аритметична</h3>
<p>Средната аритметична се изчислява в зависимост от вида на представяне на количествените данни. Те могат да бъдат изброени негрупирани числа или таблично подредени агрегирани и групирани стойности. От своя страна групировката може да бъде извършена във <strong>вариационен</strong> или <strong>интервален</strong> ред.</p>
<section id="негрупирани-данни" class="level4 page-columns page-full">
<h4 class="anchored" data-anchor-id="негрупирани-данни">Негрупирани данни</h4>
<p>При изчисление на средната аритметична за негрупирани данни се използва формулата:</p>
<p><span class="math display">\[\bar{x} = \frac{\sum x_{}}{n}\]</span></p>
<p>Където:</p>
<ul>
<li><span class="math inline">\(\bar{x}\)</span> е символът за средна аритметична;</li>
<li><span class="math inline">\(\sum x_{}\)</span> е сборът на числовите стойности на наблюдаваната променлива;</li>
<li><span class="math inline">\({n}\)</span> е броят на наблюденията.</li>
</ul>
<p>Нека онагледим това с пример. По-долу са представени стойностите на променливата “сърдечен пулс” за 10 студента от втори курс.</p>
<div class="cell">
<div class="cell-output cell-output-stdout">
<pre><code> [1] 90 80 89 72 73 74 78 86 84 82</code></pre>
</div>
</div>
<p>Графично е представено тяхното <strong>разпределение</strong> на фигура <a href="#fig-pulse" class="quarto-xref">Фигура&nbsp;2</a>. В случая, средната аритметична представлява “средата” на това разпределение (най-издадената му част). За да я изчислим разделяме сбора от стойностите на пулса за всеки един от студентите върху техния брой. Така получаваме:</p>
<p><span class="math display">\[\bar{x} = \frac{90+80+89+72+73+74+78+86+84+82}{10}\]</span> <span class="math display">\[\bar{x} = \frac{808}{10} = 80.8\]</span></p>
<div class="cell page-columns page-full" data-cap-location="margin">
<div class="cell-output-display page-columns page-full">
<div id="fig-pulse" class="quarto-float quarto-figure quarto-figure-center anchored page-columns page-full" data-cap-location="margin">
<figure class="quarto-float quarto-float-fig figure page-columns page-full">
<div aria-describedby="fig-pulse-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
<img src="teaching-posts-04_files/figure-html/fig-pulse-1.png" class="img-fluid figure-img" width="672">
</div>
<figcaption class="quarto-float-caption-margin quarto-float-caption quarto-float-fig margin-caption" id="fig-pulse-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
Фигура&nbsp;2: Разпределение на пулса - по хоризонтала са представени наблюдавани стойности, а по вертикала колко често са наблюдавани те в извадката. С черна пунктирана линия е представена средната аритметична. Представеното разпределение се нарича нормално - има камбановидна, симетрична форма
</figcaption>
</figure>
</div>
</div>
</div>
</section>
<section id="групирани-данни" class="level4 page-columns page-full">
<h4 class="anchored" data-anchor-id="групирани-данни">Групирани данни</h4>
<section id="интервален-ред" class="level5 page-columns page-full">
<h5 class="anchored" data-anchor-id="интервален-ред">Интервален ред</h5>
<p>Когато разполагаме с по-голям обем данни, удобно е тяхното представяне в групирана форма. При <strong>интервалния ред</strong> тази групировка се извършва чрез “разкъсване” на стойностите на изследваната променлива в равномерни и неприпокриващи се стъпки - интервали. Всеки от тях се определя от долна и горна лимитираща стойност (граница). При формирането на интервалните групи се преброяват само участниците, чиято наблюдавана стойност е в границите на интервала. С други думи, при тази групировка “губим” статистическа точност, защото не знаем индивидуалните стойностите на участниците, а само към коя група принадлежат. Пример за интервална групировка е представен в <a href="#tbl-interval" class="quarto-xref">Таблица&nbsp;2</a> .</p>

<div class="no-row-height column-margin column-container"><div class="">
<div id="tbl-interval" class="quarto-float quarto-figure quarto-figure-center anchored">
<figure class="quarto-float quarto-float-tbl figure">
<figcaption class="quarto-float-caption-top quarto-float-caption quarto-float-tbl" id="tbl-interval-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
Таблица&nbsp;2: Пример за интервален ред при измерването на пулс сред 45 студенти
</figcaption>
<div aria-describedby="tbl-interval-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
<table class="caption-top table">
<thead>
<tr class="header">
<th style="text-align: center;">пулс</th>
<th style="text-align: center;">брой студенти</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td style="text-align: center;">48 - 52</td>
<td style="text-align: center;">4</td>
</tr>
<tr class="even">
<td style="text-align: center;">53 - 57</td>
<td style="text-align: center;">5</td>
</tr>
<tr class="odd">
<td style="text-align: center;">58 - 62</td>
<td style="text-align: center;">8</td>
</tr>
<tr class="even">
<td style="text-align: center;">63 - 67</td>
<td style="text-align: center;">11</td>
</tr>
<tr class="odd">
<td style="text-align: center;">68 - 72</td>
<td style="text-align: center;">6</td>
</tr>
<tr class="even">
<td style="text-align: center;">73 - 77</td>
<td style="text-align: center;">6</td>
</tr>
<tr class="odd">
<td style="text-align: center;">78 - 82</td>
<td style="text-align: center;">5</td>
</tr>
</tbody>
</table>
</div>
</figure>
</div>
</div></div><p>За да изчислим средната стойност за променливата пулс в посочения пример, използваме формулата:</p>
<p><span class="math display">\[\bar{x} = \frac{\sum x_{u}\cdot{f}}{\sum_f }\]</span></p>
<p>Където:</p>
<ul>
<li><span class="math inline">\(\bar{x}\)</span> е символът за средна аритметична;</li>
<li><span class="math inline">\(x_{u}\)</span> e средата на всеки от интервалите. Тя се изчислява като половината на сумата между горната и долната лимитираща стойност. Например, за интервала 48 - 52, средата е 50;</li>
<li><span class="math inline">\(f\)</span> е броят на наблюденията за всеки един интервал;</li>
<li><span class="math inline">\(x_{u}\cdot{f}\)</span> е произведението между средата на интервала и броя на наблюденията в него;</li>
<li><span class="math inline">\(\sum{x_{u}\cdot{f}}\)</span> е сумата от всички произведения;</li>
<li><span class="math inline">\(\sum_f\)</span> е сумата от всички наблюдавани участници.</li>
</ul>
<p>Нека представим нагледно примера в <a href="#tbl-interval" class="quarto-xref">Таблица&nbsp;2</a> . Първата стъпка е определянето на средата на интервалите. Това е извършено в <a href="#tbl-intervalstep1" class="quarto-xref">Таблица&nbsp;3</a> .</p>
<div id="tbl-intervalstep1" class="quarto-float quarto-figure quarto-figure-center anchored">
<figure class="quarto-float quarto-float-tbl figure">
<figcaption class="quarto-float-caption-top quarto-float-caption quarto-float-tbl" id="tbl-intervalstep1-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
Таблица&nbsp;3: Стъпка 1 - Определяне на средата на всеки интервал
</figcaption>
<div aria-describedby="tbl-intervalstep1-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
<table class="caption-top table">
<thead>
<tr class="header">
<th style="text-align: center;">пулс</th>
<th style="text-align: center;">среда на интервала</th>
<th style="text-align: center;">брой студенти</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td style="text-align: center;">48 - 52</td>
<td style="text-align: center;">50</td>
<td style="text-align: center;">4</td>
</tr>
<tr class="even">
<td style="text-align: center;">53 - 57</td>
<td style="text-align: center;">55</td>
<td style="text-align: center;">5</td>
</tr>
<tr class="odd">
<td style="text-align: center;">58 - 62</td>
<td style="text-align: center;">60</td>
<td style="text-align: center;">8</td>
</tr>
<tr class="even">
<td style="text-align: center;">63 - 67</td>
<td style="text-align: center;">65</td>
<td style="text-align: center;">11</td>
</tr>
<tr class="odd">
<td style="text-align: center;">68 - 72</td>
<td style="text-align: center;">70</td>
<td style="text-align: center;">6</td>
</tr>
<tr class="even">
<td style="text-align: center;">73 - 77</td>
<td style="text-align: center;">75</td>
<td style="text-align: center;">6</td>
</tr>
<tr class="odd">
<td style="text-align: center;">78 - 82</td>
<td style="text-align: center;">80</td>
<td style="text-align: center;">5</td>
</tr>
</tbody>
</table>
</div>
</figure>
</div>
<p>След това изчисляваме произведенията между броя наблюдавани студенти и средата на интервала. Това е направено за всеки един интервал и представено в <a href="#tbl-intervalstep2" class="quarto-xref">Таблица&nbsp;4</a> .</p>
<div id="tbl-intervalstep2" class="quarto-float quarto-figure quarto-figure-center anchored">
<figure class="quarto-float quarto-float-tbl figure">
<figcaption class="quarto-float-caption-top quarto-float-caption quarto-float-tbl" id="tbl-intervalstep2-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
Таблица&nbsp;4: Стъпка 2 - Умножение на средата на интервала по броя на наблюдаваните студенти в него
</figcaption>
<div aria-describedby="tbl-intervalstep2-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
<table class="caption-top table">
<colgroup>
<col style="width: 12%">
<col style="width: 27%">
<col style="width: 20%">
<col style="width: 40%">
</colgroup>
<thead>
<tr class="header">
<th style="text-align: center;">Пулс</th>
<th style="text-align: center;">Среда на интервала</th>
<th style="text-align: center;">Брои студенти</th>
<th style="text-align: center;">Произведение <span class="math inline">\({x_u}\)</span> х <span class="math inline">\({f}\)</span></th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td style="text-align: center;">48 - 52</td>
<td style="text-align: center;">50</td>
<td style="text-align: center;">4</td>
<td style="text-align: center;">200</td>
</tr>
<tr class="even">
<td style="text-align: center;">53 - 57</td>
<td style="text-align: center;">55</td>
<td style="text-align: center;">5</td>
<td style="text-align: center;">275</td>
</tr>
<tr class="odd">
<td style="text-align: center;">58 - 62</td>
<td style="text-align: center;">60</td>
<td style="text-align: center;">8</td>
<td style="text-align: center;">480</td>
</tr>
<tr class="even">
<td style="text-align: center;">63 - 67</td>
<td style="text-align: center;">65</td>
<td style="text-align: center;">11</td>
<td style="text-align: center;">715</td>
</tr>
<tr class="odd">
<td style="text-align: center;">68 - 72</td>
<td style="text-align: center;">70</td>
<td style="text-align: center;">6</td>
<td style="text-align: center;">420</td>
</tr>
<tr class="even">
<td style="text-align: center;">73 - 77</td>
<td style="text-align: center;">75</td>
<td style="text-align: center;">6</td>
<td style="text-align: center;">450</td>
</tr>
<tr class="odd">
<td style="text-align: center;">78 - 82</td>
<td style="text-align: center;">80</td>
<td style="text-align: center;">5</td>
<td style="text-align: center;">400</td>
</tr>
</tbody>
</table>
</div>
</figure>
</div>
<p>Накрая сумираме всички получени произведения и ги разделяме на броя студенти</p>
<p><span class="math display">\[\bar{x} = \frac {200+275+480+715+420+450+400} {45} = \frac {2940} {45} = 65.33 \]</span></p>
<div style="page-break-after: always;"></div>
</section>
<section id="степенен-ред" class="level5 page-columns page-full">
<h5 class="anchored" data-anchor-id="степенен-ред">Степенен ред</h5>
<p>Вторият вариант за групиране на статистически данни е <strong>степенния ред</strong>. При него записваме всяка стойност на интересуващата ни променлива, а срещу нея нанасяме броя на наблюдаваните лица, при които сме я наблюдавали. Пример за степенен ред е представен в <a href="#tbl-frequency" class="quarto-xref">Таблица&nbsp;5</a> .</p>

<div class="no-row-height column-margin column-container"><div class="">
<div id="tbl-frequency" class="quarto-float quarto-figure quarto-figure-center anchored">
<figure class="quarto-float quarto-float-tbl figure">
<figcaption class="quarto-float-caption-top quarto-float-caption quarto-float-tbl" id="tbl-frequency-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
Таблица&nbsp;5: Пример за степенен ред при измерването на пулс сред 17 студенти
</figcaption>
<div aria-describedby="tbl-frequency-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
<table class="caption-top table">
<thead>
<tr class="header">
<th style="text-align: center;">Стойност на пулса</th>
<th style="text-align: center;">Брой студенти</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td style="text-align: center;">59</td>
<td style="text-align: center;">1</td>
</tr>
<tr class="even">
<td style="text-align: center;">60</td>
<td style="text-align: center;">0</td>
</tr>
<tr class="odd">
<td style="text-align: center;">61</td>
<td style="text-align: center;">2</td>
</tr>
<tr class="even">
<td style="text-align: center;">62</td>
<td style="text-align: center;">4</td>
</tr>
<tr class="odd">
<td style="text-align: center;">63</td>
<td style="text-align: center;">0</td>
</tr>
<tr class="even">
<td style="text-align: center;">64</td>
<td style="text-align: center;">3</td>
</tr>
<tr class="odd">
<td style="text-align: center;">65</td>
<td style="text-align: center;">2</td>
</tr>
<tr class="even">
<td style="text-align: center;">66</td>
<td style="text-align: center;">1</td>
</tr>
<tr class="odd">
<td style="text-align: center;">67</td>
<td style="text-align: center;">1</td>
</tr>
<tr class="even">
<td style="text-align: center;">68</td>
<td style="text-align: center;">3</td>
</tr>
</tbody>
</table>
</div>
</figure>
</div>
</div></div><p>За изчисляването на средната аритметична, при данни в степенен ред, използваме формулата:</p>
<p><span class="math display">\[\bar{x} = \frac{\sum x_{}\cdot{f}}{\sum_f }\]</span></p>
<p>Където:</p>
<ul>
<li><span class="math inline">\(\bar{x}\)</span> е символът за средна аритметична;</li>
<li><span class="math inline">\(x_{}\)</span> e стойността на наблюдаваната променлива;</li>
<li><span class="math inline">\(f\)</span> е броят на наблюденията за всяка една стойност;</li>
<li><span class="math inline">\(x_{}\cdot{f}\)</span> е произведението между всяка от стойностите на променливата и броя на наблюденията за нея;</li>
<li><span class="math inline">\(\sum{x_{}\cdot{f}}\)</span> е сумата от всички произведения;</li>
<li><span class="math inline">\(\sum{f}\)</span> е сумата от всички наблюдавани участници.</li>
</ul>
<p>Нека представим нагледно примера в <a href="#tbl-frequency" class="quarto-xref">Таблица&nbsp;5</a> . Първата стъпка, за изчисление на средната аритметична, е определянето на произведенията между всяка една стойност на променливата и съответния брой на наблюденията. Това е направено в <a href="#tbl-frequencystep" class="quarto-xref">Таблица&nbsp;6</a> .</p>
<div id="tbl-frequencystep" class="quarto-float quarto-figure quarto-figure-center anchored">
<figure class="quarto-float quarto-float-tbl figure">
<figcaption class="quarto-float-caption-top quarto-float-caption quarto-float-tbl" id="tbl-frequencystep-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
Таблица&nbsp;6: Пример за степенен ред при измерването на пулс сред 17 студенти
</figcaption>
<div aria-describedby="tbl-frequencystep-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
<table class="caption-top table">
<thead>
<tr class="header">
<th style="text-align: center;">Стойност на пулса</th>
<th style="text-align: center;">Брой студенти</th>
<th style="text-align: center;">Произведение <span class="math inline">\({x}\)</span> х <span class="math inline">\({f}\)</span></th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td style="text-align: center;">59</td>
<td style="text-align: center;">1</td>
<td style="text-align: center;">59</td>
</tr>
<tr class="even">
<td style="text-align: center;">60</td>
<td style="text-align: center;">0</td>
<td style="text-align: center;">0</td>
</tr>
<tr class="odd">
<td style="text-align: center;">61</td>
<td style="text-align: center;">2</td>
<td style="text-align: center;">122</td>
</tr>
<tr class="even">
<td style="text-align: center;">62</td>
<td style="text-align: center;">4</td>
<td style="text-align: center;">248</td>
</tr>
<tr class="odd">
<td style="text-align: center;">63</td>
<td style="text-align: center;">0</td>
<td style="text-align: center;">0</td>
</tr>
<tr class="even">
<td style="text-align: center;">64</td>
<td style="text-align: center;">3</td>
<td style="text-align: center;">192</td>
</tr>
<tr class="odd">
<td style="text-align: center;">65</td>
<td style="text-align: center;">2</td>
<td style="text-align: center;">130</td>
</tr>
<tr class="even">
<td style="text-align: center;">66</td>
<td style="text-align: center;">1</td>
<td style="text-align: center;">66</td>
</tr>
<tr class="odd">
<td style="text-align: center;">67</td>
<td style="text-align: center;">1</td>
<td style="text-align: center;">67</td>
</tr>
<tr class="even">
<td style="text-align: center;">68</td>
<td style="text-align: center;">3</td>
<td style="text-align: center;">204</td>
</tr>
</tbody>
</table>
</div>
</figure>
</div>
<p>След това сумираме всички получени произведения и ги разделяме на броя студенти <a href="#fn5" class="footnote-ref" id="fnref5" role="doc-noteref"><sup>5</sup></a> :</p>
<p><span class="math display">\[\bar{x} = \frac {59+0+122+248+0+192+130+66+67+204} {17} = \frac {1088} {17} = 64 \]</span></p>
</section>
</section>
</section>
</section>
<section id="други-показатели-за-централна-тенденция" class="level2">
<h2 class="anchored" data-anchor-id="други-показатели-за-централна-тенденция">Други показатели за централна тенденция</h2>
<p>Освен средната аритметична съществуват и други показатели, които представят централната тенденция. Това са:</p>
<ul>
<li><strong>Медианата</strong> - Медианата е тази стойност, която разделя възходящо подреден статистически ред на две равни части. С други думи 50% от наблюдаваните стойности са или по-големи или по-малки на медианата <a href="#fn6" class="footnote-ref" id="fnref6" role="doc-noteref"><sup>6</sup></a> <a href="#fn7" class="footnote-ref" id="fnref7" role="doc-noteref"><sup>7</sup></a>;</li>
</ul>
<ul>
<li><strong>Модата</strong> <span class="math inline">\({M_0}\)</span> е най-често срещаната стойност в статистическия ред и се намира чрез броене <a href="#fn8" class="footnote-ref" id="fnref8" role="doc-noteref"><sup>8</sup></a>.</li>
</ul>
</section>
<section id="относителен-дял" class="level2">
<h2 class="anchored" data-anchor-id="относителен-дял">Относителен дял</h2>
<p>Относителният дял представлява централна тенденция за променливите измервани на ординална и номинална скала. Той се изчислява чрез формулата:</p>
<p><span class="math display">\[\hat{p}=\frac{m}{n}{100}\]</span></p>
<p>Където:</p>
<ul>
<li><span class="math inline">\(\hat{p}\)</span> е символът за относителен дял;</li>
<li><span class="math inline">\(m\)</span> е броят на наблюденията, за които искаме да установим централната тенденция;</li>
<li><span class="math inline">\(n\)</span> е броят на всички наблюдения в изследваната група.</li>
</ul>
<p>Ако искаме да разберем какъв е относителния дял на 4 момичета в група от 10 студенти:</p>
<p><span class="math display">\[\hat{p}=\frac{4}{10}{100} = 40\%\]</span></p>
</section>
</section>
<section id="показатели-за-разсейване" class="level1 page-columns page-full">
<h1>Показатели за разсейване</h1>
<p>Показателите за разсейване са мерки за разпръснатостта на стойностите спрямо централната тенденция. В настоящия курс ще разгледаме показателите за разсейтване само за променливи измервани на <strong>пропорционална</strong> или <strong>интервална</strong> скала.</p>
<section id="размах" class="level2">
<h2 class="anchored" data-anchor-id="размах">Размах</h2>
<p>Размахът представлява разликата между <strong>максималната и минималната</strong> стойност в един статистически ред <a href="#fn9" class="footnote-ref" id="fnref9" role="doc-noteref"><sup>9</sup></a>. Ако използваме първия пример, за стойността на пулса при 10 студенти - 90; 80; 89; 72; 73; 74; 78; 86; 84; 82, размахът е</p>
<p><span class="math display">\[{R} = 90 - 72 = 18\]</span></p>
</section>
<section id="стандартно-отклонение" class="level2 page-columns page-full">
<h2 class="anchored" data-anchor-id="стандартно-отклонение">Стандартно отклонение</h2>
<section id="стандартно-отклонение-при-негрупирани-данни" class="level3 page-columns page-full">
<h3 class="anchored" data-anchor-id="стандартно-отклонение-при-негрупирани-данни">Стандартно отклонение при негрупирани данни</h3>
<p>Стандартното отклонение е показател за <strong>средното ниво на разсейване</strong> спрямо средната аритметична. Формулата за изчисление на стандартното отклонение е <span class="math display">\[{SD} = \sqrt{\frac{\sum (x_{} - \bar{x})^{2}}{n}}\]</span></p>
<p>Където: - <span class="math inline">\({SD}\)</span> е символът за стандартно отклонение; - <span class="math inline">\(x_{}\)</span> е стойността на всяко едно наблюдение; - <span class="math inline">\(\bar{x}\)</span> е средната аритметична; - <span class="math inline">\(n\)</span> е броят на наблюденията в изследваната група; - <span class="math inline">\(x_{} - \bar{x}\)</span> е отклонението на всяко едно наблюдение от средната аритметична; - <span class="math inline">\(\sum (x_{} - \bar{x})^{2}\)</span> е сумата от квадратите на всички отклонения.</p>
<p>Нека разгледаме примера с пулса на 10-тимата студенти от втори курс. Както определихме по-рано, средната стойност на пулса за тях е 80.8. Въпреки това няма нито един студент с точно тази стойност. Всеки студент се отклонява с няколко удара под или над тази средна. Това отклонение представлява разсейването (<strong>девиацията</strong>) и е първата стъпка при изчислението на стандартното отклонение. Разликите между стойността на средната аритметична и стойността на пулса за всеки един студент са представени в таблица <a href="#tbl-dev" class="quarto-xref">Таблица&nbsp;7</a></p>
<div class="cell page-columns page-full" data-cap-location="margin">
<div id="tbl-dev" class="cell quarto-float quarto-figure quarto-figure-center anchored page-columns page-full" data-cap-location="margin">
<figure class="quarto-float quarto-float-tbl figure page-columns page-full">
<div aria-describedby="tbl-dev-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
<div class="cell-output-display">
<div id="qmcvtypwdt" style="padding-left:0px;padding-right:0px;padding-top:10px;padding-bottom:10px;overflow-x:auto;overflow-y:auto;width:auto;height:auto;">
<style>#qmcvtypwdt table {
  font-family: system-ui, 'Segoe UI', Roboto, Helvetica, Arial, sans-serif, 'Apple Color Emoji', 'Segoe UI Emoji', 'Segoe UI Symbol', 'Noto Color Emoji';
  -webkit-font-smoothing: antialiased;
  -moz-osx-font-smoothing: grayscale;
}

#qmcvtypwdt thead, #qmcvtypwdt tbody, #qmcvtypwdt tfoot, #qmcvtypwdt tr, #qmcvtypwdt td, #qmcvtypwdt th {
  border-style: none;
}

#qmcvtypwdt p {
  margin: 0;
  padding: 0;
}

#qmcvtypwdt .gt_table {
  display: table;
  border-collapse: collapse;
  line-height: normal;
  margin-left: auto;
  margin-right: auto;
  color: #333333;
  font-size: 16px;
  font-weight: normal;
  font-style: normal;
  background-color: #FFFFFF;
  width: auto;
  border-top-style: solid;
  border-top-width: 2px;
  border-top-color: #A8A8A8;
  border-right-style: none;
  border-right-width: 2px;
  border-right-color: #D3D3D3;
  border-bottom-style: solid;
  border-bottom-width: 2px;
  border-bottom-color: #A8A8A8;
  border-left-style: none;
  border-left-width: 2px;
  border-left-color: #D3D3D3;
}

#qmcvtypwdt .gt_caption {
  padding-top: 4px;
  padding-bottom: 4px;
}

#qmcvtypwdt .gt_title {
  color: #333333;
  font-size: 125%;
  font-weight: initial;
  padding-top: 4px;
  padding-bottom: 4px;
  padding-left: 5px;
  padding-right: 5px;
  border-bottom-color: #FFFFFF;
  border-bottom-width: 0;
}

#qmcvtypwdt .gt_subtitle {
  color: #333333;
  font-size: 85%;
  font-weight: initial;
  padding-top: 3px;
  padding-bottom: 5px;
  padding-left: 5px;
  padding-right: 5px;
  border-top-color: #FFFFFF;
  border-top-width: 0;
}

#qmcvtypwdt .gt_heading {
  background-color: #FFFFFF;
  text-align: center;
  border-bottom-color: #FFFFFF;
  border-left-style: none;
  border-left-width: 1px;
  border-left-color: #D3D3D3;
  border-right-style: none;
  border-right-width: 1px;
  border-right-color: #D3D3D3;
}

#qmcvtypwdt .gt_bottom_border {
  border-bottom-style: solid;
  border-bottom-width: 2px;
  border-bottom-color: #D3D3D3;
}

#qmcvtypwdt .gt_col_headings {
  border-top-style: solid;
  border-top-width: 2px;
  border-top-color: #D3D3D3;
  border-bottom-style: solid;
  border-bottom-width: 2px;
  border-bottom-color: #D3D3D3;
  border-left-style: none;
  border-left-width: 1px;
  border-left-color: #D3D3D3;
  border-right-style: none;
  border-right-width: 1px;
  border-right-color: #D3D3D3;
}

#qmcvtypwdt .gt_col_heading {
  color: #333333;
  background-color: #FFFFFF;
  font-size: 100%;
  font-weight: normal;
  text-transform: inherit;
  border-left-style: none;
  border-left-width: 1px;
  border-left-color: #D3D3D3;
  border-right-style: none;
  border-right-width: 1px;
  border-right-color: #D3D3D3;
  vertical-align: bottom;
  padding-top: 5px;
  padding-bottom: 6px;
  padding-left: 5px;
  padding-right: 5px;
  overflow-x: hidden;
}

#qmcvtypwdt .gt_column_spanner_outer {
  color: #333333;
  background-color: #FFFFFF;
  font-size: 100%;
  font-weight: normal;
  text-transform: inherit;
  padding-top: 0;
  padding-bottom: 0;
  padding-left: 4px;
  padding-right: 4px;
}

#qmcvtypwdt .gt_column_spanner_outer:first-child {
  padding-left: 0;
}

#qmcvtypwdt .gt_column_spanner_outer:last-child {
  padding-right: 0;
}

#qmcvtypwdt .gt_column_spanner {
  border-bottom-style: solid;
  border-bottom-width: 2px;
  border-bottom-color: #D3D3D3;
  vertical-align: bottom;
  padding-top: 5px;
  padding-bottom: 5px;
  overflow-x: hidden;
  display: inline-block;
  width: 100%;
}

#qmcvtypwdt .gt_spanner_row {
  border-bottom-style: hidden;
}

#qmcvtypwdt .gt_group_heading {
  padding-top: 8px;
  padding-bottom: 8px;
  padding-left: 5px;
  padding-right: 5px;
  color: #333333;
  background-color: #FFFFFF;
  font-size: 100%;
  font-weight: initial;
  text-transform: inherit;
  border-top-style: solid;
  border-top-width: 2px;
  border-top-color: #D3D3D3;
  border-bottom-style: solid;
  border-bottom-width: 2px;
  border-bottom-color: #D3D3D3;
  border-left-style: none;
  border-left-width: 1px;
  border-left-color: #D3D3D3;
  border-right-style: none;
  border-right-width: 1px;
  border-right-color: #D3D3D3;
  vertical-align: middle;
  text-align: left;
}

#qmcvtypwdt .gt_empty_group_heading {
  padding: 0.5px;
  color: #333333;
  background-color: #FFFFFF;
  font-size: 100%;
  font-weight: initial;
  border-top-style: solid;
  border-top-width: 2px;
  border-top-color: #D3D3D3;
  border-bottom-style: solid;
  border-bottom-width: 2px;
  border-bottom-color: #D3D3D3;
  vertical-align: middle;
}

#qmcvtypwdt .gt_from_md > :first-child {
  margin-top: 0;
}

#qmcvtypwdt .gt_from_md > :last-child {
  margin-bottom: 0;
}

#qmcvtypwdt .gt_row {
  padding-top: 8px;
  padding-bottom: 8px;
  padding-left: 5px;
  padding-right: 5px;
  margin: 10px;
  border-top-style: solid;
  border-top-width: 1px;
  border-top-color: #D3D3D3;
  border-left-style: none;
  border-left-width: 1px;
  border-left-color: #D3D3D3;
  border-right-style: none;
  border-right-width: 1px;
  border-right-color: #D3D3D3;
  vertical-align: middle;
  overflow-x: hidden;
}

#qmcvtypwdt .gt_stub {
  color: #333333;
  background-color: #FFFFFF;
  font-size: 100%;
  font-weight: initial;
  text-transform: inherit;
  border-right-style: solid;
  border-right-width: 2px;
  border-right-color: #D3D3D3;
  padding-left: 5px;
  padding-right: 5px;
}

#qmcvtypwdt .gt_stub_row_group {
  color: #333333;
  background-color: #FFFFFF;
  font-size: 100%;
  font-weight: initial;
  text-transform: inherit;
  border-right-style: solid;
  border-right-width: 2px;
  border-right-color: #D3D3D3;
  padding-left: 5px;
  padding-right: 5px;
  vertical-align: top;
}

#qmcvtypwdt .gt_row_group_first td {
  border-top-width: 2px;
}

#qmcvtypwdt .gt_row_group_first th {
  border-top-width: 2px;
}

#qmcvtypwdt .gt_summary_row {
  color: #333333;
  background-color: #FFFFFF;
  text-transform: inherit;
  padding-top: 8px;
  padding-bottom: 8px;
  padding-left: 5px;
  padding-right: 5px;
}

#qmcvtypwdt .gt_first_summary_row {
  border-top-style: solid;
  border-top-color: #D3D3D3;
}

#qmcvtypwdt .gt_first_summary_row.thick {
  border-top-width: 2px;
}

#qmcvtypwdt .gt_last_summary_row {
  padding-top: 8px;
  padding-bottom: 8px;
  padding-left: 5px;
  padding-right: 5px;
  border-bottom-style: solid;
  border-bottom-width: 2px;
  border-bottom-color: #D3D3D3;
}

#qmcvtypwdt .gt_grand_summary_row {
  color: #333333;
  background-color: #FFFFFF;
  text-transform: inherit;
  padding-top: 8px;
  padding-bottom: 8px;
  padding-left: 5px;
  padding-right: 5px;
}

#qmcvtypwdt .gt_first_grand_summary_row {
  padding-top: 8px;
  padding-bottom: 8px;
  padding-left: 5px;
  padding-right: 5px;
  border-top-style: double;
  border-top-width: 6px;
  border-top-color: #D3D3D3;
}

#qmcvtypwdt .gt_last_grand_summary_row_top {
  padding-top: 8px;
  padding-bottom: 8px;
  padding-left: 5px;
  padding-right: 5px;
  border-bottom-style: double;
  border-bottom-width: 6px;
  border-bottom-color: #D3D3D3;
}

#qmcvtypwdt .gt_striped {
  background-color: rgba(128, 128, 128, 0.05);
}

#qmcvtypwdt .gt_table_body {
  border-top-style: solid;
  border-top-width: 2px;
  border-top-color: #D3D3D3;
  border-bottom-style: solid;
  border-bottom-width: 2px;
  border-bottom-color: #D3D3D3;
}

#qmcvtypwdt .gt_footnotes {
  color: #333333;
  background-color: #FFFFFF;
  border-bottom-style: none;
  border-bottom-width: 2px;
  border-bottom-color: #D3D3D3;
  border-left-style: none;
  border-left-width: 2px;
  border-left-color: #D3D3D3;
  border-right-style: none;
  border-right-width: 2px;
  border-right-color: #D3D3D3;
}

#qmcvtypwdt .gt_footnote {
  margin: 0px;
  font-size: 90%;
  padding-top: 4px;
  padding-bottom: 4px;
  padding-left: 5px;
  padding-right: 5px;
}

#qmcvtypwdt .gt_sourcenotes {
  color: #333333;
  background-color: #FFFFFF;
  border-bottom-style: none;
  border-bottom-width: 2px;
  border-bottom-color: #D3D3D3;
  border-left-style: none;
  border-left-width: 2px;
  border-left-color: #D3D3D3;
  border-right-style: none;
  border-right-width: 2px;
  border-right-color: #D3D3D3;
}

#qmcvtypwdt .gt_sourcenote {
  font-size: 90%;
  padding-top: 4px;
  padding-bottom: 4px;
  padding-left: 5px;
  padding-right: 5px;
}

#qmcvtypwdt .gt_left {
  text-align: left;
}

#qmcvtypwdt .gt_center {
  text-align: center;
}

#qmcvtypwdt .gt_right {
  text-align: right;
  font-variant-numeric: tabular-nums;
}

#qmcvtypwdt .gt_font_normal {
  font-weight: normal;
}

#qmcvtypwdt .gt_font_bold {
  font-weight: bold;
}

#qmcvtypwdt .gt_font_italic {
  font-style: italic;
}

#qmcvtypwdt .gt_super {
  font-size: 65%;
}

#qmcvtypwdt .gt_footnote_marks {
  font-size: 75%;
  vertical-align: 0.4em;
  position: initial;
}

#qmcvtypwdt .gt_asterisk {
  font-size: 100%;
  vertical-align: 0;
}

#qmcvtypwdt .gt_indent_1 {
  text-indent: 5px;
}

#qmcvtypwdt .gt_indent_2 {
  text-indent: 10px;
}

#qmcvtypwdt .gt_indent_3 {
  text-indent: 15px;
}

#qmcvtypwdt .gt_indent_4 {
  text-indent: 20px;
}

#qmcvtypwdt .gt_indent_5 {
  text-indent: 25px;
}

#qmcvtypwdt .katex-display {
  display: inline-flex !important;
  margin-bottom: 0.75em !important;
}

#qmcvtypwdt div.Reactable > div.rt-table > div.rt-thead > div.rt-tr.rt-tr-group-header > div.rt-th-group:after {
  height: 0px !important;
}
</style>

<table class="gt_table do-not-create-environment cell caption-top table table-sm table-striped small" data-quarto-postprocess="true" data-quarto-disable-processing="false" data-quarto-bootstrap="false">
<thead>
<tr class="gt_col_headings header">
<th id="aсърд.честота" class="gt_col_heading gt_columns_bottom_border gt_right" data-quarto-table-cell-role="th" scope="col">сърд.честота</th>
<th id="aдевиация" class="gt_col_heading gt_columns_bottom_border gt_right" data-quarto-table-cell-role="th" scope="col">девиация</th>
</tr>
</thead>
<tbody class="gt_table_body">
<tr class="odd">
<td class="gt_row gt_right" headers="сърд.честота">90</td>
<td class="gt_row gt_right" headers="девиация">9.2</td>
</tr>
<tr class="even">
<td class="gt_row gt_right" headers="сърд.честота">80</td>
<td class="gt_row gt_right" headers="девиация">-0.8</td>
</tr>
<tr class="odd">
<td class="gt_row gt_right" headers="сърд.честота">89</td>
<td class="gt_row gt_right" headers="девиация">8.2</td>
</tr>
<tr class="even">
<td class="gt_row gt_right" headers="сърд.честота">72</td>
<td class="gt_row gt_right" headers="девиация">-8.8</td>
</tr>
<tr class="odd">
<td class="gt_row gt_right" headers="сърд.честота">73</td>
<td class="gt_row gt_right" headers="девиация">-7.8</td>
</tr>
<tr class="even">
<td class="gt_row gt_right" headers="сърд.честота">74</td>
<td class="gt_row gt_right" headers="девиация">-6.8</td>
</tr>
<tr class="odd">
<td class="gt_row gt_right" headers="сърд.честота">78</td>
<td class="gt_row gt_right" headers="девиация">-2.8</td>
</tr>
<tr class="even">
<td class="gt_row gt_right" headers="сърд.честота">86</td>
<td class="gt_row gt_right" headers="девиация">5.2</td>
</tr>
<tr class="odd">
<td class="gt_row gt_right" headers="сърд.честота">84</td>
<td class="gt_row gt_right" headers="девиация">3.2</td>
</tr>
<tr class="even">
<td class="gt_row gt_right" headers="сърд.честота">82</td>
<td class="gt_row gt_right" headers="девиация">1.2</td>
</tr>
</tbody>
</table>

</div>
</div>
</div>
<figcaption class="quarto-float-caption-margin quarto-float-caption quarto-float-tbl margin-caption" id="tbl-dev-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
Таблица&nbsp;7: Отклонение на всеки един от изследваните спрямо средната аритметична за групата
</figcaption>
</figure>
</div>
</div>
<p>Ако съберем девиациите на всички участници, че получим “0”. Това няма да ни позволи да изчислим средното отклонение в групата – затова, във втората стъпка повдигаме всяка една от девиациите на втора степен. Изчисленията са представени в <a href="#tbl-sd" class="quarto-xref">Таблица&nbsp;8</a></p>
<div class="cell page-columns page-full" data-cap-location="margin">
<div id="tbl-sd" class="cell quarto-float quarto-figure quarto-figure-center anchored page-columns page-full" data-cap-location="margin">
<figure class="quarto-float quarto-float-tbl figure page-columns page-full">
<div aria-describedby="tbl-sd-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
<div class="cell-output-display">
<div id="hshuvwgiwq" style="padding-left:0px;padding-right:0px;padding-top:10px;padding-bottom:10px;overflow-x:auto;overflow-y:auto;width:auto;height:auto;">
<style>#hshuvwgiwq table {
  font-family: system-ui, 'Segoe UI', Roboto, Helvetica, Arial, sans-serif, 'Apple Color Emoji', 'Segoe UI Emoji', 'Segoe UI Symbol', 'Noto Color Emoji';
  -webkit-font-smoothing: antialiased;
  -moz-osx-font-smoothing: grayscale;
}

#hshuvwgiwq thead, #hshuvwgiwq tbody, #hshuvwgiwq tfoot, #hshuvwgiwq tr, #hshuvwgiwq td, #hshuvwgiwq th {
  border-style: none;
}

#hshuvwgiwq p {
  margin: 0;
  padding: 0;
}

#hshuvwgiwq .gt_table {
  display: table;
  border-collapse: collapse;
  line-height: normal;
  margin-left: auto;
  margin-right: auto;
  color: #333333;
  font-size: 16px;
  font-weight: normal;
  font-style: normal;
  background-color: #FFFFFF;
  width: auto;
  border-top-style: solid;
  border-top-width: 2px;
  border-top-color: #A8A8A8;
  border-right-style: none;
  border-right-width: 2px;
  border-right-color: #D3D3D3;
  border-bottom-style: solid;
  border-bottom-width: 2px;
  border-bottom-color: #A8A8A8;
  border-left-style: none;
  border-left-width: 2px;
  border-left-color: #D3D3D3;
}

#hshuvwgiwq .gt_caption {
  padding-top: 4px;
  padding-bottom: 4px;
}

#hshuvwgiwq .gt_title {
  color: #333333;
  font-size: 125%;
  font-weight: initial;
  padding-top: 4px;
  padding-bottom: 4px;
  padding-left: 5px;
  padding-right: 5px;
  border-bottom-color: #FFFFFF;
  border-bottom-width: 0;
}

#hshuvwgiwq .gt_subtitle {
  color: #333333;
  font-size: 85%;
  font-weight: initial;
  padding-top: 3px;
  padding-bottom: 5px;
  padding-left: 5px;
  padding-right: 5px;
  border-top-color: #FFFFFF;
  border-top-width: 0;
}

#hshuvwgiwq .gt_heading {
  background-color: #FFFFFF;
  text-align: center;
  border-bottom-color: #FFFFFF;
  border-left-style: none;
  border-left-width: 1px;
  border-left-color: #D3D3D3;
  border-right-style: none;
  border-right-width: 1px;
  border-right-color: #D3D3D3;
}

#hshuvwgiwq .gt_bottom_border {
  border-bottom-style: solid;
  border-bottom-width: 2px;
  border-bottom-color: #D3D3D3;
}

#hshuvwgiwq .gt_col_headings {
  border-top-style: solid;
  border-top-width: 2px;
  border-top-color: #D3D3D3;
  border-bottom-style: solid;
  border-bottom-width: 2px;
  border-bottom-color: #D3D3D3;
  border-left-style: none;
  border-left-width: 1px;
  border-left-color: #D3D3D3;
  border-right-style: none;
  border-right-width: 1px;
  border-right-color: #D3D3D3;
}

#hshuvwgiwq .gt_col_heading {
  color: #333333;
  background-color: #FFFFFF;
  font-size: 100%;
  font-weight: normal;
  text-transform: inherit;
  border-left-style: none;
  border-left-width: 1px;
  border-left-color: #D3D3D3;
  border-right-style: none;
  border-right-width: 1px;
  border-right-color: #D3D3D3;
  vertical-align: bottom;
  padding-top: 5px;
  padding-bottom: 6px;
  padding-left: 5px;
  padding-right: 5px;
  overflow-x: hidden;
}

#hshuvwgiwq .gt_column_spanner_outer {
  color: #333333;
  background-color: #FFFFFF;
  font-size: 100%;
  font-weight: normal;
  text-transform: inherit;
  padding-top: 0;
  padding-bottom: 0;
  padding-left: 4px;
  padding-right: 4px;
}

#hshuvwgiwq .gt_column_spanner_outer:first-child {
  padding-left: 0;
}

#hshuvwgiwq .gt_column_spanner_outer:last-child {
  padding-right: 0;
}

#hshuvwgiwq .gt_column_spanner {
  border-bottom-style: solid;
  border-bottom-width: 2px;
  border-bottom-color: #D3D3D3;
  vertical-align: bottom;
  padding-top: 5px;
  padding-bottom: 5px;
  overflow-x: hidden;
  display: inline-block;
  width: 100%;
}

#hshuvwgiwq .gt_spanner_row {
  border-bottom-style: hidden;
}

#hshuvwgiwq .gt_group_heading {
  padding-top: 8px;
  padding-bottom: 8px;
  padding-left: 5px;
  padding-right: 5px;
  color: #333333;
  background-color: #FFFFFF;
  font-size: 100%;
  font-weight: initial;
  text-transform: inherit;
  border-top-style: solid;
  border-top-width: 2px;
  border-top-color: #D3D3D3;
  border-bottom-style: solid;
  border-bottom-width: 2px;
  border-bottom-color: #D3D3D3;
  border-left-style: none;
  border-left-width: 1px;
  border-left-color: #D3D3D3;
  border-right-style: none;
  border-right-width: 1px;
  border-right-color: #D3D3D3;
  vertical-align: middle;
  text-align: left;
}

#hshuvwgiwq .gt_empty_group_heading {
  padding: 0.5px;
  color: #333333;
  background-color: #FFFFFF;
  font-size: 100%;
  font-weight: initial;
  border-top-style: solid;
  border-top-width: 2px;
  border-top-color: #D3D3D3;
  border-bottom-style: solid;
  border-bottom-width: 2px;
  border-bottom-color: #D3D3D3;
  vertical-align: middle;
}

#hshuvwgiwq .gt_from_md > :first-child {
  margin-top: 0;
}

#hshuvwgiwq .gt_from_md > :last-child {
  margin-bottom: 0;
}

#hshuvwgiwq .gt_row {
  padding-top: 8px;
  padding-bottom: 8px;
  padding-left: 5px;
  padding-right: 5px;
  margin: 10px;
  border-top-style: solid;
  border-top-width: 1px;
  border-top-color: #D3D3D3;
  border-left-style: none;
  border-left-width: 1px;
  border-left-color: #D3D3D3;
  border-right-style: none;
  border-right-width: 1px;
  border-right-color: #D3D3D3;
  vertical-align: middle;
  overflow-x: hidden;
}

#hshuvwgiwq .gt_stub {
  color: #333333;
  background-color: #FFFFFF;
  font-size: 100%;
  font-weight: initial;
  text-transform: inherit;
  border-right-style: solid;
  border-right-width: 2px;
  border-right-color: #D3D3D3;
  padding-left: 5px;
  padding-right: 5px;
}

#hshuvwgiwq .gt_stub_row_group {
  color: #333333;
  background-color: #FFFFFF;
  font-size: 100%;
  font-weight: initial;
  text-transform: inherit;
  border-right-style: solid;
  border-right-width: 2px;
  border-right-color: #D3D3D3;
  padding-left: 5px;
  padding-right: 5px;
  vertical-align: top;
}

#hshuvwgiwq .gt_row_group_first td {
  border-top-width: 2px;
}

#hshuvwgiwq .gt_row_group_first th {
  border-top-width: 2px;
}

#hshuvwgiwq .gt_summary_row {
  color: #333333;
  background-color: #FFFFFF;
  text-transform: inherit;
  padding-top: 8px;
  padding-bottom: 8px;
  padding-left: 5px;
  padding-right: 5px;
}

#hshuvwgiwq .gt_first_summary_row {
  border-top-style: solid;
  border-top-color: #D3D3D3;
}

#hshuvwgiwq .gt_first_summary_row.thick {
  border-top-width: 2px;
}

#hshuvwgiwq .gt_last_summary_row {
  padding-top: 8px;
  padding-bottom: 8px;
  padding-left: 5px;
  padding-right: 5px;
  border-bottom-style: solid;
  border-bottom-width: 2px;
  border-bottom-color: #D3D3D3;
}

#hshuvwgiwq .gt_grand_summary_row {
  color: #333333;
  background-color: #FFFFFF;
  text-transform: inherit;
  padding-top: 8px;
  padding-bottom: 8px;
  padding-left: 5px;
  padding-right: 5px;
}

#hshuvwgiwq .gt_first_grand_summary_row {
  padding-top: 8px;
  padding-bottom: 8px;
  padding-left: 5px;
  padding-right: 5px;
  border-top-style: double;
  border-top-width: 6px;
  border-top-color: #D3D3D3;
}

#hshuvwgiwq .gt_last_grand_summary_row_top {
  padding-top: 8px;
  padding-bottom: 8px;
  padding-left: 5px;
  padding-right: 5px;
  border-bottom-style: double;
  border-bottom-width: 6px;
  border-bottom-color: #D3D3D3;
}

#hshuvwgiwq .gt_striped {
  background-color: rgba(128, 128, 128, 0.05);
}

#hshuvwgiwq .gt_table_body {
  border-top-style: solid;
  border-top-width: 2px;
  border-top-color: #D3D3D3;
  border-bottom-style: solid;
  border-bottom-width: 2px;
  border-bottom-color: #D3D3D3;
}

#hshuvwgiwq .gt_footnotes {
  color: #333333;
  background-color: #FFFFFF;
  border-bottom-style: none;
  border-bottom-width: 2px;
  border-bottom-color: #D3D3D3;
  border-left-style: none;
  border-left-width: 2px;
  border-left-color: #D3D3D3;
  border-right-style: none;
  border-right-width: 2px;
  border-right-color: #D3D3D3;
}

#hshuvwgiwq .gt_footnote {
  margin: 0px;
  font-size: 90%;
  padding-top: 4px;
  padding-bottom: 4px;
  padding-left: 5px;
  padding-right: 5px;
}

#hshuvwgiwq .gt_sourcenotes {
  color: #333333;
  background-color: #FFFFFF;
  border-bottom-style: none;
  border-bottom-width: 2px;
  border-bottom-color: #D3D3D3;
  border-left-style: none;
  border-left-width: 2px;
  border-left-color: #D3D3D3;
  border-right-style: none;
  border-right-width: 2px;
  border-right-color: #D3D3D3;
}

#hshuvwgiwq .gt_sourcenote {
  font-size: 90%;
  padding-top: 4px;
  padding-bottom: 4px;
  padding-left: 5px;
  padding-right: 5px;
}

#hshuvwgiwq .gt_left {
  text-align: left;
}

#hshuvwgiwq .gt_center {
  text-align: center;
}

#hshuvwgiwq .gt_right {
  text-align: right;
  font-variant-numeric: tabular-nums;
}

#hshuvwgiwq .gt_font_normal {
  font-weight: normal;
}

#hshuvwgiwq .gt_font_bold {
  font-weight: bold;
}

#hshuvwgiwq .gt_font_italic {
  font-style: italic;
}

#hshuvwgiwq .gt_super {
  font-size: 65%;
}

#hshuvwgiwq .gt_footnote_marks {
  font-size: 75%;
  vertical-align: 0.4em;
  position: initial;
}

#hshuvwgiwq .gt_asterisk {
  font-size: 100%;
  vertical-align: 0;
}

#hshuvwgiwq .gt_indent_1 {
  text-indent: 5px;
}

#hshuvwgiwq .gt_indent_2 {
  text-indent: 10px;
}

#hshuvwgiwq .gt_indent_3 {
  text-indent: 15px;
}

#hshuvwgiwq .gt_indent_4 {
  text-indent: 20px;
}

#hshuvwgiwq .gt_indent_5 {
  text-indent: 25px;
}

#hshuvwgiwq .katex-display {
  display: inline-flex !important;
  margin-bottom: 0.75em !important;
}

#hshuvwgiwq div.Reactable > div.rt-table > div.rt-thead > div.rt-tr.rt-tr-group-header > div.rt-th-group:after {
  height: 0px !important;
}
</style>

<table class="gt_table do-not-create-environment cell caption-top table table-sm table-striped small" data-quarto-postprocess="true" data-quarto-disable-processing="false" data-quarto-bootstrap="false">
<thead>
<tr class="gt_col_headings header">
<th id="aсърд.честота" class="gt_col_heading gt_columns_bottom_border gt_right" data-quarto-table-cell-role="th" scope="col">сърд.честота</th>
<th id="aдевиация" class="gt_col_heading gt_columns_bottom_border gt_right" data-quarto-table-cell-role="th" scope="col">девиация</th>
<th id="aдевиация^2" class="gt_col_heading gt_columns_bottom_border gt_right" data-quarto-table-cell-role="th" scope="col">девиация^2</th>
</tr>
</thead>
<tbody class="gt_table_body">
<tr class="odd">
<td class="gt_row gt_right" headers="сърд.честота">90</td>
<td class="gt_row gt_right" headers="девиация">9.2</td>
<td class="gt_row gt_right" headers="девиация^2">84.64</td>
</tr>
<tr class="even">
<td class="gt_row gt_right" headers="сърд.честота">80</td>
<td class="gt_row gt_right" headers="девиация">-0.8</td>
<td class="gt_row gt_right" headers="девиация^2">0.64</td>
</tr>
<tr class="odd">
<td class="gt_row gt_right" headers="сърд.честота">89</td>
<td class="gt_row gt_right" headers="девиация">8.2</td>
<td class="gt_row gt_right" headers="девиация^2">67.24</td>
</tr>
<tr class="even">
<td class="gt_row gt_right" headers="сърд.честота">72</td>
<td class="gt_row gt_right" headers="девиация">-8.8</td>
<td class="gt_row gt_right" headers="девиация^2">77.44</td>
</tr>
<tr class="odd">
<td class="gt_row gt_right" headers="сърд.честота">73</td>
<td class="gt_row gt_right" headers="девиация">-7.8</td>
<td class="gt_row gt_right" headers="девиация^2">60.84</td>
</tr>
<tr class="even">
<td class="gt_row gt_right" headers="сърд.честота">74</td>
<td class="gt_row gt_right" headers="девиация">-6.8</td>
<td class="gt_row gt_right" headers="девиация^2">46.24</td>
</tr>
<tr class="odd">
<td class="gt_row gt_right" headers="сърд.честота">78</td>
<td class="gt_row gt_right" headers="девиация">-2.8</td>
<td class="gt_row gt_right" headers="девиация^2">7.84</td>
</tr>
<tr class="even">
<td class="gt_row gt_right" headers="сърд.честота">86</td>
<td class="gt_row gt_right" headers="девиация">5.2</td>
<td class="gt_row gt_right" headers="девиация^2">27.04</td>
</tr>
<tr class="odd">
<td class="gt_row gt_right" headers="сърд.честота">84</td>
<td class="gt_row gt_right" headers="девиация">3.2</td>
<td class="gt_row gt_right" headers="девиация^2">10.24</td>
</tr>
<tr class="even">
<td class="gt_row gt_right" headers="сърд.честота">82</td>
<td class="gt_row gt_right" headers="девиация">1.2</td>
<td class="gt_row gt_right" headers="девиация^2">1.44</td>
</tr>
</tbody>
</table>

</div>
</div>
</div>
<figcaption class="quarto-float-caption-margin quarto-float-caption quarto-float-tbl margin-caption" id="tbl-sd-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
Таблица&nbsp;8: Девиация повдигната на квадрат
</figcaption>
</figure>
</div>
</div>
<p>В третата стъпка - събираме стойностите на всички отклонения повдигнати на квадрат. Резултатът разделяме на броя на студентите, а за да “стандартизираме” използваното в предходния етап степенуване, използваме реципрочната математическа функция – коренуване.</p>
<p><span class="math display">\[ {SD} = \sqrt{\frac{84.64 + 0.64 + 67.24 + 77.44 + 60.84 + 46.24 + 7.84 + 27.04 + 10.24 + 1.44}{10}}\]</span> <span class="math display">\[SD = \sqrt{\frac{383.6}{10}} = \sqrt{38.36} = 6.19 \]</span></p>
<p>След като вече разполагаме със стандартното отклонение, можем да изразим пулса на групата по този начин <span class="math inline">\({\bar{x}} = {80.8\pm 6.19}\)</span></p>
</section>
<section id="стандартно-отклонение-при-данни-групирани-в-интервален-ред" class="level3 page-columns page-full">
<h3 class="anchored" data-anchor-id="стандартно-отклонение-при-данни-групирани-в-интервален-ред">Стандартно отклонение при данни групирани в интервален ред</h3>
<p>Нека разгледаме примера с пулса на 45 студента от втори курс. Изходните стойности са представени в <a href="#tbl-interval" class="quarto-xref">Таблица&nbsp;2</a> . За да определим стандартното отклонение, трябва да приложим следната формула:</p>
<p><span class="math display">\[{SD} = \sqrt{\frac{\sum {(x_{u} - \bar{x})^{2}}\cdot{f}}{\sum_f }}\]</span></p>
<p>Където:</p>
<ul>
<li><span class="math inline">\({SD}\)</span> е символът за стандартно отклонение;</li>
<li><span class="math inline">\(x_{u}\)</span> e средата на всеки от интервалите;</li>
<li><span class="math inline">\(\bar{x}\)</span> е средната аритметична;</li>
<li><span class="math inline">\(f\)</span> е броят на наблюденията за всеки един интервал;</li>
<li><span class="math inline">\(x_{u} - \bar{x}\)</span> е отклонението на средата на интервала от средната аритметична;</li>
<li><span class="math inline">\(\sum {(x_{u} - \bar{x})^{2}}\cdot{f}\)</span> е сумата от квадратите на всички отклонения, умножени по броя на наблюденията в интервала;</li>
<li><span class="math inline">\(\sum_f\)</span> е сумата от всички наблюдавани участници.</li>
</ul>
<p>Нека разгледаме последователно как се изчислява стандартното отклонение в посочения пример.</p>
<p>Първата стъпка е определянето на средата на интервалите - това е показано в <a href="#tbl-intervalstep1" class="quarto-xref">Таблица&nbsp;3</a> . Във втора стъпка - определяме девиацията между средата на всеки интервал и изчислената средна аритметична - <strong>65.33</strong>. Това е представено в <a href="#tbl-intervalsdstep2" class="quarto-xref">Таблица&nbsp;9</a> .</p>
<div id="tbl-intervalsdstep2" class="quarto-float quarto-figure quarto-figure-center anchored">
<figure class="quarto-float quarto-float-tbl figure">
<figcaption class="quarto-float-caption-top quarto-float-caption quarto-float-tbl" id="tbl-intervalsdstep2-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
Таблица&nbsp;9: Стъпка 2 - Определяне на девиацията
</figcaption>
<div aria-describedby="tbl-intervalsdstep2-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
<table class="caption-top table">
<colgroup>
<col style="width: 12%">
<col style="width: 27%">
<col style="width: 38%">
<col style="width: 20%">
</colgroup>
<thead>
<tr class="header">
<th style="text-align: center;">пулс</th>
<th style="text-align: center;">среда на интервала</th>
<th style="text-align: center;">Девиация <span class="math inline">\(x_{u} - \bar{x}\)</span></th>
<th style="text-align: center;">брой студенти</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td style="text-align: center;">48 - 52</td>
<td style="text-align: center;">50</td>
<td style="text-align: center;">-15.33</td>
<td style="text-align: center;">4</td>
</tr>
<tr class="even">
<td style="text-align: center;">53 - 57</td>
<td style="text-align: center;">55</td>
<td style="text-align: center;">-10.33</td>
<td style="text-align: center;">5</td>
</tr>
<tr class="odd">
<td style="text-align: center;">58 - 62</td>
<td style="text-align: center;">60</td>
<td style="text-align: center;">-5.33</td>
<td style="text-align: center;">8</td>
</tr>
<tr class="even">
<td style="text-align: center;">63 - 67</td>
<td style="text-align: center;">65</td>
<td style="text-align: center;">-0.33</td>
<td style="text-align: center;">11</td>
</tr>
<tr class="odd">
<td style="text-align: center;">68 - 72</td>
<td style="text-align: center;">70</td>
<td style="text-align: center;">4.67</td>
<td style="text-align: center;">6</td>
</tr>
<tr class="even">
<td style="text-align: center;">73 - 77</td>
<td style="text-align: center;">75</td>
<td style="text-align: center;">9.67</td>
<td style="text-align: center;">6</td>
</tr>
<tr class="odd">
<td style="text-align: center;">78 - 82</td>
<td style="text-align: center;">80</td>
<td style="text-align: center;">14.67</td>
<td style="text-align: center;">5</td>
</tr>
</tbody>
</table>
</div>
</figure>
</div>
<p>В трета стъпка - повдигаме девиациите на квадрат, както е показано в <a href="#tbl-intervalsdstep3" class="quarto-xref">Таблица&nbsp;10</a> .</p>
<div id="tbl-intervalsdstep3" class="quarto-float quarto-figure quarto-figure-center anchored" data-tbl-colwidths="[20,15,25,25,15]">
<figure class="quarto-float quarto-float-tbl figure">
<figcaption class="quarto-float-caption-top quarto-float-caption quarto-float-tbl" id="tbl-intervalsdstep3-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
Таблица&nbsp;10: Стъпка 3 - Повдигане на девиациите на втора степен
</figcaption>
<div aria-describedby="tbl-intervalsdstep3-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
<table class="caption-top table">
<colgroup>
<col style="width: 20%">
<col style="width: 15%">
<col style="width: 25%">
<col style="width: 25%">
<col style="width: 15%">
</colgroup>
<thead>
<tr class="header">
<th style="text-align: center;">пулс</th>
<th style="text-align: center;">Среда на интервала</th>
<th style="text-align: center;">Девиация <span class="math inline">\(x_{u} - \bar{x}\)</span></th>
<th style="text-align: center;"><span class="math inline">\((x_{u} - \bar{x})^{2}\)</span></th>
<th style="text-align: center;">брой студенти</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td style="text-align: center;">48 - 52</td>
<td style="text-align: center;">50</td>
<td style="text-align: center;">-15.33</td>
<td style="text-align: center;">235</td>
<td style="text-align: center;">4</td>
</tr>
<tr class="even">
<td style="text-align: center;">53 - 57</td>
<td style="text-align: center;">55</td>
<td style="text-align: center;">-10.33</td>
<td style="text-align: center;">106.7</td>
<td style="text-align: center;">5</td>
</tr>
<tr class="odd">
<td style="text-align: center;">58 - 62</td>
<td style="text-align: center;">60</td>
<td style="text-align: center;">-5.33</td>
<td style="text-align: center;">28.40</td>
<td style="text-align: center;">8</td>
</tr>
<tr class="even">
<td style="text-align: center;">63 - 67</td>
<td style="text-align: center;">65</td>
<td style="text-align: center;">-0.33</td>
<td style="text-align: center;">0.11</td>
<td style="text-align: center;">11</td>
</tr>
<tr class="odd">
<td style="text-align: center;">68 - 72</td>
<td style="text-align: center;">70</td>
<td style="text-align: center;">4.67</td>
<td style="text-align: center;">21.8</td>
<td style="text-align: center;">6</td>
</tr>
<tr class="even">
<td style="text-align: center;">73 - 77</td>
<td style="text-align: center;">75</td>
<td style="text-align: center;">9.67</td>
<td style="text-align: center;">93.7</td>
<td style="text-align: center;">6</td>
</tr>
<tr class="odd">
<td style="text-align: center;">78 - 82</td>
<td style="text-align: center;">80</td>
<td style="text-align: center;">14.67</td>
<td style="text-align: center;">215,2</td>
<td style="text-align: center;">5</td>
</tr>
</tbody>
</table>
</div>
</figure>
</div>
<p>След това умножаваме всяка една от получените стойности с броя на наблюденията в съответния интервал. Това е представено в <a href="#tbl-intervalsdstep4" class="quarto-xref">Таблица&nbsp;11</a> .</p>
<div id="tbl-intervalsdstep4" class="quarto-float quarto-figure quarto-figure-center anchored" data-tbl-colwidths="[20,15,20,20,25]">
<figure class="quarto-float quarto-float-tbl figure">
<figcaption class="quarto-float-caption-top quarto-float-caption quarto-float-tbl" id="tbl-intervalsdstep4-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
Таблица&nbsp;11: Стъпка 4 - Умножаване на квадрата на девиациите по броя студенти
</figcaption>
<div aria-describedby="tbl-intervalsdstep4-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
<table class="caption-top table">
<colgroup>
<col style="width: 20%">
<col style="width: 15%">
<col style="width: 20%">
<col style="width: 20%">
<col style="width: 25%">
</colgroup>
<thead>
<tr class="header">
<th style="text-align: center;">пулс</th>
<th style="text-align: center;">среда на интервала</th>
<th style="text-align: center;"><span class="math inline">\((x_{u} - \bar{x})^{2}\)</span></th>
<th style="text-align: center;">брой студенти (f)</th>
<th style="text-align: center;"><span class="math inline">\((x_{u} - \bar{x})^{2}\cdot{f}\)</span></th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td style="text-align: center;">48 - 52</td>
<td style="text-align: center;">50</td>
<td style="text-align: center;">235</td>
<td style="text-align: center;">4</td>
<td style="text-align: center;">940</td>
</tr>
<tr class="even">
<td style="text-align: center;">53 - 57</td>
<td style="text-align: center;">55</td>
<td style="text-align: center;">106.7</td>
<td style="text-align: center;">5</td>
<td style="text-align: center;">533.5</td>
</tr>
<tr class="odd">
<td style="text-align: center;">58 - 62</td>
<td style="text-align: center;">60</td>
<td style="text-align: center;">28.40</td>
<td style="text-align: center;">8</td>
<td style="text-align: center;">227.2</td>
</tr>
<tr class="even">
<td style="text-align: center;">63 - 67</td>
<td style="text-align: center;">65</td>
<td style="text-align: center;">0.11</td>
<td style="text-align: center;">11</td>
<td style="text-align: center;">1.21</td>
</tr>
<tr class="odd">
<td style="text-align: center;">68 - 72</td>
<td style="text-align: center;">70</td>
<td style="text-align: center;">21.8</td>
<td style="text-align: center;">6</td>
<td style="text-align: center;">130.8</td>
</tr>
<tr class="even">
<td style="text-align: center;">73 - 77</td>
<td style="text-align: center;">75</td>
<td style="text-align: center;">93.7</td>
<td style="text-align: center;">6</td>
<td style="text-align: center;">562.2</td>
</tr>
<tr class="odd">
<td style="text-align: center;">78 - 82</td>
<td style="text-align: center;">80</td>
<td style="text-align: center;">215,2</td>
<td style="text-align: center;">5</td>
<td style="text-align: center;">1076</td>
</tr>
</tbody>
</table>
</div>
</figure>
</div>
<p>Накрая сумираме всички получени произведения, разделяме ги на броя студенти и коренуваме</p>
<p><span class="math display">\[ {SD} = \sqrt{\frac{940+533.5+227.2+1.21+130.8+562.2+1076}{45}}\]</span> <span class="math display">\[ {SD} = \sqrt{\frac{3470.91}{45}} = \sqrt{77.13} = 8.78 \]</span></p>
<div class="column-page-right">
<div class="callout callout-style-default callout-important callout-titled">
<div class="callout-header d-flex align-content-center" data-bs-toggle="collapse" data-bs-target=".callout-4-contents" aria-controls="callout-4" aria-expanded="true" aria-label="Toggle callout">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-title-container flex-fill">
Важно
</div>
<div class="callout-btn-toggle d-inline-block border-0 py-1 ps-1 pe-0 float-end"><i class="callout-toggle"></i></div>
</div>
<div id="callout-4" class="callout-4-contents callout-collapse collapse show">
<div class="callout-body-container callout-body">
<p>В основата на стандартното отклонение можем да изградим <strong>предикативен интервал</strong>. Това е възможно, само ако изследваната променлива е <strong>нормално</strong> разпределена. За да “предскажем” какъв брой от изследваните имат стойност в конкретен интервал използваме правилото на трите сигми:</p>
<ul>
<li>95 % от наблюденията <strong>в извадката</strong> имат стойност на променливата в интервала между средната аритметична + или - <strong>две</strong> стандартни отклонения;</li>
<li>68% от наблюденията <strong>в извадката</strong> имат стойност на променливата в интервала между средната аритметична + или - <strong>едно</strong> стандартно отклонение;</li>
<li>99.7% от наблюденията <strong>в извадката</strong> имат стойност на променливата в интервала между средната аритметична + или - <strong>три</strong> стандартни отклонения.</li>
</ul>
<p>Нормално разпределена величина - означава, че имаме много наблюдения със стойности близки до средната аритметичната, която съвпада с медианата и модата. При построяването на графика - разпределението е камбановидно и симетрично.*</p>
<p>Ако сме изчислили теглото на извадка от 1000 души и сме установили че <span class="math inline">\({\bar{x}} = {80\pm 10}\)</span> и приемем променливата за <strong>нормално разпределена</strong> можем да твърдим, че 95 % от участниците (950 изследвани) имат тегло в диапазона <span class="math inline">\(80\pm 2\cdot{SD}= 80\pm 20\)</span> или от 60 до 120 кг. Останалите 2,5 % от останалите 50 участници (25) ще имат тегло над 110 кг, а 25 души (2,5 %) ще имат тегло под 60 кг.*</p>
</div>
</div>
</div>
</div>
<p>Илюстративно нормалното разпределение е представено на фигура <a href="#fig-normal" class="quarto-xref">Фигура&nbsp;3</a> .</p>
<div id="fig-normal" class="quarto-float quarto-figure quarto-figure-center anchored" data-fig-align="center">
<figure class="quarto-float quarto-float-fig figure">
<div aria-describedby="fig-normal-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
<img src="images/02-fig_2.png" class="img-fluid quarto-figure quarto-figure-center figure-img" width="350">
</div>
<figcaption class="quarto-float-caption-bottom quarto-float-caption quarto-float-fig" id="fig-normal-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
Фигура&nbsp;3: Нормално разпределение
</figcaption>
</figure>
</div>
</section>
</section>
<section id="интерквартилен-размах" class="level2 page-columns page-full">
<h2 class="anchored" data-anchor-id="интерквартилен-размах">Интерквартилен размах</h2>
<p>Понякога средната аритметична не е подходяща за измерване на централната тенденция. Такъв случай е разгледан по-долу, когато използваме данните за продължителността на хоспитализацията на 24 пациенти.</p>
<div class="cell">
<div class="cell-output cell-output-stdout">
<pre><code> [1] 24  4  2  3  4  1  6 17  4  3  2  6 25  1  6  4  2  4  3  6  2  1</code></pre>
</div>
</div>
<p>По-голямата част от включените в статистическия ред пациенти са прекарали между 1 и 6 дни в болница. Въпреки това, ако изчислим средната аритметична за цялата група получаваме 5.91 дни. Това число не представя добре централната тенденция, тъй като само 3 от 24-те (12.5%) пациенти са пролежали в болница за повече от 6 дни. Техните стойности се наричат екстремални, а средната аритметична силно повлияна от тях.</p>
<p>Ако нанесем броя на дните по хоризонтала, а броя на пациентите по вертикала ще получим разпределението на променливата “продължителност на хоспитализацията” – тя е представена на <a href="#fig-days" class="quarto-xref">Фигура&nbsp;4</a>.</p>
<div class="cell page-columns page-full" data-cap-location="margin">
<div class="cell-output-display page-columns page-full">
<div id="fig-days" class="quarto-float quarto-figure quarto-figure-center anchored page-columns page-full" data-cap-location="margin">
<figure class="quarto-float quarto-float-fig figure page-columns page-full">
<div aria-describedby="fig-days-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
<img src="teaching-posts-04_files/figure-html/fig-days-1.png" class="img-fluid figure-img" width="576">
</div>
<figcaption class="quarto-float-caption-margin quarto-float-caption quarto-float-fig margin-caption" id="fig-days-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
Фигура&nbsp;4: В този случай, средната аритметична (непрекъснатата линия) е изместена към екстремалните стойности. По-добър показател е медианата - тя е 4 дни (прекъснатата линия) и по-добре представя централната тенденция в данните.
</figcaption>
</figure>
</div>
</div>
</div>
<p>Представеното в <a href="#fig-days" class="quarto-xref">Фигура&nbsp;4</a> разпределение <strong>дясно изтеглено</strong>. С други думи, по-голямата част от наблюденията се намират в лявата част на средната аритметична, а екстремалните 5-ма пациенти издърпват “опашката” на разпределението на дясно. В случаи като тези, медианата е по-добър показател за централна тенденция.</p>
<p>За да разберем какво е разсейването спрямо медианата използваме показателя <strong>интерквартилен размах</strong>. Подобно на стандартното отклонение, той онагледява разсейването на наблюденията спрямо медианата. Показателят се изчислява по формула:</p>
<p><span class="math display">\[{IQR} = {Q3} - {Q1}\]</span></p>
<p>Където:</p>
<ul>
<li><span class="math inline">\({IQR}\)</span> е символът за интерквартилен размах;</li>
<li><span class="math inline">\({Q3}\)</span> е стойността на 3-тия квартил <a href="#fn10" class="footnote-ref" id="fnref10" role="doc-noteref"><sup>10</sup></a>;</li>
<li><span class="math inline">\({Q1}\)</span> е стойността на 1-вия квартил.</li>
</ul>
<p>За да разберем какво представлява интерквартилния размах, нека първо представим данните за болничния престой във възходящ ред:</p>
<div class="cell">
<div class="cell-output cell-output-stdout">
<pre><code> [1]  1  1  1  2  2  2  2  3  3  3  4  4  4  4  4  6  6  6  6 17 24 25</code></pre>
</div>
</div>
<p>Ако разделим тези 24 пациенти в 4 групи (по 6-ма) ще установим стойностите на 4-те квартила. В случая 6-тият пациент, пролежал 2 дни, е на границата между първата и останалите три четвъртини на статистическия ред. Стойността, на неговото пролежаване представлява 1-вия квартил <span class="math inline">\({Q1}\)</span>. Стойността на пролежаването на 12-тия пациент (4 дни) ограничава разделя статистически ред на две равни части, това е и медианата или втория квартил <span class="math inline">\({Q2}\)</span> - половината пациенти са пролежали повече дни от него. Стойността на пролежаването на 18-тия пациент (6 дни) е 4-тия квартил <span class="math inline">\({Q3}\)</span>.</p>
<p>След като сме определили квартилите прилагаме формулата. Интерквартилният размах е</p>
<p><span class="math display">\[{IQR} = {Q3} - {Q1} = 6 - 2 = 4\]</span></p>
<p>За графично представяне на интерквартилния размах използваме боксплот диаграмата представена на <a href="#fig-box-days" class="quarto-xref">Фигура&nbsp;5</a> .</p>
<div class="cell page-columns page-full" data-cap-location="margin">
<div class="cell-output-display page-columns page-full">
<div id="fig-box-days" class="quarto-float quarto-figure quarto-figure-center anchored page-columns page-full" data-cap-location="margin">
<figure class="quarto-float quarto-float-fig figure page-columns page-full">
<div aria-describedby="fig-box-days-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
<img src="teaching-posts-04_files/figure-html/fig-box-days-1.png" class="img-fluid figure-img" width="672">
</div>
<figcaption class="quarto-float-caption-margin quarto-float-caption quarto-float-fig margin-caption" id="fig-box-days-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
Фигура&nbsp;5: Боксплотът се описва като кутия с мустаци. Лявата страна на кутията представя първия, а дясната страна третия квартил. В средата на кутията с черна линия хоризонтална линия е представена медианата.
</figcaption>
</figure>
</div>
</div>
</div>
<p>С помощта на интерквартилния размах можем да определим кои стойности са “екстремални” <a href="#fn11" class="footnote-ref" id="fnref11" role="doc-noteref"><sup>11</sup></a></p>
</section>
</section>
<section id="инферентна-статистика" class="level1 page-columns page-full">
<h1>Инферентна статистика</h1>
<p>Показателите централна тенденция и разсейване в извадката се наричат <strong>статистики</strong>. При инферентния анализ, тези индикатори се използват за да се направи заключение за интересуващите ни <strong>параметри</strong> в генералната съвкупност <a href="#fn12" class="footnote-ref" id="fnref12" role="doc-noteref"><sup>12</sup></a>.</p>
<div class="callout callout-style-default callout-important callout-titled">
<div class="callout-header d-flex align-content-center" data-bs-toggle="collapse" data-bs-target=".callout-5-contents" aria-controls="callout-5" aria-expanded="true" aria-label="Toggle callout">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-title-container flex-fill">
Статистика и параметър
</div>
<div class="callout-btn-toggle d-inline-block border-0 py-1 ps-1 pe-0 float-end"><i class="callout-toggle"></i></div>
</div>
<div id="callout-5" class="callout-5-contents callout-collapse collapse show">
<div class="callout-body-container callout-body">
<p>Статистиката изчислена в извадка се използва за да се установят <strong>вероятните границите</strong> на параметъра в генералната съвкупност</p>
</div>
</div>
</div>
<p>За да се определи интервалът, в който с определена сигурност се намира стойността на интересуващия ни параметър, трябва първо да изчислим <strong>стандартната грешка</strong>.</p>
<section id="стандартна-грешка-на-средната-аритметична-sem" class="level2">
<h2 class="anchored" data-anchor-id="стандартна-грешка-на-средната-аритметична-sem">Стандартна грешка на средната аритметична (SEM)</h2>
<p>Нека си представим, че имаме генерална съвкупност от 200 студенти със стойност на средната аритметична равна на 3. Ако направим 9 случайни извадки (всяка по 10 студенти), можем да определим средната аритметична във всяка една от тях. Тази извадкова средна ще се различава с малко или повече от истинската поради случайната грешка, която не можем да избегнем, когато работим с извадки. Ако нанесем тези 9 извадкови средни статистики на една графика ще получим <strong>нормално разпределение</strong> (<a href="#fig-meanmean" class="quarto-xref">Фигура&nbsp;6</a>).</p>
<div id="fig-meanmean" class="quarto-float quarto-figure quarto-figure-center anchored" data-fig-align="center">
<figure class="quarto-float quarto-float-fig figure">
<div aria-describedby="fig-meanmean-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
<img src="images/02-fig_3.jpeg" class="img-fluid quarto-figure quarto-figure-center figure-img" width="400">
</div>
<figcaption class="quarto-float-caption-bottom quarto-float-caption quarto-float-fig" id="fig-meanmean-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
Фигура&nbsp;6: Разпределение на средни аритметични на 9 извадки от генералната съвкупност
</figcaption>
</figure>
</div>
<p>Колкото повече извадки от тази генерална съвкупност правим, толкова повече средната от всички извадкови статистики ще е по-близо до истинската средна за генералната съвкупност. Това е <strong>закона на големите числа</strong>. <strong>Стандартната грешка</strong> ни позволява да оценим точността на средната аритметична за всяка извадка, спрямо неизвестен параметър на генералната съвкупност.</p>
<p>За да изчислим стандартната грешка прилагаме формулата:</p>
<p><span class="math display">\[{SE_m} = \frac{SD}{\sqrt{n}}\]</span></p>
<p>Където:</p>
<ul>
<li><span class="math inline">\({SE_m}\)</span> е символът за стандартна грешка на стандартна грешка;</li>
<li><span class="math inline">\({SD}\)</span> е символът за стандартно отклонение;</li>
<li><span class="math inline">\({n}\)</span> е броят на наблюденията в извадката.</li>
</ul>
<p>Грешката зависи от стандартното отклонение – колкото по-голямо е то, толкова по-неточна е оценката. Също така от значение е обемът на извадката <span class="math inline">\({n}\)</span> – колкото повече наблюдение сме включили в извадката толкова по-малка е грешката.</p>
<p>Ако използваме примера с 10-мата студенти със среден пулс от 80.8 удара в минута и стандартно отклонение от 6.16 уд./мин, можем да изчислим стандартната грешка като заместим:</p>
<p><span class="math display">\[{SE_m} = \frac{SD}{\sqrt{n}} = \frac {6.19}{\sqrt10}= \frac {6.19}{3.16}=1.95\]</span></p>
<p>Във втория пример, с данните за 45-мата студенти в интервален ред със средната аритметична 65.33 уд./мин и стандартното отклонение 8.78 уд./мин. Стандартната грешка е</p>
<p><span class="math display">\[{SE_m} = \frac{SD}{\sqrt{n}} = \frac {8.78}{\sqrt45}= \frac {8.78}{6.71}=1.31\]</span></p>
</section>
<section id="интервал-на-доверителност-средна-аритметична" class="level2">
<h2 class="anchored" data-anchor-id="интервал-на-доверителност-средна-аритметична">Интервал на доверителност средна аритметична</h2>
<p>Интервалът на доверителност представлява <em>оценка</em> на параметъра на генералната съвкупност. Той ограничава възможните стойности на неизвестния параметър в определен интервал от числа с определена вероятност (сигурност). Тази степен на сигурност се определя от изследователя – в медицината най-често се използват 95%, 99% или 90% вероятност.</p>
<p>За да се онагледи концепцията за интервал на доверителност се използва <a href="#fig-cifig" class="quarto-xref">Фигура&nbsp;7</a> .</p>
<div id="fig-cifig" class="quarto-float quarto-figure quarto-figure-center anchored" data-fig-align="center">
<figure class="quarto-float quarto-float-fig figure">
<div aria-describedby="fig-cifig-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
<img src="images/02-fig_4.png" class="img-fluid quarto-figure quarto-figure-center figure-img" width="300">
</div>
<figcaption class="quarto-float-caption-bottom quarto-float-caption quarto-float-fig" id="fig-cifig-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
Фигура&nbsp;7: 95% интервал на доверителност сред 20 извадки
</figcaption>
</figure>
</div>
<p>Хоризонталната черна линия представлява “неизвестния” параметър в генералната съвкупност - в нашия пример това е средната пулсова честотата на II курс. Вертикалните линии представляват 95%-товите интервали на доверителност изградени в основа на 20 извадки. При 19 от тях това интервалът обхваща стойността на истината средна за генералната съвкупност (сини линии). При един интервал (5%) интервалът е неточен (в червено) и не съдържа истинската стойност на средната сърдечна честота в курса. Не е възможно изграждането на 100% интервал на доверителност! Статистиката единствено ни дава възможността да намалим несигурността си по отношение на неизвестния параметър.</p>
<p>За да конструираме интервала на доверителност използваме формулата:</p>
<p><span class="math display">\[ {CI} = \bar{x\pm}z\cdot{SE_m} \]</span></p>
<p>Където</p>
<ul>
<li><span class="math inline">\({CI}\)</span> е символът за интервал на доверителност;</li>
<li><span class="math inline">\({\bar{x}}\)</span> е средната аритметична;</li>
<li><span class="math inline">\({z}\)</span> е гаранционният множител;</li>
<li><span class="math inline">\({SE_m}\)</span> е стандартната грешка.</li>
</ul>
<p><strong>Гаранционният множител</strong> <span class="math inline">\(z\)</span> е константа, която зависи от това избраното ниво на сигурност, с което искаме да определим интервала на доверителност. Най-често избираното ниво в медицината е <strong>95%</strong>, за което стойността на <span class="math inline">\(z\)</span> е 1,96 <a href="#fn13" class="footnote-ref" id="fnref13" role="doc-noteref"><sup>13</sup></a>.</p>
<p>Нека използваме примера за 10-те студенти със среден пулс 80,8 и стандартна грешка от 1.95. 95% -овия интервал на доверителност се изчислява като:</p>
<p><span class="math display">\[ {95\%CI} = 80.8 {\pm} 1.95{\cdot}1.96 = 80.8{\pm} 3.82\]</span></p>
<p>В основа на нашата извадка, можем да кажем, че с <strong>95% сигурност, средната сърдечна честота на курса се намира в диапазона между 76.98 и 84.62 уд./мин</strong>.</p>
</section>
<section id="стандартна-грешка-и-интервал-на-доверителност-за-пропорция" class="level2 page-columns page-full">
<h2 class="anchored" data-anchor-id="стандартна-грешка-и-интервал-на-доверителност-за-пропорция">Стандартна грешка и интервал на доверителност за пропорция</h2>
<p>Стандартната грешка може да бъде изчислена за качествени променливи измервани на номинална и ординални скали. Нека вземем пример за параметър – относителния дял на момичетата в 2-ри курс. Да приемем, че нямаме достъп до генералната съвкупност и трябва да направим заключение в основата на една студентска група от 12 студента, 6 от които са момичета.</p>

<div class="no-row-height column-margin column-container"><section id="важно-1" class="level3">
<h3 class="anchored" data-anchor-id="важно-1">Важно</h3>
<p>Ако изберем да използваме ниво на сигурност 99% умножаваме по по-висока стойност на гаранционния множител - това ще доведе до разширение на ширината на интервала на доверителност. Обратно, ако изберем да използваме ниво на сигурност 90% умножаваме по по-ниска стойност на гаранционния множител - това ще доведе до намаление на ширината на интервала на доверителност.</p>
</section></div><p>Първо - изчисляваме относителния дял (статистика) в извадката</p>
<p><span class="math display">\[ {\hat{p}} = \frac{6}{12} = 50\%\]</span></p>
<p>След това изчисляваме стандартната грешка</p>
<p><span class="math display">\[ {SE_p}= \sqrt{\frac{\hat{p}\cdot{(100-{\hat{p})}}}{n}}\]</span></p>
<p><span class="math display">\[ {SE_p} = \sqrt{\frac{50\cdot{50}}{12}}=\sqrt{\frac{2500}{12}}\]</span></p>
<p><span class="math display">\[{SE_p}=\sqrt{208}= 14.4\% \]</span></p>
<p>Накрая определяме 95%-овия интервал на доверителност за параметъра в генералната съвкупност:</p>
<p><span class="math display">\[ {CI} = \bar{x\pm}z\cdot{SE_m} \]</span></p>
<p><span class="math display">\[{95\%CI} = 50\%\pm{1.96} \cdot{14.4}\%\]</span></p>
<p><span class="math display">\[{95\%CI} = 50\%\pm28.2\%\]</span></p>
<p>Изводът е, че с <strong>95%-ова сигурност</strong> можем да твърдим, че относителният дял на момичетата в 2-ри курс е в интервала между 21.8% и 78.2%.</p>
</section>
</section>
<section id="задачи-и-тестове-за-самоподготовка" class="level1">
<h1>Задачи и тестове за самоподготовка</h1>
<section id="задача-1" class="level2">
<h2 class="anchored" data-anchor-id="задача-1">Задача 1</h2>
<p>След провеждане на тренировъчен режим с група спортисти в края на периода е измерено теглото в килограми. Получени са следните стойности: 64, 76, 68, 84, 80. 72, 74, 72 кг. Да се определи средното тегло на групата и границите на 95% от интервал на доверителност за средното тегло на спортистите в популацията.</p>
</section>
<section id="задача-2" class="level2">
<h2 class="anchored" data-anchor-id="задача-2">Задача 2</h2>
<p>Изследвана е съобразителността на 40 студента при работа с компютри по определена психологична задача. Да се изчисли средното време, употребено от студентите за решаването и при следните резултати. Да се определят границите на 95% - овия доверителен интервал за средната аритметична. Времето е количествена променлива.</p>
<table class="caption-top table">
<thead>
<tr class="header">
<th style="text-align: center;">Употребено време (мин)</th>
<th style="text-align: center;">Брой студенти</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td style="text-align: center;">3</td>
<td style="text-align: center;">1</td>
</tr>
<tr class="even">
<td style="text-align: center;">4</td>
<td style="text-align: center;">3</td>
</tr>
<tr class="odd">
<td style="text-align: center;">5</td>
<td style="text-align: center;">4</td>
</tr>
<tr class="even">
<td style="text-align: center;">6</td>
<td style="text-align: center;">7</td>
</tr>
<tr class="odd">
<td style="text-align: center;">7</td>
<td style="text-align: center;">8</td>
</tr>
<tr class="even">
<td style="text-align: center;">8</td>
<td style="text-align: center;">9</td>
</tr>
<tr class="odd">
<td style="text-align: center;">9</td>
<td style="text-align: center;">8</td>
</tr>
<tr class="even">
<td style="text-align: center;">общо</td>
<td style="text-align: center;">40</td>
</tr>
</tbody>
</table>
</section>
<section id="задача-3" class="level2">
<h2 class="anchored" data-anchor-id="задача-3">Задача 3</h2>
<p>Дадена е променливата “диагноза” с нейните разновидности. Преобразувайте категорийната променлива в дихотомна и изчислете границите на 95%-овия интервал на доверителност за относителния дял на пациенти с хепатит от популацията.</p>
<table class="caption-top table">
<thead>
<tr class="header">
<th style="text-align: left;">Диагноза</th>
<th style="text-align: center;">Брой пациенти</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td style="text-align: left;">Колит</td>
<td style="text-align: center;">10</td>
</tr>
<tr class="even">
<td style="text-align: left;">Гастрит</td>
<td style="text-align: center;">18</td>
</tr>
<tr class="odd">
<td style="text-align: left;">Апендицит</td>
<td style="text-align: center;">22</td>
</tr>
<tr class="even">
<td style="text-align: left;">Язва</td>
<td style="text-align: center;">29</td>
</tr>
<tr class="odd">
<td style="text-align: left;">Хепатит</td>
<td style="text-align: center;">38</td>
</tr>
<tr class="even">
<td style="text-align: left;">Общо</td>
<td style="text-align: center;">117</td>
</tr>
</tbody>
</table>
</section>
<section id="задача-4" class="level2">
<h2 class="anchored" data-anchor-id="задача-4">Задача 4</h2>
<p>По случаен принцип са подбрани две извадки с обем съответно п = 320 и n = 540 индивиди с белодробни проблеми. Изследваните случаи от първата извадка са третирани с антибактериален препарат “А” без витамини, докато в терапията на втората извадка са включени и витамини. Случаите с подобрение в първата група са 98, а във втората група 231. Да се изчислят границите на 95% в доверителен интервал за относителния дял на случаите с подобрение в двете извадки.</p>
<table class="caption-top table">
<thead>
<tr class="header">
<th>Терапия</th>
<th style="text-align: center;">Всички пациенти</th>
<th style="text-align: center;">Случаи с подобрение</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td>А без витамини</td>
<td style="text-align: center;">320</td>
<td style="text-align: center;">98</td>
</tr>
<tr class="even">
<td>А с витамини</td>
<td style="text-align: center;">540</td>
<td style="text-align: center;">231</td>
</tr>
</tbody>
</table>
</section>
<section id="тестове" class="level2">
<h2 class="anchored" data-anchor-id="тестове">Тестове</h2>
<ol type="1">
<li>Кой от изброените вариационни редове има мода?</li>
</ol>
<ol type="a">
<li>1, 4, 5, 7, 9, 11, 12, 13</li>
<li>2, 4, 5, 7, 9, 11, 12, 13</li>
<li>1, 4, 5, 7, 9, 11, 11, 13</li>
<li>1, 4, 5, 7, 9, 11, 12, 14</li>
</ol>
<ol start="2" type="1">
<li>Кое от следните твърдения е грешно?</li>
</ol>
<ol type="a">
<li>Степенните вариационни редове водят до по-прецизни крайни оценки в сравнение с интервалните.</li>
<li>Количествените променливи винаги могат да бъдат преобразувани в качествени.</li>
<li>Променливата пол се измерва на номинална скала.</li>
<li>Променливата ръст при раждане се измерва на интервална скала.</li>
</ol>
<ol start="3" type="1">
<li>В случай на дясно изтеглено разпределение:</li>
</ol>
<ol type="a">
<li>Средната аритметична е по-голяма по стойност от модата и показателят за асиметрия е положителен.</li>
<li>Средната аритметична е по-малка по стойност от модата и показателят за асиметрия е положителен.</li>
<li>Средната аритметична е по-голяма по стойност от модата и показателят за асиметрия е отрицателен.</li>
<li>Средната аритметична е по-малка по стойност от модата и показателят за асиметрия е отрицателен.</li>
</ol>
<ol start="4" type="1">
<li>Доверителна вероятност от 90% означава:</li>
</ol>
<ol type="a">
<li>90 от 100 доверителни интервала биха довели до грешно заключение за популационния параметър.</li>
<li>100 от 1 000 доверителни интервала биха довели до грешно заключение за популационния параметър.</li>
<li>Използваме гаранционен множител Z=1.96 при изчисляване на границите на доверителния интервал.</li>
<li>Вероятността за вярно заключение относно изучавания популационен параметър е 10%.</li>
</ol>
<ol start="5" type="1">
<li>Кой от изброените отговори съдържа само променливи, които могат да бъдат измерени на интервална или пропорционална скала?</li>
</ol>
<ol type="a">
<li>Кръвна група, систолно кръвно налягане, стадий на заболяване</li>
<li>Ниво на кръвна захар, тегло, индекс на телесна маса</li>
<li>Индекс на телесна маса, кръвна група, семеен статус</li>
<li>Систолно кръвно налягане, индекс на телесна маса, пол</li>
</ol>


</section>
</section>


<div id="quarto-appendix" class="default"><section id="footnotes" class="footnotes footnotes-end-of-document" role="doc-endnotes"><h2 class="anchored quarto-appendix-heading">Бележки</h2>

<ol>
<li id="fn1"><p>За да направим това “обобщение” е необходимо извадката да бъде представителна - тоест, да възпроизвежда структурата (най-малко по пол и възраст) на генералната съвкупност, а наблюдаваните единици да са избрани случайно.<a href="#fnref1" class="footnote-back" role="doc-backlink">↩︎</a></p></li>
<li id="fn2"><p>Въпреки, че прекъснатите характеристики не се изразяват с дробни числа, много често това се налага, когато те се анализират като прекъснати променливи. Така, въпреки че за някого звучи абсурдно, може да кажем, че средностатистическата българка ражда 1.7 деца.<a href="#fnref2" class="footnote-back" role="doc-backlink">↩︎</a></p></li>
<li id="fn3"><p>Ако кажем за един човек, че е висок, това не е равнозначно да кажем, че неговият ръст е 185 см. В първия случаи използваме неточно измерване на “номинална скала”, а във втория - точно на “пропорционална скала”<a href="#fnref3" class="footnote-back" role="doc-backlink">↩︎</a></p></li>
<li id="fn4"><p>“Централна тенденция” означава използването на стойност, която описва всички участници в извадката “като едно цяло”.”Разсейване” означава колко са “разпръснати” наблюденията около централна тенденция.<a href="#fnref4" class="footnote-back" role="doc-backlink">↩︎</a></p></li>
<li id="fn5"><p><strong>Важно!</strong> За разлика от интервалния при степенния ред, знаем стойността на всяко едно наблюдение. Тоест не “губим” статистическа точност.<a href="#fnref5" class="footnote-back" role="doc-backlink">↩︎</a></p></li>
<li id="fn6"><p>Ако сме измерили кръвна на 5 пациенти със следните стойности 6.0; 6.5; <strong>7.0</strong>; 7.5; 8.0, стойността 7.0 е медиана - защото разделя възходящо подредения ред на две симетрични части.<a href="#fnref6" class="footnote-back" role="doc-backlink">↩︎</a></p></li>
<li id="fn7"><p>Ако имаме ред с четни стойности като: 6.0; 6.5; <strong>7.0; 7.5</strong>; 8.0; 8.5, медианата получаваме като разделим на две сбора от двете стойности в средата на реда - в случая медианата в случая е 7,25.<a href="#fnref7" class="footnote-back" role="doc-backlink">↩︎</a></p></li>
<li id="fn8"><p>Ако имаме следните данни за систолното кръвно налягане <strong>120</strong>; <strong>120</strong>; 130; 135; <strong>120</strong>; 140; 140 модата е <strong>120</strong> -защото представена е най-много пъти. В статистически ред е възможно да няма мода или да има две и повече моди.<a href="#fnref8" class="footnote-back" role="doc-backlink">↩︎</a></p></li>
<li id="fn9"><p>Размахът не се използва рутинно в медицинската статистика, защото е зависим само от две стойности, а понякога те са екстремални поради грешки в измерването.<a href="#fnref9" class="footnote-back" role="doc-backlink">↩︎</a></p></li>
<li id="fn10"><p>“Квартилите” са стойностите на наблюденията, която разделят статистическия ред на 4 равни части.<a href="#fnref10" class="footnote-back" role="doc-backlink">↩︎</a></p></li>
<li id="fn11"><p>Екстремални са всички стойности по-високи от <span class="math inline">\({Q3}+1.5\cdot{IQR}\)</span> или по-ниски от <span class="math inline">\({Q1} - 1.5\cdot{IQR}\)</span>. В посочения пример такива са стойностите над <span class="math inline">\({6}+1.5\cdot{4}\)</span>) и под <span class="math inline">\({2}-1.5\cdot{4}\)</span>.<a href="#fnref11" class="footnote-back" role="doc-backlink">↩︎</a></p></li>
<li id="fn12"><p>Средният пулс на групата от 10 студенти представлява <strong>статистика</strong>, а средният пулс на генералната съвкупност - студентите от II-ри курс представлява <strong>параметър</strong>.<a href="#fnref12" class="footnote-back" role="doc-backlink">↩︎</a></p></li>
<li id="fn13"><p>Ако искаме да конструираме 99% интервал, стойността <span class="math inline">\(z\)</span> е 2.58, при 90% интервал - 1.65<a href="#fnref13" class="footnote-back" role="doc-backlink">↩︎</a></p></li>
</ol>
</section></div></main> <!-- /main -->
<script id="quarto-html-after-body" type="application/javascript">
  window.document.addEventListener("DOMContentLoaded", function (event) {
    const icon = "";
    const anchorJS = new window.AnchorJS();
    anchorJS.options = {
      placement: 'right',
      icon: icon
    };
    anchorJS.add('.anchored');
    const isCodeAnnotation = (el) => {
      for (const clz of el.classList) {
        if (clz.startsWith('code-annotation-')) {                     
          return true;
        }
      }
      return false;
    }
    const onCopySuccess = function(e) {
      // button target
      const button = e.trigger;
      // don't keep focus
      button.blur();
      // flash "checked"
      button.classList.add('code-copy-button-checked');
      var currentTitle = button.getAttribute("title");
      button.setAttribute("title", "Копирано!");
      let tooltip;
      if (window.bootstrap) {
        button.setAttribute("data-bs-toggle", "tooltip");
        button.setAttribute("data-bs-placement", "left");
        button.setAttribute("data-bs-title", "Копирано!");
        tooltip = new bootstrap.Tooltip(button, 
          { trigger: "manual", 
            customClass: "code-copy-button-tooltip",
            offset: [0, -8]});
        tooltip.show();    
      }
      setTimeout(function() {
        if (tooltip) {
          tooltip.hide();
          button.removeAttribute("data-bs-title");
          button.removeAttribute("data-bs-toggle");
          button.removeAttribute("data-bs-placement");
        }
        button.setAttribute("title", currentTitle);
        button.classList.remove('code-copy-button-checked');
      }, 1000);
      // clear code selection
      e.clearSelection();
    }
    const getTextToCopy = function(trigger) {
        const codeEl = trigger.previousElementSibling.cloneNode(true);
        for (const childEl of codeEl.children) {
          if (isCodeAnnotation(childEl)) {
            childEl.remove();
          }
        }
        return codeEl.innerText;
    }
    const clipboard = new window.ClipboardJS('.code-copy-button:not([data-in-quarto-modal])', {
      text: getTextToCopy
    });
    clipboard.on('success', onCopySuccess);
    if (window.document.getElementById('quarto-embedded-source-code-modal')) {
      const clipboardModal = new window.ClipboardJS('.code-copy-button[data-in-quarto-modal]', {
        text: getTextToCopy,
        container: window.document.getElementById('quarto-embedded-source-code-modal')
      });
      clipboardModal.on('success', onCopySuccess);
    }
      var localhostRegex = new RegExp(/^(?:http|https):\/\/localhost\:?[0-9]*\//);
      var mailtoRegex = new RegExp(/^mailto:/);
        var filterRegex = new RegExp('/' + window.location.host + '/');
      var isInternal = (href) => {
          return filterRegex.test(href) || localhostRegex.test(href) || mailtoRegex.test(href);
      }
      // Inspect non-navigation links and adorn them if external
     var links = window.document.querySelectorAll('a[href]:not(.nav-link):not(.navbar-brand):not(.toc-action):not(.sidebar-link):not(.sidebar-item-toggle):not(.pagination-link):not(.no-external):not([aria-hidden]):not(.dropdown-item):not(.quarto-navigation-tool):not(.about-link)');
      for (var i=0; i<links.length; i++) {
        const link = links[i];
        if (!isInternal(link.href)) {
          // undo the damage that might have been done by quarto-nav.js in the case of
          // links that we want to consider external
          if (link.dataset.originalHref !== undefined) {
            link.href = link.dataset.originalHref;
          }
        }
      }
    function tippyHover(el, contentFn, onTriggerFn, onUntriggerFn) {
      const config = {
        allowHTML: true,
        maxWidth: 500,
        delay: 100,
        arrow: false,
        appendTo: function(el) {
            return el.parentElement;
        },
        interactive: true,
        interactiveBorder: 10,
        theme: 'quarto',
        placement: 'bottom-start',
      };
      if (contentFn) {
        config.content = contentFn;
      }
      if (onTriggerFn) {
        config.onTrigger = onTriggerFn;
      }
      if (onUntriggerFn) {
        config.onUntrigger = onUntriggerFn;
      }
      window.tippy(el, config); 
    }
    const noterefs = window.document.querySelectorAll('a[role="doc-noteref"]');
    for (var i=0; i<noterefs.length; i++) {
      const ref = noterefs[i];
      tippyHover(ref, function() {
        // use id or data attribute instead here
        let href = ref.getAttribute('data-footnote-href') || ref.getAttribute('href');
        try { href = new URL(href).hash; } catch {}
        const id = href.replace(/^#\/?/, "");
        const note = window.document.getElementById(id);
        if (note) {
          return note.innerHTML;
        } else {
          return "";
        }
      });
    }
    const xrefs = window.document.querySelectorAll('a.quarto-xref');
    const processXRef = (id, note) => {
      // Strip column container classes
      const stripColumnClz = (el) => {
        el.classList.remove("page-full", "page-columns");
        if (el.children) {
          for (const child of el.children) {
            stripColumnClz(child);
          }
        }
      }
      stripColumnClz(note)
      if (id === null || id.startsWith('sec-')) {
        // Special case sections, only their first couple elements
        const container = document.createElement("div");
        if (note.children && note.children.length > 2) {
          container.appendChild(note.children[0].cloneNode(true));
          for (let i = 1; i < note.children.length; i++) {
            const child = note.children[i];
            if (child.tagName === "P" && child.innerText === "") {
              continue;
            } else {
              container.appendChild(child.cloneNode(true));
              break;
            }
          }
          if (window.Quarto?.typesetMath) {
            window.Quarto.typesetMath(container);
          }
          return container.innerHTML
        } else {
          if (window.Quarto?.typesetMath) {
            window.Quarto.typesetMath(note);
          }
          return note.innerHTML;
        }
      } else {
        // Remove any anchor links if they are present
        const anchorLink = note.querySelector('a.anchorjs-link');
        if (anchorLink) {
          anchorLink.remove();
        }
        if (window.Quarto?.typesetMath) {
          window.Quarto.typesetMath(note);
        }
        if (note.classList.contains("callout")) {
          return note.outerHTML;
        } else {
          return note.innerHTML;
        }
      }
    }
    for (var i=0; i<xrefs.length; i++) {
      const xref = xrefs[i];
      tippyHover(xref, undefined, function(instance) {
        instance.disable();
        let url = xref.getAttribute('href');
        let hash = undefined; 
        if (url.startsWith('#')) {
          hash = url;
        } else {
          try { hash = new URL(url).hash; } catch {}
        }
        if (hash) {
          const id = hash.replace(/^#\/?/, "");
          const note = window.document.getElementById(id);
          if (note !== null) {
            try {
              const html = processXRef(id, note.cloneNode(true));
              instance.setContent(html);
            } finally {
              instance.enable();
              instance.show();
            }
          } else {
            // See if we can fetch this
            fetch(url.split('#')[0])
            .then(res => res.text())
            .then(html => {
              const parser = new DOMParser();
              const htmlDoc = parser.parseFromString(html, "text/html");
              const note = htmlDoc.getElementById(id);
              if (note !== null) {
                const html = processXRef(id, note);
                instance.setContent(html);
              } 
            }).finally(() => {
              instance.enable();
              instance.show();
            });
          }
        } else {
          // See if we can fetch a full url (with no hash to target)
          // This is a special case and we should probably do some content thinning / targeting
          fetch(url)
          .then(res => res.text())
          .then(html => {
            const parser = new DOMParser();
            const htmlDoc = parser.parseFromString(html, "text/html");
            const note = htmlDoc.querySelector('main.content');
            if (note !== null) {
              // This should only happen for chapter cross references
              // (since there is no id in the URL)
              // remove the first header
              if (note.children.length > 0 && note.children[0].tagName === "HEADER") {
                note.children[0].remove();
              }
              const html = processXRef(null, note);
              instance.setContent(html);
            } 
          }).finally(() => {
            instance.enable();
            instance.show();
          });
        }
      }, function(instance) {
      });
    }
        let selectedAnnoteEl;
        const selectorForAnnotation = ( cell, annotation) => {
          let cellAttr = 'data-code-cell="' + cell + '"';
          let lineAttr = 'data-code-annotation="' +  annotation + '"';
          const selector = 'span[' + cellAttr + '][' + lineAttr + ']';
          return selector;
        }
        const selectCodeLines = (annoteEl) => {
          const doc = window.document;
          const targetCell = annoteEl.getAttribute("data-target-cell");
          const targetAnnotation = annoteEl.getAttribute("data-target-annotation");
          const annoteSpan = window.document.querySelector(selectorForAnnotation(targetCell, targetAnnotation));
          const lines = annoteSpan.getAttribute("data-code-lines").split(",");
          const lineIds = lines.map((line) => {
            return targetCell + "-" + line;
          })
          let top = null;
          let height = null;
          let parent = null;
          if (lineIds.length > 0) {
              //compute the position of the single el (top and bottom and make a div)
              const el = window.document.getElementById(lineIds[0]);
              top = el.offsetTop;
              height = el.offsetHeight;
              parent = el.parentElement.parentElement;
            if (lineIds.length > 1) {
              const lastEl = window.document.getElementById(lineIds[lineIds.length - 1]);
              const bottom = lastEl.offsetTop + lastEl.offsetHeight;
              height = bottom - top;
            }
            if (top !== null && height !== null && parent !== null) {
              // cook up a div (if necessary) and position it 
              let div = window.document.getElementById("code-annotation-line-highlight");
              if (div === null) {
                div = window.document.createElement("div");
                div.setAttribute("id", "code-annotation-line-highlight");
                div.style.position = 'absolute';
                parent.appendChild(div);
              }
              div.style.top = top - 2 + "px";
              div.style.height = height + 4 + "px";
              div.style.left = 0;
              let gutterDiv = window.document.getElementById("code-annotation-line-highlight-gutter");
              if (gutterDiv === null) {
                gutterDiv = window.document.createElement("div");
                gutterDiv.setAttribute("id", "code-annotation-line-highlight-gutter");
                gutterDiv.style.position = 'absolute';
                const codeCell = window.document.getElementById(targetCell);
                const gutter = codeCell.querySelector('.code-annotation-gutter');
                gutter.appendChild(gutterDiv);
              }
              gutterDiv.style.top = top - 2 + "px";
              gutterDiv.style.height = height + 4 + "px";
            }
            selectedAnnoteEl = annoteEl;
          }
        };
        const unselectCodeLines = () => {
          const elementsIds = ["code-annotation-line-highlight", "code-annotation-line-highlight-gutter"];
          elementsIds.forEach((elId) => {
            const div = window.document.getElementById(elId);
            if (div) {
              div.remove();
            }
          });
          selectedAnnoteEl = undefined;
        };
          // Handle positioning of the toggle
      window.addEventListener(
        "resize",
        throttle(() => {
          elRect = undefined;
          if (selectedAnnoteEl) {
            selectCodeLines(selectedAnnoteEl);
          }
        }, 10)
      );
      function throttle(fn, ms) {
      let throttle = false;
      let timer;
        return (...args) => {
          if(!throttle) { // first call gets through
              fn.apply(this, args);
              throttle = true;
          } else { // all the others get throttled
              if(timer) clearTimeout(timer); // cancel #2
              timer = setTimeout(() => {
                fn.apply(this, args);
                timer = throttle = false;
              }, ms);
          }
        };
      }
        // Attach click handler to the DT
        const annoteDls = window.document.querySelectorAll('dt[data-target-cell]');
        for (const annoteDlNode of annoteDls) {
          annoteDlNode.addEventListener('click', (event) => {
            const clickedEl = event.target;
            if (clickedEl !== selectedAnnoteEl) {
              unselectCodeLines();
              const activeEl = window.document.querySelector('dt[data-target-cell].code-annotation-active');
              if (activeEl) {
                activeEl.classList.remove('code-annotation-active');
              }
              selectCodeLines(clickedEl);
              clickedEl.classList.add('code-annotation-active');
            } else {
              // Unselect the line
              unselectCodeLines();
              clickedEl.classList.remove('code-annotation-active');
            }
          });
        }
    const findCites = (el) => {
      const parentEl = el.parentElement;
      if (parentEl) {
        const cites = parentEl.dataset.cites;
        if (cites) {
          return {
            el,
            cites: cites.split(' ')
          };
        } else {
          return findCites(el.parentElement)
        }
      } else {
        return undefined;
      }
    };
    var bibliorefs = window.document.querySelectorAll('a[role="doc-biblioref"]');
    for (var i=0; i<bibliorefs.length; i++) {
      const ref = bibliorefs[i];
      const citeInfo = findCites(ref);
      if (citeInfo) {
        tippyHover(citeInfo.el, function() {
          var popup = window.document.createElement('div');
          citeInfo.cites.forEach(function(cite) {
            var citeDiv = window.document.createElement('div');
            citeDiv.classList.add('hanging-indent');
            citeDiv.classList.add('csl-entry');
            var biblioDiv = window.document.getElementById('ref-' + cite);
            if (biblioDiv) {
              citeDiv.innerHTML = biblioDiv.innerHTML;
            }
            popup.appendChild(citeDiv);
          });
          return popup.innerHTML;
        });
      }
    }
  });
  </script>
</div> <!-- /content -->
<footer class="footer">
  <div class="nav-footer">
    <div class="nav-footer-left">
<p>Email me at <a href="mailto:kostadinr.kostadinov@mu-plovdiv.bg">kostadinr.kostadinov@mu-plovdiv.bg</a> or book a <a href="https://tinyurl.com/whentomeetme" target="_blank">meeting</a></p>
</div>   
    <div class="nav-footer-center">
      &nbsp;
    </div>
    <div class="nav-footer-right">
      &nbsp;
    </div>
  </div>
</footer>




</body></html>