<!DOCTYPE html>
<html xmlns="http://www.w3.org/1999/xhtml" lang="en" xml:lang="en"><head>

<meta charset="utf-8">
<meta name="generator" content="quarto-1.9.37">

<meta name="viewport" content="width=device-width, initial-scale=1.0, user-scalable=yes">

<meta name="author" content="Kostadin Kostadinov">
<meta name="dcterms.date" content="2026-08-16">
<meta name="description" content="One cohort, one deliberately misleading crude estimate, and a worked tour of kkstatfun — from 2×2 tables and colour-blindness audits to targeted causal inference, interrupted time series and cost-effectiveness curves. Then the public-health workflow it sits inside: getting NHIS data out of the system under ЗДОИ, the pipeline that cleans it, where AI actually helps, and how it reaches a manuscript.">

<title>A Package That Argues With You: kkstatfun, One Analysis Start to Finish – Kostadin Kostadinov</title>
<style>
/* Default styles provided by pandoc.
** See https://pandoc.org/MANUAL.html#variables-for-html for config info.
*/
code{white-space: pre-wrap;}
span.smallcaps{font-variant: small-caps;}
div.columns{display: flex; gap: min(4vw, 1.5em);}
div.column{flex: auto; overflow-x: auto;}
div.hanging-indent{margin-left: 1.5em; text-indent: -1.5em;}
ul.task-list{list-style: none;}
ul.task-list li input[type="checkbox"] {
  width: 0.8em;
  margin: 0 0.8em 0.2em -1em; /* quarto-specific, see https://github.com/quarto-dev/quarto-cli/issues/4556 */ 
  vertical-align: middle;
}
/* CSS for syntax highlighting */
html { -webkit-text-size-adjust: 100%; }
pre > code.sourceCode { white-space: pre; position: relative; }
pre > code.sourceCode > span { display: inline-block; line-height: 1.25; }
pre > code.sourceCode > span:empty { height: 1.2em; }
.sourceCode { overflow: visible; }
code.sourceCode > span { color: inherit; text-decoration: inherit; }
div.sourceCode { margin: 1em 0; }
pre.sourceCode { margin: 0; }
@media screen {
div.sourceCode { overflow: auto; }
}
@media print {
pre > code.sourceCode { white-space: pre-wrap; }
pre > code.sourceCode > span { text-indent: -5em; padding-left: 5em; }
}
pre.numberSource code
  { counter-reset: source-line 0; }
pre.numberSource code > span
  { position: relative; left: -4em; counter-increment: source-line; }
pre.numberSource code > span > a:first-child::before
  { content: counter(source-line);
    position: relative; left: -1em; text-align: right; vertical-align: baseline;
    border: none; display: inline-block;
    -webkit-touch-callout: none; -webkit-user-select: none;
    -khtml-user-select: none; -moz-user-select: none;
    -ms-user-select: none; user-select: none;
    padding: 0 4px; width: 4em;
  }
pre.numberSource { margin-left: 3em;  padding-left: 4px; }
div.sourceCode
  {   }
@media screen {
pre > code.sourceCode > span > a:first-child::before { text-decoration: underline; }
}
</style>


<script src="../site_libs/quarto-nav/quarto-nav.js"></script>
<script src="../site_libs/quarto-nav/headroom.min.js"></script>
<script src="../site_libs/clipboard/clipboard.min.js"></script>
<script src="../site_libs/quarto-search/autocomplete.umd.js"></script>
<script src="../site_libs/quarto-search/fuse.min.js"></script>
<script src="../site_libs/quarto-search/quarto-search.js"></script>
<meta name="quarto:offset" content="../">
<link href="../favicon.png" rel="icon" type="image/png">
<script src="../site_libs/quarto-html/quarto.js" type="module"></script>
<script src="../site_libs/quarto-html/tabsets/tabsets.js" type="module"></script>
<script src="../site_libs/quarto-html/popper.min.js"></script>
<script src="../site_libs/quarto-html/tippy.umd.min.js"></script>
<script src="../site_libs/quarto-html/anchor.min.js"></script>
<link href="../site_libs/quarto-html/tippy.css" rel="stylesheet">
<link href="../site_libs/quarto-html/quarto-syntax-highlighting-993615bec231d6057790b9e3465a04b0.css" rel="stylesheet" class="quarto-color-scheme" id="quarto-text-highlighting-styles">
<link href="../site_libs/quarto-html/quarto-syntax-highlighting-dark-8f3d97f8e51a6dae54ce054eebf10868.css" rel="stylesheet" class="quarto-color-scheme quarto-color-alternate" id="quarto-text-highlighting-styles">
<link href="../site_libs/quarto-html/quarto-syntax-highlighting-993615bec231d6057790b9e3465a04b0.css" rel="stylesheet" class="quarto-color-scheme-extra" id="quarto-text-highlighting-styles">
<script src="../site_libs/bootstrap/bootstrap.min.js"></script>
<link href="../site_libs/bootstrap/bootstrap-icons.css" rel="stylesheet">
<link href="../site_libs/bootstrap/bootstrap-bdd62bf60ee9af6da7d6f01dc1eb4b72.min.css" rel="stylesheet" append-hash="true" class="quarto-color-scheme" id="quarto-bootstrap" data-mode="light">
<link href="../site_libs/bootstrap/bootstrap-dark-691dfc7af7cbd832f7fe67ba9e416462.min.css" rel="stylesheet" append-hash="true" class="quarto-color-scheme quarto-color-alternate" id="quarto-bootstrap" data-mode="dark">
<link href="../site_libs/bootstrap/bootstrap-bdd62bf60ee9af6da7d6f01dc1eb4b72.min.css" rel="stylesheet" append-hash="true" class="quarto-color-scheme-extra" id="quarto-bootstrap" data-mode="light">
<script id="quarto-search-options" type="application/json">{
  "location": "navbar",
  "copy-button": false,
  "collapse-after": 3,
  "panel-placement": "end",
  "type": "overlay",
  "limit": 50,
  "keyboard-shortcut": [
    "f",
    "/",
    "s"
  ],
  "show-item-context": false,
  "language": {
    "search-no-results-text": "No results",
    "search-matching-documents-text": "matching documents",
    "search-copy-link-title": "Copy link to search",
    "search-hide-matches-text": "Hide additional matches",
    "search-more-match-text": "more match in this document",
    "search-more-matches-text": "more matches in this document",
    "search-clear-button-title": "Clear",
    "search-text-placeholder": "",
    "search-detached-cancel-button-title": "Cancel",
    "search-submit-button-title": "Submit",
    "search-label": "Search"
  }
}</script>


<link rel="stylesheet" href="../styles.css">
<link rel="stylesheet" href="../assets/teaching.css">
<meta name="twitter:title" content="A Package That Argues With You: kkstatfun, One Analysis Start to Finish – Kostadin Kostadinov">
<meta name="twitter:description" content="One cohort, one deliberately misleading crude estimate, and a worked tour of kkstatfun — from 2×2 tables and colour-blindness audits to targeted causal inference, interrupted time series and cost-effectiveness curves. Then the public-health workflow it sits inside: getting NHIS data out of the system under ЗДОИ, the pipeline that cleans it, where AI actually helps, and how it reaches a manuscript.">
<meta name="twitter:image" content="https://kostadinoff.github.io/blog/kkstatfun-worked-example_files/figure-html/fig-cvd-1.png">
<meta name="twitter:creator" content="@https://x.com/kostadinoffMD">
<meta name="twitter:image-height" content="2040">
<meta name="twitter:image-width" content="4800">
<meta name="twitter:card" content="summary_large_image">
</head>

<body class="nav-fixed blog-post quarto-light"><script id="quarto-html-before-body" type="application/javascript">
    const toggleBodyColorMode = (bsSheetEl) => {
      const mode = bsSheetEl.getAttribute("data-mode");
      const bodyEl = window.document.querySelector("body");
      if (mode === "dark") {
        bodyEl.classList.add("quarto-dark");
        bodyEl.classList.remove("quarto-light");
      } else {
        bodyEl.classList.add("quarto-light");
        bodyEl.classList.remove("quarto-dark");
      }
    }
    const toggleBodyColorPrimary = () => {
      const bsSheetEl = window.document.querySelector("link#quarto-bootstrap:not([rel=disabled-stylesheet])");
      if (bsSheetEl) {
        toggleBodyColorMode(bsSheetEl);
      }
    }
    const setColorSchemeToggle = (alternate) => {
      const toggles = window.document.querySelectorAll('.quarto-color-scheme-toggle');
      for (let i=0; i < toggles.length; i++) {
        const toggle = toggles[i];
        if (toggle) {
          if (alternate) {
            toggle.classList.add("alternate");
          } else {
            toggle.classList.remove("alternate");
          }
        }
      }
    };
    const toggleColorMode = (alternate) => {
      // Switch the stylesheets
      const primaryStylesheets = window.document.querySelectorAll('link.quarto-color-scheme:not(.quarto-color-alternate)');
      const alternateStylesheets = window.document.querySelectorAll('link.quarto-color-scheme.quarto-color-alternate');
      manageTransitions('#quarto-margin-sidebar .nav-link', false);
      if (alternate) {
        // note: dark is layered on light, we don't disable primary!
        enableStylesheet(alternateStylesheets);
        for (const sheetNode of alternateStylesheets) {
          if (sheetNode.id === "quarto-bootstrap") {
            toggleBodyColorMode(sheetNode);
          }
        }
      } else {
        disableStylesheet(alternateStylesheets);
        enableStylesheet(primaryStylesheets)
        toggleBodyColorPrimary();
      }
      manageTransitions('#quarto-margin-sidebar .nav-link', true);
      // Switch the toggles
      setColorSchemeToggle(alternate)
      // Hack to workaround the fact that safari doesn't
      // properly recolor the scrollbar when toggling (#1455)
      if (navigator.userAgent.indexOf('Safari') > 0 && navigator.userAgent.indexOf('Chrome') == -1) {
        manageTransitions("body", false);
        window.scrollTo(0, 1);
        setTimeout(() => {
          window.scrollTo(0, 0);
          manageTransitions("body", true);
        }, 40);
      }
    }
    const disableStylesheet = (stylesheets) => {
      for (let i=0; i < stylesheets.length; i++) {
        const stylesheet = stylesheets[i];
        stylesheet.rel = 'disabled-stylesheet';
      }
    }
    const enableStylesheet = (stylesheets) => {
      for (let i=0; i < stylesheets.length; i++) {
        const stylesheet = stylesheets[i];
        if(stylesheet.rel !== 'stylesheet') { // for Chrome, which will still FOUC without this check
          stylesheet.rel = 'stylesheet';
        }
      }
    }
    const manageTransitions = (selector, allowTransitions) => {
      const els = window.document.querySelectorAll(selector);
      for (let i=0; i < els.length; i++) {
        const el = els[i];
        if (allowTransitions) {
          el.classList.remove('notransition');
        } else {
          el.classList.add('notransition');
        }
      }
    }
    const isFileUrl = () => {
      return window.location.protocol === 'file:';
    }
    const hasAlternateSentinel = () => {
      let styleSentinel = getColorSchemeSentinel();
      if (styleSentinel !== null) {
        return styleSentinel === "alternate";
      } else {
        return false;
      }
    }
    const setStyleSentinel = (alternate) => {
      const value = alternate ? "alternate" : "default";
      if (!isFileUrl()) {
        window.localStorage.setItem("quarto-color-scheme", value);
      } else {
        localAlternateSentinel = value;
      }
    }
    const getColorSchemeSentinel = () => {
      if (!isFileUrl()) {
        const storageValue = window.localStorage.getItem("quarto-color-scheme");
        return storageValue != null ? storageValue : localAlternateSentinel;
      } else {
        return localAlternateSentinel;
      }
    }
    const toggleGiscusIfUsed = (isAlternate, darkModeDefault) => {
      const baseTheme = document.querySelector('#giscus-base-theme')?.value ?? 'light';
      const alternateTheme = document.querySelector('#giscus-alt-theme')?.value ?? 'dark';
      let newTheme = '';
      if(authorPrefersDark) {
        newTheme = isAlternate ? baseTheme : alternateTheme;
      } else {
        newTheme = isAlternate ? alternateTheme : baseTheme;
      }
      const changeGiscusTheme = () => {
        // From: https://github.com/giscus/giscus/issues/336
        const sendMessage = (message) => {
          const iframe = document.querySelector('iframe.giscus-frame');
          if (!iframe) return;
          iframe.contentWindow.postMessage({ giscus: message }, 'https://giscus.app');
        }
        sendMessage({
          setConfig: {
            theme: newTheme
          }
        });
      }
      const isGiscussLoaded = window.document.querySelector('iframe.giscus-frame') !== null;
      if (isGiscussLoaded) {
        changeGiscusTheme();
      }
    };
    const authorPrefersDark = false;
    const queryPrefersDark = window.matchMedia('(prefers-color-scheme: dark)');
    const darkModeDefault = queryPrefersDark.matches;
      document.querySelector('link#quarto-text-highlighting-styles.quarto-color-scheme-extra').rel = 'disabled-stylesheet';
      document.querySelector('link#quarto-bootstrap.quarto-color-scheme-extra').rel = 'disabled-stylesheet';
    let localAlternateSentinel = darkModeDefault ? 'alternate' : 'default';
    // Dark / light mode switch
    window.quartoToggleColorScheme = () => {
      // Read the current dark / light value
      let toAlternate = !hasAlternateSentinel();
      toggleColorMode(toAlternate);
      setStyleSentinel(toAlternate);
      toggleGiscusIfUsed(toAlternate, darkModeDefault);
      window.dispatchEvent(new Event('resize'));
    };
    queryPrefersDark.addEventListener("change", e => {
      if(window.localStorage.getItem("quarto-color-scheme") !== null)
        return;
      const alternate = e.matches
      toggleColorMode(alternate);
      localAlternateSentinel = e.matches ? 'alternate' : 'default'; // this is used alongside local storage!
      toggleGiscusIfUsed(alternate, darkModeDefault);
    });
    // Switch to dark mode if need be
    if (hasAlternateSentinel()) {
      toggleColorMode(true);
    } else {
      toggleColorMode(false);
    }
  </script>

<div id="quarto-search-results"></div>
  <header id="quarto-header" class="headroom fixed-top quarto-banner">
    <nav class="navbar navbar-expand-lg " data-bs-theme="dark">
      <div class="navbar-container container-fluid">
      <div class="navbar-brand-container mx-auto">
    <a class="navbar-brand" href="../index.html">
    <span class="navbar-title">Kostadin Kostadinov</span>
    </a>
  </div>
            <div id="quarto-search" class="" title="Search"></div>
          <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarCollapse" aria-controls="navbarCollapse" role="menu" aria-expanded="false" aria-label="Toggle navigation" onclick="if (window.quartoToggleHeadroom) { window.quartoToggleHeadroom(); }">
  <span class="navbar-toggler-icon"></span>
</button>
          <div class="collapse navbar-collapse" id="navbarCollapse">
            <ul class="navbar-nav navbar-nav-scroll me-auto">
  <li class="nav-item">
    <a class="nav-link" href="../index.html"> 
<span class="menu-text">Home</span></a>
  </li>  
  <li class="nav-item">
    <a class="nav-link" href="../CV.html"> 
<span class="menu-text">CV</span></a>
  </li>  
  <li class="nav-item dropdown ">
    <a class="nav-link dropdown-toggle" href="#" id="nav-menu-teaching" role="link" data-bs-toggle="dropdown" aria-expanded="false">
 <span class="menu-text">Teaching</span>
    </a>
    <ul class="dropdown-menu" aria-labelledby="nav-menu-teaching">    
        <li>
    <a class="dropdown-item" href="../slides.html">
 <span class="dropdown-text">Teaching materials</span></a>
  </li>  
        <li>
    <a class="dropdown-item" href="../learning.html">
 <span class="dropdown-text">15-minute learning</span></a>
  </li>  
        <li>
    <a class="dropdown-item" href="../tasks.html">
 <span class="dropdown-text">Learning tasks</span></a>
  </li>  
        <li>
    <a class="dropdown-item" href="../study-guide.html">
 <span class="dropdown-text">Study guides</span></a>
  </li>  
    </ul>
  </li>
  <li class="nav-item">
    <a class="nav-link" href="../blog.html"> 
<span class="menu-text">Blog</span></a>
  </li>  
  <li class="nav-item">
    <a class="nav-link" href="../epinews.html"> 
<span class="menu-text">Epi News</span></a>
  </li>  
  <li class="nav-item">
    <a class="nav-link" href="../kkstatfun.html"> 
<span class="menu-text">kkstatfun</span></a>
  </li>  
  <li class="nav-item">
    <a class="nav-link" href="../lab.html"> 
<span class="menu-text">Lab</span></a>
  </li>  
</ul>
            <ul class="navbar-nav navbar-nav-scroll ms-auto">
  <li class="nav-item compact">
    <a class="nav-link" href="https://github.com/kostadinoff"> <i class="bi bi-github" role="img">
</i> 
<span class="menu-text"></span></a>
  </li>  
  <li class="nav-item compact">
    <a class="nav-link" href="https://x.com/kostadinoffMD"> <i class="bi bi-twitter" role="img">
</i> 
<span class="menu-text"></span></a>
  </li>  
  <li class="nav-item compact">
    <a class="nav-link" href="https://www.linkedin.com/in/kostadinovmd/"> <i class="bi bi-linkedin" role="img">
</i> 
<span class="menu-text"></span></a>
  </li>  
  <li class="nav-item compact">
    <a class="nav-link" href="../epinews.xml"> <i class="bi bi-rss" role="img">
</i> 
<span class="menu-text"></span></a>
  </li>  
</ul>
          </div> <!-- /navcollapse -->
            <div class="quarto-navbar-tools">
  <a href="" class="quarto-color-scheme-toggle quarto-navigation-tool  px-1" onclick="window.quartoToggleColorScheme(); return false;" title="Toggle dark mode"><i class="bi"></i></a>
</div>
      </div> <!-- /container-fluid -->
    </nav>
</header>
<!-- content -->
<header id="title-block-header" class="quarto-title-block default page-columns page-full">
  <div class="quarto-title-banner page-columns page-full">
    <div class="quarto-title column-body">
      <h1 class="title">A Package That Argues With You: kkstatfun, One Analysis Start to Finish</h1>
                  <div>
        <div class="description">
          One cohort, one deliberately misleading crude estimate, and a worked tour of kkstatfun — from 2×2 tables and colour-blindness audits to targeted causal inference, interrupted time series and cost-effectiveness curves. Then the public-health workflow it sits inside: getting NHIS data out of the system under ЗДОИ, the pipeline that cleans it, where AI actually helps, and how it reaches a manuscript.
        </div>
      </div>
                          <div class="quarto-categories">
                <div class="quarto-category">R</div>
                <div class="quarto-category">kkstatfun</div>
                <div class="quarto-category">epidemiology</div>
                <div class="quarto-category">causal inference</div>
                <div class="quarto-category">public health</div>
                <div class="quarto-category">reproducibility</div>
                <div class="quarto-category">workflow</div>
              </div>
                  </div>
  </div>
    
  
  <div class="quarto-title-meta">

      <div>
      <div class="quarto-title-meta-heading">Author</div>
      <div class="quarto-title-meta-contents">
               <p>Kostadin Kostadinov </p>
            </div>
    </div>
      
      <div>
      <div class="quarto-title-meta-heading">Published</div>
      <div class="quarto-title-meta-contents">
        <p class="date">August 16, 2026</p>
      </div>
    </div>
    
      <div>
      <div class="quarto-title-meta-heading">Modified</div>
      <div class="quarto-title-meta-contents">
        <p class="date-modified">August 16, 2026</p>
      </div>
    </div>
      
    </div>
    
  
  </header><div id="quarto-content" class="quarto-container page-columns page-rows-contents page-layout-article page-navbar">
<!-- sidebar -->
<!-- margin-sidebar -->
    <div id="quarto-margin-sidebar" class="sidebar margin-sidebar">
        <nav id="TOC" role="doc-toc" class="toc-active">
    <h2 id="toc-title">On this page</h2>
   
  <ul>
  <li><a href="#setup-and-a-palette-that-fails-its-own-audit" id="toc-setup-and-a-palette-that-fails-its-own-audit" class="nav-link active" data-scroll-target="#setup-and-a-palette-that-fails-its-own-audit">1. Setup, and a palette that fails its own audit</a></li>
  <li><a href="#the-data-and-why-it-is-synthetic" id="toc-the-data-and-why-it-is-synthetic" class="nav-link" data-scroll-target="#the-data-and-why-it-is-synthetic">2. The data, and why it is synthetic</a></li>
  <li><a href="#the-estimate-that-would-get-published" id="toc-the-estimate-that-would-get-published" class="nav-link" data-scroll-target="#the-estimate-that-would-get-published">3. The estimate that would get published</a></li>
  <li><a href="#group_by-is-the-whole-design" id="toc-group_by-is-the-whole-design" class="nav-link" data-scroll-target="#group_by-is-the-whole-design">4. <code>group_by()</code> is the whole design</a></li>
  <li><a href="#adjusted-weighted-and-doubly-robust" id="toc-adjusted-weighted-and-doubly-robust" class="nav-link" data-scroll-target="#adjusted-weighted-and-doubly-robust">5. Adjusted, weighted, and doubly robust</a></li>
  <li><a href="#diagnostics-validating-a-marker" id="toc-diagnostics-validating-a-marker" class="nav-link" data-scroll-target="#diagnostics-validating-a-marker">6. Diagnostics: validating a marker</a></li>
  <li><a href="#time-to-event" id="toc-time-to-event" class="nav-link" data-scroll-target="#time-to-event">7. Time to event</a></li>
  <li><a href="#when-assignment-was-a-rule-not-a-judgement" id="toc-when-assignment-was-a-rule-not-a-judgement" class="nav-link" data-scroll-target="#when-assignment-was-a-rule-not-a-judgement">8. When assignment was a rule, not a judgement</a></li>
  <li><a href="#costing-it" id="toc-costing-it" class="nav-link" data-scroll-target="#costing-it">9. Costing it</a></li>
  <li><a href="#everything-else-briefly" id="toc-everything-else-briefly" class="nav-link" data-scroll-target="#everything-else-briefly">10. Everything else, briefly</a></li>
  <li><a href="#the-philosophy-stated-plainly" id="toc-the-philosophy-stated-plainly" class="nav-link" data-scroll-target="#the-philosophy-stated-plainly">11. The philosophy, stated plainly</a></li>
  <li><a href="#where-this-actually-gets-used-nhis-data" id="toc-where-this-actually-gets-used-nhis-data" class="nav-link" data-scroll-target="#where-this-actually-gets-used-nhis-data">12. Where this actually gets used: NHIS data</a>
  <ul class="collapse">
  <li><a href="#asking-for-the-data" id="toc-asking-for-the-data" class="nav-link" data-scroll-target="#asking-for-the-data">Asking for the data</a></li>
  <li><a href="#the-pipeline" id="toc-the-pipeline" class="nav-link" data-scroll-target="#the-pipeline">The pipeline</a></li>
  <li><a href="#then-and-only-then-the-analysis" id="toc-then-and-only-then-the-analysis" class="nav-link" data-scroll-target="#then-and-only-then-the-analysis">Then, and only then, the analysis</a></li>
  <li><a href="#where-ai-fits-and-where-it-does-not" id="toc-where-ai-fits-and-where-it-does-not" class="nav-link" data-scroll-target="#where-ai-fits-and-where-it-does-not">Where AI fits, and where it does not</a></li>
  <li><a href="#writing-it-up" id="toc-writing-it-up" class="nav-link" data-scroll-target="#writing-it-up">Writing it up</a></li>
  </ul></li>
  <li><a href="#reproducing-this-post" id="toc-reproducing-this-post" class="nav-link" data-scroll-target="#reproducing-this-post">Reproducing this post</a></li>
  </ul>
</nav>
    </div>
<!-- main -->
<main class="content quarto-banner-title-block" id="quarto-document-content">






<p>Every applied statistics package makes a claim about what analysis <em>is</em>. Most claim it is a sequence of tests: you hand over data, you get back a <em>p</em>-value, and the interpretation is left as an exercise. <a href="../kkstatfun.html"><code>kkstatfun</code></a> claims something else, and this post tries to demonstrate that claim rather than assert it — that an analysis is a chain of decisions, that most of those decisions should be made once and then reused, and that a good tool makes the uncomfortable ones visible instead of hiding them behind a default.</p>
<p>So this is not a feature list — the <a href="../kkstatfun.html">reference page</a> already is one. It is a single worked analysis, run end to end, on a dataset built so that <strong>the honest answer and the obvious answer point in opposite directions</strong>. Every number below was produced by the code shown above it when this page was rendered. Nothing is transcribed.</p>
<p>Then, in §12, the part that actually pays for the package: the public-health workflow it sits inside. How the data gets out of the National Health Information System in the first place, what has to happen to it before an estimate is legitimate, and which parts of that I now hand to a machine.</p>
<div class="callout callout-style-default callout-note callout-titled">
<div class="callout-header d-flex align-content-center">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-title-container flex-fill">
<span class="screen-reader-only">Note</span>The short version
</div>
</div>
<div class="callout-body-container callout-body">
<p>A crude 2×2 table on this cohort says that giving antibiotics within four hours <em>increases</em> 30-day mortality by half. It is wrong, and it is wrong for the most ordinary reason in clinical epidemiology: the sickest patients are treated fastest. Six <code>kkstatfun</code> functions — stratification, Mantel–Haenszel, risk-ratio regression, standardised differences, IPTW and TMLE — each recover the truth from a different direction. The package’s contribution is not any one of those estimators. It is that they all take the same data frame, honour the same <code>group_by()</code>, and return the same shape of tibble, so you can afford to run all six.</p>
</div>
</div>
<section id="setup-and-a-palette-that-fails-its-own-audit" class="level2">
<h2 class="anchored" data-anchor-id="setup-and-a-palette-that-fails-its-own-audit">1. Setup, and a palette that fails its own audit</h2>
<p>The opening lines of every analysis I write are the same four:</p>
<div class="cell" data-layout-align="center">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb1"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb1-1"><a href="#cb1-1" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(kkstatfun)</span>
<span id="cb1-2"><a href="#cb1-2" aria-hidden="true" tabindex="-1"></a><span class="fu">kk_setup</span>()</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-stderr">
<pre><code>#&gt; ✅ kkstatfun environment configured:</code></pre>
</div>
<div class="cell-output cell-output-stderr">
<pre><code>#&gt;    - Cores: 5</code></pre>
</div>
<div class="cell-output cell-output-stderr">
<pre><code>#&gt;    - Backend: cmdstanr</code></pre>
</div>
<div class="cell-output cell-output-stderr">
<pre><code>#&gt;    - Scientific notation disabled</code></pre>
</div>
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb6"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb6-1"><a href="#cb6-1" aria-hidden="true" tabindex="-1"></a>myfont <span class="ot">&lt;-</span> <span class="st">"Roboto Condensed"</span></span>
<span id="cb6-2"><a href="#cb6-2" aria-hidden="true" tabindex="-1"></a><span class="fu">set_plot_font</span>(myfont, <span class="at">size =</span> <span class="dv">14</span>)</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-stdout">
<pre><code>#&gt; 🔍 Searching for font: Roboto Condensed 
#&gt;  Checking system source...</code></pre>
</div>
<div class="cell-output cell-output-stderr">
<pre><code>#&gt;  ✓ Found in system source!</code></pre>
</div>
<div class="cell-output cell-output-stderr">
<pre><code>#&gt; ✓ Updated ggplot2 theme with font 'Roboto Condensed'</code></pre>
</div>
<div class="cell-output cell-output-stderr">
<pre><code>#&gt; ✅ Font setup complete. Using: Roboto Condensed</code></pre>
</div>
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb11"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb11-1"><a href="#cb11-1" aria-hidden="true" tabindex="-1"></a><span class="fu">set_plot_colors</span>(<span class="fu">c</span>(<span class="st">"#D62828"</span>, <span class="st">"#003049"</span>, <span class="st">"#F77F00"</span>))</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-stderr">
<pre><code>#&gt; ✓ Default discrete palette set from 3 anchor colour(s): #D62828, #003049, #F77F00</code></pre>
</div>
</div>
<p><code>kk_setup()</code> configures parallel workers and disables scientific notation. <code>set_plot_font()</code> searches your system, then local font files, then Google Fonts, and updates the default <code>ggplot2</code> theme, so every figure in the session inherits it without a <code>theme()</code> call. <code>set_plot_colors()</code> does the same for the discrete palette: three anchor colours, expanded on demand and installed as the session default.</p>
<p>Three colours I like. But <em>liking</em> a palette is not evidence that it works, and version 1.2.0 added the functions that check:</p>
<div class="cell" data-layout-align="center">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb13"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb13-1"><a href="#cb13-1" aria-hidden="true" tabindex="-1"></a><span class="fu">kk_pal_check</span>(<span class="fu">c</span>(<span class="st">"#D62828"</span>, <span class="st">"#003049"</span>, <span class="st">"#F77F00"</span>)) <span class="sc">|&gt;</span></span>
<span id="cb13-2"><a href="#cb13-2" aria-hidden="true" tabindex="-1"></a>  <span class="fu">filter</span>(<span class="sc">!</span>distinct <span class="sc">|</span> <span class="sc">!</span>graphic)</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-stdout">
<pre><code>#&gt; # A tibble: 4 × 8
#&gt;   color   vision  simulated contrast graphic nearest min_dist distinct
#&gt;   &lt;chr&gt;   &lt;fct&gt;   &lt;chr&gt;        &lt;dbl&gt; &lt;lgl&gt;   &lt;chr&gt;      &lt;dbl&gt; &lt;lgl&gt;   
#&gt; 1 #F77F00 normal  #F77F00       2.63 FALSE   #D62828    0.179 TRUE    
#&gt; 2 #F77F00 deutan  #C0AA00       2.33 FALSE   #D62828    0.155 TRUE    
#&gt; 3 #F77F00 tritan  #FF636C       2.90 FALSE   #D62828    0.120 TRUE    
#&gt; 4 #F77F00 achroma #A0A0A0       2.63 FALSE   #D62828    0.162 TRUE</code></pre>
</div>
</div>
<p>An empty result would mean the palette passes. This one does not. The three colours stay perceptually distinct under deuteranopia, protanopia, tritanopia and full achromatopsia — the <code>distinct</code> column is <code>TRUE</code> throughout, which is the check most people mean when they say “colour-blind safe”. What fails is a different thing: the orange has a WCAG contrast ratio against white of about 2.6, below the 3.0 needed for graphical objects. On a projector or a photocopy, an orange <em>line</em> on white disappears. An orange <em>area</em> is fine.</p>
<div class="cell" data-layout-align="center">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb15"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb15-1"><a href="#cb15-1" aria-hidden="true" tabindex="-1"></a><span class="fu">kk_show_cvd</span>(<span class="fu">c</span>(<span class="st">"#D62828"</span>, <span class="st">"#003049"</span>, <span class="st">"#F77F00"</span>))</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output-display">
<div id="fig-cvd" class="quarto-float quarto-figure quarto-figure-center anchored" data-fig-align="center">
<figure class="quarto-float quarto-float-fig figure">
<div aria-describedby="fig-cvd-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
<img src="kkstatfun-worked-example_files/figure-html/fig-cvd-1.png" class="img-fluid quarto-figure quarto-figure-center figure-img" style="width:100.0%">
</div>
<figcaption class="quarto-float-caption-bottom quarto-float-caption quarto-float-fig" id="fig-cvd-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
Figure&nbsp;1: The requested palette simulated under four vision types. The categories never collapse into each other — the failure is contrast against the background, not confusability between hues.
</figcaption>
</figure>
</div>
</div>
</div>
<p>I am keeping the palette, because I use those colours for fills and points rather than hairlines, and because I would rather hold a documented exception than pretend the audit passed. Had I wanted the machine to solve it instead, one call builds a palette that is safe by construction:</p>
<div class="cell" data-layout-align="center">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb16"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb16-1"><a href="#cb16-1" aria-hidden="true" tabindex="-1"></a><span class="fu">kk_pal_safe</span>(<span class="dv">4</span>, <span class="at">seed_colors =</span> <span class="st">"#003049"</span>)</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-stdout">
<pre><code>#&gt; [1] "#003049" "#A88E00" "#3453D3" "#704E00"
#&gt; attr(,"min_dist")
#&gt; [1] 0.1785405</code></pre>
</div>
</div>
<p>That is the package’s whole attitude in one function. It did not silently fix my figure, and it did not refuse to run. It told me what was wrong, in units I can act on, and left the decision with me.</p>
</section>
<section id="the-data-and-why-it-is-synthetic" class="level2">
<h2 class="anchored" data-anchor-id="the-data-and-why-it-is-synthetic">2. The data, and why it is synthetic</h2>
<p>The cohort below is generated, not downloaded. That is a deliberate choice over a Kaggle dataset, and for one reason: <strong>I know the true effect</strong>. A real dataset lets you demonstrate that a function runs. A simulated one lets you check whether it is <em>right</em> — every estimator in this post can be scored against a number I put into the data myself.</p>
<p>Three thousand adults admitted with community-acquired pneumonia to eight hospitals, 2018–2024. The exposure is antibiotics within four hours of arrival; the outcome is death within 30 days. The generator has two features that matter. First, <strong>the sickest patients are treated fastest</strong> — severity raises the probability of early treatment, and it raises mortality independently. That is confounding by indication, and it is not a pathological edge case; it is the default state of every observational treatment comparison in acute medicine. Second, the true causal effect of early treatment is a <strong>risk ratio of 0.70</strong>, written into the data as <code>log(0.70)</code> in a log-binomial model.</p>
<div class="cell" data-layout-align="center">
<details class="code-fold">
<summary>The data generator (click to expand)</summary>
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb18"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb18-1"><a href="#cb18-1" aria-hidden="true" tabindex="-1"></a><span class="fu">set.seed</span>(<span class="dv">2026</span>)</span>
<span id="cb18-2"><a href="#cb18-2" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb18-3"><a href="#cb18-3" aria-hidden="true" tabindex="-1"></a>n <span class="ot">&lt;-</span> <span class="dv">3000</span></span>
<span id="cb18-4"><a href="#cb18-4" aria-hidden="true" tabindex="-1"></a>hospitals <span class="ot">&lt;-</span> <span class="fu">paste</span>(<span class="st">"Hospital"</span>, LETTERS[<span class="dv">1</span><span class="sc">:</span><span class="dv">8</span>])</span>
<span id="cb18-5"><a href="#cb18-5" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb18-6"><a href="#cb18-6" aria-hidden="true" tabindex="-1"></a>cap <span class="ot">&lt;-</span> <span class="fu">tibble</span>(</span>
<span id="cb18-7"><a href="#cb18-7" aria-hidden="true" tabindex="-1"></a>  <span class="at">id       =</span> <span class="fu">seq_len</span>(n),</span>
<span id="cb18-8"><a href="#cb18-8" aria-hidden="true" tabindex="-1"></a>  <span class="at">hospital =</span> <span class="fu">sample</span>(hospitals, n, <span class="at">replace =</span> <span class="cn">TRUE</span>,</span>
<span id="cb18-9"><a href="#cb18-9" aria-hidden="true" tabindex="-1"></a>                    <span class="at">prob =</span> <span class="fu">c</span>(.<span class="dv">18</span>, .<span class="dv">16</span>, .<span class="dv">14</span>, .<span class="dv">12</span>, .<span class="dv">11</span>, .<span class="dv">10</span>, .<span class="dv">10</span>, .<span class="dv">09</span>)),</span>
<span id="cb18-10"><a href="#cb18-10" aria-hidden="true" tabindex="-1"></a>  <span class="at">year     =</span> <span class="fu">sample</span>(<span class="dv">2018</span><span class="sc">:</span><span class="dv">2024</span>, n, <span class="at">replace =</span> <span class="cn">TRUE</span>),</span>
<span id="cb18-11"><a href="#cb18-11" aria-hidden="true" tabindex="-1"></a>  <span class="at">age      =</span> <span class="fu">pmin</span>(<span class="fu">pmax</span>(<span class="fu">round</span>(<span class="fu">rnorm</span>(n, <span class="dv">68</span>, <span class="dv">14</span>)), <span class="dv">18</span>), <span class="dv">98</span>),</span>
<span id="cb18-12"><a href="#cb18-12" aria-hidden="true" tabindex="-1"></a>  <span class="at">sex      =</span> <span class="fu">sample</span>(<span class="fu">c</span>(<span class="st">"Male"</span>, <span class="st">"Female"</span>), n, <span class="cn">TRUE</span>, <span class="fu">c</span>(.<span class="dv">54</span>, .<span class="dv">46</span>)),</span>
<span id="cb18-13"><a href="#cb18-13" aria-hidden="true" tabindex="-1"></a>  <span class="at">smoker   =</span> <span class="fu">rbinom</span>(n, <span class="dv">1</span>, <span class="fl">0.31</span>),</span>
<span id="cb18-14"><a href="#cb18-14" aria-hidden="true" tabindex="-1"></a>  <span class="at">charlson =</span> <span class="fu">rpois</span>(n, <span class="fl">1.8</span>)</span>
<span id="cb18-15"><a href="#cb18-15" aria-hidden="true" tabindex="-1"></a>) <span class="sc">|&gt;</span></span>
<span id="cb18-16"><a href="#cb18-16" aria-hidden="true" tabindex="-1"></a>  <span class="fu">mutate</span>(</span>
<span id="cb18-17"><a href="#cb18-17" aria-hidden="true" tabindex="-1"></a>    <span class="co"># severity rises with age and comorbidity</span></span>
<span id="cb18-18"><a href="#cb18-18" aria-hidden="true" tabindex="-1"></a>    <span class="at">curb65 =</span> <span class="fu">pmin</span>(<span class="fu">rbinom</span>(n, <span class="dv">4</span>, <span class="fu">plogis</span>(<span class="sc">-</span><span class="fl">1.4</span> <span class="sc">+</span> <span class="fl">0.030</span> <span class="sc">*</span> (age <span class="sc">-</span> <span class="dv">68</span>) <span class="sc">+</span> <span class="fl">0.16</span> <span class="sc">*</span> charlson)), <span class="dv">4</span>),</span>
<span id="cb18-19"><a href="#cb18-19" aria-hidden="true" tabindex="-1"></a>    <span class="co"># the sickest are triaged fastest -&gt; confounding by indication</span></span>
<span id="cb18-20"><a href="#cb18-20" aria-hidden="true" tabindex="-1"></a>    <span class="at">early_abx =</span> <span class="fu">rbinom</span>(n, <span class="dv">1</span>, <span class="fu">plogis</span>(<span class="sc">-</span><span class="fl">1.05</span> <span class="sc">+</span> <span class="fl">0.95</span> <span class="sc">*</span> curb65 <span class="sc">+</span></span>
<span id="cb18-21"><a href="#cb18-21" aria-hidden="true" tabindex="-1"></a>                                      <span class="fl">0.012</span> <span class="sc">*</span> (age <span class="sc">-</span> <span class="dv">68</span>) <span class="sc">-</span> <span class="fl">0.20</span> <span class="sc">*</span> smoker)),</span>
<span id="cb18-22"><a href="#cb18-22" aria-hidden="true" tabindex="-1"></a>    <span class="co"># true log-binomial risk model; TRUE risk ratio of early_abx = 0.70</span></span>
<span id="cb18-23"><a href="#cb18-23" aria-hidden="true" tabindex="-1"></a>    <span class="at">p_death =</span> <span class="fu">pmin</span>(<span class="fu">exp</span>(<span class="sc">-</span><span class="fl">3.55</span> <span class="sc">+</span> <span class="fl">0.78</span> <span class="sc">*</span> curb65 <span class="sc">+</span> <span class="fl">0.028</span> <span class="sc">*</span> (age <span class="sc">-</span> <span class="dv">68</span>) <span class="sc">+</span> <span class="fl">0.22</span> <span class="sc">*</span> smoker <span class="sc">+</span></span>
<span id="cb18-24"><a href="#cb18-24" aria-hidden="true" tabindex="-1"></a>                       <span class="fl">0.17</span> <span class="sc">*</span> charlson <span class="sc">+</span> <span class="fu">log</span>(<span class="fl">0.70</span>) <span class="sc">*</span> early_abx), <span class="fl">0.95</span>),</span>
<span id="cb18-25"><a href="#cb18-25" aria-hidden="true" tabindex="-1"></a>    <span class="at">death30 =</span> <span class="fu">rbinom</span>(n, <span class="dv">1</span>, p_death),</span>
<span id="cb18-26"><a href="#cb18-26" aria-hidden="true" tabindex="-1"></a>    <span class="co"># bacterial aetiology, procalcitonin, and a rapid antigen test</span></span>
<span id="cb18-27"><a href="#cb18-27" aria-hidden="true" tabindex="-1"></a>    <span class="at">bacterial =</span> <span class="fu">rbinom</span>(n, <span class="dv">1</span>, <span class="fu">plogis</span>(<span class="sc">-</span><span class="fl">0.35</span> <span class="sc">+</span> <span class="fl">0.35</span> <span class="sc">*</span> curb65 <span class="sc">-</span> <span class="fl">0.012</span> <span class="sc">*</span> (age <span class="sc">-</span> <span class="dv">68</span>))),</span>
<span id="cb18-28"><a href="#cb18-28" aria-hidden="true" tabindex="-1"></a>    <span class="at">pct       =</span> <span class="fu">round</span>(<span class="fu">exp</span>(<span class="fu">rnorm</span>(n, <span class="sc">-</span><span class="fl">0.55</span> <span class="sc">+</span> <span class="fl">1.55</span> <span class="sc">*</span> bacterial <span class="sc">+</span> <span class="fl">0.18</span> <span class="sc">*</span> curb65, <span class="fl">0.85</span>)), <span class="dv">2</span>),</span>
<span id="cb18-29"><a href="#cb18-29" aria-hidden="true" tabindex="-1"></a>    <span class="at">rapid_ag  =</span> <span class="fu">rbinom</span>(n, <span class="dv">1</span>, <span class="fu">ifelse</span>(bacterial <span class="sc">==</span> <span class="dv">1</span>, <span class="fl">0.74</span>, <span class="fl">0.07</span>)),</span>
<span id="cb18-30"><a href="#cb18-30" aria-hidden="true" tabindex="-1"></a>    <span class="co"># 90-day time to death</span></span>
<span id="cb18-31"><a href="#cb18-31" aria-hidden="true" tabindex="-1"></a>    <span class="at">t_event =</span> <span class="fu">rexp</span>(n, <span class="fu">exp</span>(<span class="sc">-</span><span class="fl">6.9</span> <span class="sc">+</span> <span class="fl">0.72</span> <span class="sc">*</span> curb65 <span class="sc">+</span> <span class="fl">0.026</span> <span class="sc">*</span> (age <span class="sc">-</span> <span class="dv">68</span>) <span class="sc">+</span></span>
<span id="cb18-32"><a href="#cb18-32" aria-hidden="true" tabindex="-1"></a>                            <span class="fu">log</span>(<span class="fl">0.72</span>) <span class="sc">*</span> early_abx)),</span>
<span id="cb18-33"><a href="#cb18-33" aria-hidden="true" tabindex="-1"></a>    <span class="at">time    =</span> <span class="fu">pmin</span>(<span class="fu">round</span>(t_event), <span class="dv">90</span>),</span>
<span id="cb18-34"><a href="#cb18-34" aria-hidden="true" tabindex="-1"></a>    <span class="at">status  =</span> <span class="fu">as.integer</span>(t_event <span class="sc">&lt;=</span> <span class="dv">90</span>),</span>
<span id="cb18-35"><a href="#cb18-35" aria-hidden="true" tabindex="-1"></a>    <span class="at">timing  =</span> <span class="fu">factor</span>(early_abx, <span class="dv">0</span><span class="sc">:</span><span class="dv">1</span>,</span>
<span id="cb18-36"><a href="#cb18-36" aria-hidden="true" tabindex="-1"></a>                     <span class="fu">c</span>(<span class="st">"Antibiotics ≥ 4 h"</span>, <span class="st">"Antibiotics &lt; 4 h"</span>))</span>
<span id="cb18-37"><a href="#cb18-37" aria-hidden="true" tabindex="-1"></a>  ) <span class="sc">|&gt;</span></span>
<span id="cb18-38"><a href="#cb18-38" aria-hidden="true" tabindex="-1"></a>  <span class="fu">select</span>(<span class="sc">-</span>p_death, <span class="sc">-</span>t_event)</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
</details>
</div>
<p>Table 1 first, because you should always look before you estimate:</p>
<div class="cell" data-layout-align="center">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb19"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb19-1"><a href="#cb19-1" aria-hidden="true" tabindex="-1"></a><span class="fu">kk_table1</span>(cap,</span>
<span id="cb19-2"><a href="#cb19-2" aria-hidden="true" tabindex="-1"></a>          <span class="at">by =</span> <span class="st">"early_abx"</span>,</span>
<span id="cb19-3"><a href="#cb19-3" aria-hidden="true" tabindex="-1"></a>          <span class="at">variables =</span> <span class="fu">c</span>(<span class="st">"age"</span>, <span class="st">"sex"</span>, <span class="st">"curb65"</span>, <span class="st">"charlson"</span>, <span class="st">"smoker"</span>, <span class="st">"death30"</span>))</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-stdout">
<pre><code>#&gt; # A tibble: 13 × 5
#&gt;    Characteristic N     `0   N = 1,617`      `1   N = 1,383`      `p-value`
#&gt;    &lt;chr&gt;          &lt;chr&gt; &lt;chr&gt;                &lt;chr&gt;                &lt;chr&gt;    
#&gt;  1 __age__        3,000 65.00 (56.00, 75.00) 70.00 (61.00, 80.00) &lt;0.001   
#&gt;  2 __sex__        3,000 &lt;NA&gt;                 &lt;NA&gt;                 0.8      
#&gt;  3 Female         &lt;NA&gt;  756 (47%)            639 (46%)            &lt;NA&gt;     
#&gt;  4 Male           &lt;NA&gt;  861 (53%)            744 (54%)            &lt;NA&gt;     
#&gt;  5 __curb65__     3,000 &lt;NA&gt;                 &lt;NA&gt;                 &lt;0.001   
#&gt;  6 0              &lt;NA&gt;  757 (47%)            205 (15%)            &lt;NA&gt;     
#&gt;  7 1              &lt;NA&gt;  624 (39%)            555 (40%)            &lt;NA&gt;     
#&gt;  8 2              &lt;NA&gt;  210 (13%)            446 (32%)            &lt;NA&gt;     
#&gt;  9 3              &lt;NA&gt;  23 (1.4%)            155 (11%)            &lt;NA&gt;     
#&gt; 10 4              &lt;NA&gt;  3 (0.2%)             22 (1.6%)            &lt;NA&gt;     
#&gt; 11 __charlson__   3,000 2.00 (1.00, 2.00)    2.00 (1.00, 3.00)    &lt;0.001   
#&gt; 12 __smoker__     3,000 531 (33%)            412 (30%)            0.073    
#&gt; 13 __death30__    3,000 161 (10.0%)          209 (15%)            &lt;0.001</code></pre>
</div>
</div>
<p>The imbalance is already visible in the <code>curb65</code> rows. Among patients treated later, 47 % had a CURB-65 of zero; among those treated within four hours, 15 % did. The two columns are not describing the same patients, which is exactly what the rest of this post has to deal with.</p>
</section>
<section id="the-estimate-that-would-get-published" class="level2">
<h2 class="anchored" data-anchor-id="the-estimate-that-would-get-published">3. The estimate that would get published</h2>
<div class="cell" data-layout-align="center">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb21"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb21-1"><a href="#cb21-1" aria-hidden="true" tabindex="-1"></a>crude <span class="ot">&lt;-</span> cap <span class="sc">|&gt;</span> <span class="fu">kk_twobytwo</span>(early_abx, death30)</span>
<span id="cb21-2"><a href="#cb21-2" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb21-3"><a href="#cb21-3" aria-hidden="true" tabindex="-1"></a>crude <span class="sc">|&gt;</span></span>
<span id="cb21-4"><a href="#cb21-4" aria-hidden="true" tabindex="-1"></a>  <span class="fu">filter</span>(Metric <span class="sc">%in%</span> <span class="fu">c</span>(<span class="st">"Odds Ratio"</span>, <span class="st">"Relative Risk"</span>, <span class="st">"Risk Difference"</span>,</span>
<span id="cb21-5"><a href="#cb21-5" aria-hidden="true" tabindex="-1"></a>                       <span class="st">"Risk in Exposed"</span>, <span class="st">"Risk in Unexposed"</span>, <span class="st">"NNH"</span>)) <span class="sc">|&gt;</span></span>
<span id="cb21-6"><a href="#cb21-6" aria-hidden="true" tabindex="-1"></a>  <span class="fu">select</span>(Metric, Estimate, Lower, Upper) <span class="sc">|&gt;</span></span>
<span id="cb21-7"><a href="#cb21-7" aria-hidden="true" tabindex="-1"></a>  <span class="fu">mutate_round</span>(<span class="dv">3</span>)</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-stdout">
<pre><code>#&gt; # A tibble: 6 × 4
#&gt;   Metric            Estimate  Lower  Upper
#&gt;   &lt;chr&gt;                &lt;dbl&gt;  &lt;dbl&gt;  &lt;dbl&gt;
#&gt; 1 Odds Ratio           1.61   1.29   2.00 
#&gt; 2 Relative Risk        1.52   1.25   1.84 
#&gt; 3 Risk Difference      0.052  0.028  0.075
#&gt; 4 Risk in Exposed      0.151 NA     NA    
#&gt; 5 Risk in Unexposed    0.1   NA     NA    
#&gt; 6 NNH                 19.4   13.3   36.1</code></pre>
</div>
</div>
<p>There it is. A relative risk of 1.52 (95% CI 1.25–1.84) — early antibiotics associated with a <strong>50 % higher</strong> 30-day mortality, comfortably significant, with a number-needed-to-harm of about 19. Written up carelessly, this is a paper. Written up carelessly by someone with a hypothesis, it is a paper with a mechanism section.</p>
<p>Two things about <code>kk_twobytwo()</code> are worth noticing. It returns nineteen quantities, not one — odds ratio, risk ratio, risk difference, attributable and preventable fractions, phi, Yule’s Q and Y, Cohen’s h, excess cases per 1,000, NNH — because the choice between them is yours and the arithmetic should not be a reason to avoid reporting the right one. And it returns them as a <strong>tibble</strong>, which is why the line above could <code>filter()</code> and <code>select()</code> it like any other data frame, and why §5 can collect this estimate and three others into a single figure without a number being retyped. (<code>kk_risk_plot()</code> will take the whole object and draw a forest plot in one call; I use it while exploring, but it builds its own theme, so the figures below are drawn with <code>kkplot()</code> instead.)</p>
</section>
<section id="group_by-is-the-whole-design" class="level2">
<h2 class="anchored" data-anchor-id="group_by-is-the-whole-design">4. <code>group_by()</code> is the whole design</h2>
<p>Here is where the package’s core convention earns its keep. Every analysis function honours <code>dplyr::group_by()</code>: pipe in a grouped data frame and the analysis runs once per group, with the grouping columns prefixed to the result. Not a loop, not a <code>lapply()</code> with <code>bind_rows()</code> — the same function call, one verb longer.</p>
<div class="cell" data-layout-align="center">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb23"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb23-1"><a href="#cb23-1" aria-hidden="true" tabindex="-1"></a>cap <span class="sc">|&gt;</span></span>
<span id="cb23-2"><a href="#cb23-2" aria-hidden="true" tabindex="-1"></a>  <span class="fu">group_by</span>(curb65) <span class="sc">|&gt;</span></span>
<span id="cb23-3"><a href="#cb23-3" aria-hidden="true" tabindex="-1"></a>  <span class="fu">kk_twobytwo</span>(early_abx, death30) <span class="sc">|&gt;</span></span>
<span id="cb23-4"><a href="#cb23-4" aria-hidden="true" tabindex="-1"></a>  <span class="fu">filter</span>(Metric <span class="sc">==</span> <span class="st">"Relative Risk"</span>) <span class="sc">|&gt;</span></span>
<span id="cb23-5"><a href="#cb23-5" aria-hidden="true" tabindex="-1"></a>  <span class="fu">select</span>(curb65, Estimate, Lower, Upper, P_Value) <span class="sc">|&gt;</span></span>
<span id="cb23-6"><a href="#cb23-6" aria-hidden="true" tabindex="-1"></a>  <span class="fu">mutate_round</span>(<span class="dv">3</span>)</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-stdout">
<pre><code>#&gt; # A tibble: 5 × 5
#&gt;   curb65 Estimate Lower Upper P_Value
#&gt;    &lt;dbl&gt;    &lt;dbl&gt; &lt;dbl&gt; &lt;dbl&gt;   &lt;dbl&gt;
#&gt; 1      0    0.369 0.114 1.20    0.081
#&gt; 2      1    0.66  0.447 0.975   0.035
#&gt; 3      2    0.748 0.549 1.02    0.068
#&gt; 4      3    0.721 0.496 1.05    0.127
#&gt; 5      4    0.909 0.797 1.04    0.586</code></pre>
</div>
</div>
<p>Every stratum-specific risk ratio is <strong>below one</strong>. The crude estimate was above 1.5. This is Simpson’s paradox arriving in a form that will actually turn up in your data, and one added line of <code>dplyr</code> is what exposed it.</p>
<p>The pooled version, with the test for whether pooling was legitimate in the first place:</p>
<div class="cell" data-layout-align="center">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb25"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb25-1"><a href="#cb25-1" aria-hidden="true" tabindex="-1"></a>st <span class="ot">&lt;-</span> cap <span class="sc">|&gt;</span> <span class="fu">kk_stratified_2x2</span>(early_abx, death30, curb65)</span>
<span id="cb25-2"><a href="#cb25-2" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb25-3"><a href="#cb25-3" aria-hidden="true" tabindex="-1"></a>st<span class="sc">$</span>pooled_rr</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-stdout">
<pre><code>#&gt; # A tibble: 1 × 4
#&gt;   Estimate Lower Upper Method         
#&gt;      &lt;dbl&gt; &lt;dbl&gt; &lt;dbl&gt; &lt;chr&gt;          
#&gt; 1    0.690 0.561 0.849 Mantel-Haenszel</code></pre>
</div>
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb27"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb27-1"><a href="#cb27-1" aria-hidden="true" tabindex="-1"></a>st<span class="sc">$</span>breslow_day</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-stdout">
<pre><code>#&gt; # A tibble: 1 × 5
#&gt;   Test        Statistic    DF P_Value Interpretation        
#&gt;   &lt;chr&gt;           &lt;dbl&gt; &lt;dbl&gt;   &lt;dbl&gt; &lt;chr&gt;                 
#&gt; 1 Breslow-Day      1.52     4   0.823 ORs appear homogeneous</code></pre>
</div>
</div>
<p>Mantel–Haenszel pooled risk ratio: 0.69 (95% CI 0.56–0.85). The truth I wrote into the generator was 0.70. Breslow–Day gives no evidence of heterogeneity across strata (<em>p</em> = 0.82), so a single pooled number is a fair summary here — which is a claim the function makes me check rather than assume.</p>
<div class="cell" data-layout-align="center">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb29"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb29-1"><a href="#cb29-1" aria-hidden="true" tabindex="-1"></a>plot_df <span class="ot">&lt;-</span> cap <span class="sc">|&gt;</span></span>
<span id="cb29-2"><a href="#cb29-2" aria-hidden="true" tabindex="-1"></a>  <span class="fu">group_by</span>(curb65, timing) <span class="sc">|&gt;</span></span>
<span id="cb29-3"><a href="#cb29-3" aria-hidden="true" tabindex="-1"></a>  <span class="fu">summarise</span>(<span class="at">n =</span> <span class="fu">n</span>(), <span class="at">deaths =</span> <span class="fu">sum</span>(death30), <span class="at">.groups =</span> <span class="st">"drop"</span>) <span class="sc">|&gt;</span></span>
<span id="cb29-4"><a href="#cb29-4" aria-hidden="true" tabindex="-1"></a>  <span class="fu">mutate</span>(<span class="at">risk =</span> deaths <span class="sc">/</span> n,</span>
<span id="cb29-5"><a href="#cb29-5" aria-hidden="true" tabindex="-1"></a>         <span class="at">lo   =</span> <span class="fu">qbeta</span>(.<span class="dv">025</span>, deaths, n <span class="sc">-</span> deaths <span class="sc">+</span> <span class="dv">1</span>),</span>
<span id="cb29-6"><a href="#cb29-6" aria-hidden="true" tabindex="-1"></a>         <span class="at">hi   =</span> <span class="fu">qbeta</span>(.<span class="dv">975</span>, deaths <span class="sc">+</span> <span class="dv">1</span>, n <span class="sc">-</span> deaths)) <span class="sc">|&gt;</span></span>
<span id="cb29-7"><a href="#cb29-7" aria-hidden="true" tabindex="-1"></a>  <span class="fu">filter</span>(curb65 <span class="sc">&lt;=</span> <span class="dv">3</span>)</span>
<span id="cb29-8"><a href="#cb29-8" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb29-9"><a href="#cb29-9" aria-hidden="true" tabindex="-1"></a><span class="fu">kkplot</span>(plot_df, <span class="fu">aes</span>(curb65, risk, <span class="at">colour =</span> timing)) <span class="sc">+</span></span>
<span id="cb29-10"><a href="#cb29-10" aria-hidden="true" tabindex="-1"></a>  <span class="fu">geom_line</span>(<span class="at">linewidth =</span> .<span class="dv">8</span>) <span class="sc">+</span></span>
<span id="cb29-11"><a href="#cb29-11" aria-hidden="true" tabindex="-1"></a>  <span class="fu">geom_pointrange</span>(<span class="fu">aes</span>(<span class="at">ymin =</span> lo, <span class="at">ymax =</span> hi), <span class="at">size =</span> .<span class="dv">5</span>) <span class="sc">+</span></span>
<span id="cb29-12"><a href="#cb29-12" aria-hidden="true" tabindex="-1"></a>  <span class="fu">scale_color_kk</span>() <span class="sc">+</span></span>
<span id="cb29-13"><a href="#cb29-13" aria-hidden="true" tabindex="-1"></a>  <span class="fu">scale_y_continuous</span>(<span class="at">labels =</span> <span class="fu">label_percent</span>(<span class="dv">1</span>)) <span class="sc">+</span></span>
<span id="cb29-14"><a href="#cb29-14" aria-hidden="true" tabindex="-1"></a>  <span class="fu">labs</span>(<span class="at">x =</span> <span class="st">"CURB-65 score"</span>, <span class="at">y =</span> <span class="st">"30-day mortality"</span>, <span class="at">colour =</span> <span class="cn">NULL</span>,</span>
<span id="cb29-15"><a href="#cb29-15" aria-hidden="true" tabindex="-1"></a>       <span class="at">title =</span> <span class="st">"Within every severity stratum, early antibiotics do better"</span>,</span>
<span id="cb29-16"><a href="#cb29-16" aria-hidden="true" tabindex="-1"></a>       <span class="at">subtitle =</span> <span class="st">"Yet the crude comparison across strata says the opposite"</span>) <span class="sc">+</span></span>
<span id="cb29-17"><a href="#cb29-17" aria-hidden="true" tabindex="-1"></a>  <span class="fu">theme</span>(<span class="at">legend.position =</span> <span class="st">"top"</span>)</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output-display">
<div id="fig-confounding" class="quarto-float quarto-figure quarto-figure-center anchored" data-fig-align="center">
<figure class="quarto-float quarto-float-fig figure">
<div aria-describedby="fig-confounding-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
<img src="kkstatfun-worked-example_files/figure-html/fig-confounding-1.png" class="img-fluid quarto-figure quarto-figure-center figure-img" style="width:100.0%">
</div>
<figcaption class="quarto-float-caption-bottom quarto-float-caption quarto-float-fig" id="fig-confounding-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
Figure&nbsp;2: The same data twice. Within each severity stratum early treatment does better; pooled across strata it appears to do worse, because severity drives both treatment speed and death.
</figcaption>
</figure>
</div>
</div>
</div>
<p><code>kkplot()</code> is a drop-in replacement for <code>ggplot()</code> that adds capped axes and, with <code>rangeframe = TRUE</code>, Tufte’s range frame. The font and the palette are already set from §1, so the figure needs no styling code at all — <code>scale_color_kk()</code> and nothing else.</p>
</section>
<section id="adjusted-weighted-and-doubly-robust" class="level2">
<h2 class="anchored" data-anchor-id="adjusted-weighted-and-doubly-robust">5. Adjusted, weighted, and doubly robust</h2>
<p>Stratification handles one confounder. For several at once there are three routes, with different assumptions and, the point, one interface.</p>
<p><strong>Regression, on the right scale.</strong> For a common binary outcome the odds ratio overstates the risk ratio, so <code>kk_rr_reg()</code> fits modified Poisson regression with robust standard errors (Zou 2004) and returns risk ratios directly. It runs the univariate models alongside the multivariable one, so confounding is visible as a shift between rows rather than something you have to reconstruct from two printouts:</p>
<div class="cell" data-layout-align="center">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb30"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb30-1"><a href="#cb30-1" aria-hidden="true" tabindex="-1"></a>rr <span class="ot">&lt;-</span> <span class="fu">kk_rr_reg</span>(cap, <span class="st">"death30"</span>,</span>
<span id="cb30-2"><a href="#cb30-2" aria-hidden="true" tabindex="-1"></a>                <span class="fu">c</span>(<span class="st">"early_abx"</span>, <span class="st">"curb65"</span>, <span class="st">"age"</span>, <span class="st">"smoker"</span>, <span class="st">"charlson"</span>))</span>
<span id="cb30-3"><a href="#cb30-3" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb30-4"><a href="#cb30-4" aria-hidden="true" tabindex="-1"></a>rr <span class="sc">|&gt;</span></span>
<span id="cb30-5"><a href="#cb30-5" aria-hidden="true" tabindex="-1"></a>  <span class="fu">select</span>(term, model_type, risk_ratio, conf.low, conf.high) <span class="sc">|&gt;</span></span>
<span id="cb30-6"><a href="#cb30-6" aria-hidden="true" tabindex="-1"></a>  <span class="fu">mutate_round</span>(<span class="dv">3</span>)</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-stdout">
<pre><code>#&gt; # A tibble: 10 × 5
#&gt;    term      model_type    risk_ratio conf.low conf.high
#&gt;    &lt;chr&gt;     &lt;chr&gt;              &lt;dbl&gt;    &lt;dbl&gt;     &lt;dbl&gt;
#&gt;  1 early_abx univariate         1.52     1.25      1.84 
#&gt;  2 curb65    univariate         2.31     2.14      2.49 
#&gt;  3 age       univariate         1.04     1.03      1.05 
#&gt;  4 smoker    univariate         1.15     0.945     1.41 
#&gt;  5 charlson  univariate         1.24     1.16      1.31 
#&gt;  6 early_abx multivariable      0.684    0.565     0.828
#&gt;  7 curb65    multivariable      2.15     1.97      2.34 
#&gt;  8 age       multivariable      1.02     1.02      1.03 
#&gt;  9 smoker    multivariable      1.09     0.906     1.30 
#&gt; 10 charlson  multivariable      1.13     1.06      1.19</code></pre>
</div>
</div>
<p>The <code>early_abx</code> row moves from 1.52 univariately to 0.68 adjusted. That reversal is the entire post.</p>
<p><strong>Weighting.</strong> Before weighting anything, look at the imbalance you are trying to remove:</p>
<div class="cell" data-layout-align="center">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb32"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb32-1"><a href="#cb32-1" aria-hidden="true" tabindex="-1"></a>cap <span class="sc">|&gt;</span></span>
<span id="cb32-2"><a href="#cb32-2" aria-hidden="true" tabindex="-1"></a>  <span class="fu">select</span>(early_abx, age, sex, smoker, charlson, curb65) <span class="sc">|&gt;</span></span>
<span id="cb32-3"><a href="#cb32-3" aria-hidden="true" tabindex="-1"></a>  <span class="fu">kk_smd</span>(<span class="at">treatment =</span> <span class="st">"early_abx"</span>)</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-stdout">
<pre><code>#&gt; # A tibble: 5 × 8
#&gt;   variable level type        group1 group2     smd abs_smd imbalanced
#&gt; * &lt;chr&gt;    &lt;chr&gt; &lt;chr&gt;        &lt;dbl&gt;  &lt;dbl&gt;   &lt;dbl&gt;   &lt;dbl&gt; &lt;lgl&gt;     
#&gt; 1 age      &lt;NA&gt;  continuous  65.6   70.7   -0.371   0.371  TRUE      
#&gt; 2 sex      Male  categorical  0.532  0.538 -0.0110  0.0110 FALSE     
#&gt; 3 smoker   1     categorical  0.328  0.298  0.0658  0.0658 FALSE     
#&gt; 4 charlson &lt;NA&gt;  continuous   1.70   1.96  -0.193   0.193  TRUE      
#&gt; 5 curb65   &lt;NA&gt;  continuous   0.696  1.45  -0.883   0.883  TRUE</code></pre>
</div>
</div>
<p>A standardised mean difference of 0.88 on <code>curb65</code> — nine times the conventional 0.1 threshold — is the numerical statement of the problem. Then inverse-probability-of-treatment weighting, with stabilised weights and robust confidence intervals:</p>
<div class="cell" data-layout-align="center">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb34"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb34-1"><a href="#cb34-1" aria-hidden="true" tabindex="-1"></a>ipw <span class="ot">&lt;-</span> <span class="fu">kk_iptw</span>(cap, <span class="st">"early_abx"</span>, <span class="st">"death30"</span>,</span>
<span id="cb34-2"><a href="#cb34-2" aria-hidden="true" tabindex="-1"></a>               <span class="at">covariates =</span> <span class="fu">c</span>(<span class="st">"age"</span>, <span class="st">"sex"</span>, <span class="st">"smoker"</span>, <span class="st">"charlson"</span>, <span class="st">"curb65"</span>))</span>
<span id="cb34-3"><a href="#cb34-3" aria-hidden="true" tabindex="-1"></a>ipw <span class="sc">|&gt;</span> <span class="fu">mutate_round</span>(<span class="dv">4</span>)</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-stdout">
<pre><code>#&gt; # A tibble: 2 × 7
#&gt;   estimand metric          estimate conf.low conf.high p.value conf.level
#&gt;   &lt;chr&gt;    &lt;chr&gt;              &lt;dbl&gt;    &lt;dbl&gt;     &lt;dbl&gt;   &lt;dbl&gt;      &lt;dbl&gt;
#&gt; 1 ATE      Risk difference  -0.0588  -0.0926    -0.025  0.0006       0.95
#&gt; 2 ATE      Risk ratio        0.639    0.505      0.808  0.0002       0.95</code></pre>
</div>
</div>
<p><strong>Double robustness.</strong> Targeted maximum likelihood estimation fits both the outcome model and the treatment model and remains consistent if <em>either</em> is right:</p>
<div class="cell" data-layout-align="center">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb36"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb36-1"><a href="#cb36-1" aria-hidden="true" tabindex="-1"></a>tm <span class="ot">&lt;-</span> <span class="fu">kk_tmle</span>(cap,</span>
<span id="cb36-2"><a href="#cb36-2" aria-hidden="true" tabindex="-1"></a>              <span class="at">outcome    =</span> <span class="st">"death30"</span>,</span>
<span id="cb36-3"><a href="#cb36-3" aria-hidden="true" tabindex="-1"></a>              <span class="at">treatment  =</span> <span class="st">"early_abx"</span>,</span>
<span id="cb36-4"><a href="#cb36-4" aria-hidden="true" tabindex="-1"></a>              <span class="at">covariates =</span> <span class="fu">c</span>(<span class="st">"age"</span>, <span class="st">"sex"</span>, <span class="st">"smoker"</span>, <span class="st">"charlson"</span>, <span class="st">"curb65"</span>))</span>
<span id="cb36-5"><a href="#cb36-5" aria-hidden="true" tabindex="-1"></a>tm <span class="sc">|&gt;</span> <span class="fu">mutate_round</span>(<span class="dv">4</span>)</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-stdout">
<pre><code>#&gt; # A tibble: 1 × 8
#&gt;       ate std.error conf.low conf.high p.value   ey1   ey0 conf.level
#&gt;     &lt;dbl&gt;     &lt;dbl&gt;    &lt;dbl&gt;     &lt;dbl&gt;   &lt;dbl&gt; &lt;dbl&gt; &lt;dbl&gt;      &lt;dbl&gt;
#&gt; 1 -0.0488    0.0124  -0.0731   -0.0246  0.0001 0.104 0.153       0.95</code></pre>
</div>
</div>
<p>The counterfactual risks come back as <code>ey1</code> and <code>ey0</code>: 10.4 % if everyone had been treated early, 15.3 % if nobody had — an absolute difference of 4.9 percentage points, which <code>kk_nnt()</code> turns into the number a clinician actually wants:</p>
<div class="cell" data-layout-align="center">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb38"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb38-1"><a href="#cb38-1" aria-hidden="true" tabindex="-1"></a><span class="fu">kk_nnt</span>(<span class="at">estimate =</span> tm<span class="sc">$</span>ate, <span class="at">type =</span> <span class="st">"risk_diff"</span>,</span>
<span id="cb38-2"><a href="#cb38-2" aria-hidden="true" tabindex="-1"></a>       <span class="at">ci_low =</span> tm<span class="sc">$</span>conf.low, <span class="at">ci_high =</span> tm<span class="sc">$</span>conf.high)</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-stdout">
<pre><code>#&gt; # A tibble: 1 × 6
#&gt;   Metric Estimate Lower Upper RD_Estimate Note       
#&gt;   &lt;chr&gt;     &lt;dbl&gt; &lt;dbl&gt; &lt;dbl&gt;       &lt;dbl&gt; &lt;chr&gt;      
#&gt; 1 NNT        20.5  13.7  40.7     -0.0488 Significant</code></pre>
</div>
</div>
<p>Because every one of those functions returned a tibble, collecting them into one figure is a <code>bind_rows()</code> rather than a transcription exercise — and the figure is the argument of this whole post:</p>
<div class="cell" data-layout-align="center">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb40"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb40-1"><a href="#cb40-1" aria-hidden="true" tabindex="-1"></a>crude_rr <span class="ot">&lt;-</span> crude <span class="sc">|&gt;</span> <span class="fu">filter</span>(Metric <span class="sc">==</span> <span class="st">"Relative Risk"</span>)</span>
<span id="cb40-2"><a href="#cb40-2" aria-hidden="true" tabindex="-1"></a>mh_rr    <span class="ot">&lt;-</span> st<span class="sc">$</span>pooled_rr</span>
<span id="cb40-3"><a href="#cb40-3" aria-hidden="true" tabindex="-1"></a>pois_rr  <span class="ot">&lt;-</span> rr <span class="sc">|&gt;</span> <span class="fu">filter</span>(term <span class="sc">==</span> <span class="st">"early_abx"</span>, model_type <span class="sc">==</span> <span class="st">"multivariable"</span>)</span>
<span id="cb40-4"><a href="#cb40-4" aria-hidden="true" tabindex="-1"></a>ipw_rr   <span class="ot">&lt;-</span> ipw <span class="sc">|&gt;</span> <span class="fu">filter</span>(metric <span class="sc">==</span> <span class="st">"Risk ratio"</span>)</span>
<span id="cb40-5"><a href="#cb40-5" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb40-6"><a href="#cb40-6" aria-hidden="true" tabindex="-1"></a>estimates <span class="ot">&lt;-</span> <span class="fu">tibble</span>(</span>
<span id="cb40-7"><a href="#cb40-7" aria-hidden="true" tabindex="-1"></a>  <span class="at">method =</span> <span class="fu">c</span>(<span class="st">"Crude 2×2"</span>, <span class="st">"Mantel–Haenszel"</span>, <span class="st">"Modified Poisson"</span>, <span class="st">"IPTW (ATE)"</span>),</span>
<span id="cb40-8"><a href="#cb40-8" aria-hidden="true" tabindex="-1"></a>  <span class="at">fn     =</span> <span class="fu">c</span>(<span class="st">"kk_twobytwo()"</span>, <span class="st">"kk_stratified_2x2()"</span>, <span class="st">"kk_rr_reg()"</span>, <span class="st">"kk_iptw()"</span>),</span>
<span id="cb40-9"><a href="#cb40-9" aria-hidden="true" tabindex="-1"></a>  <span class="at">rr     =</span> <span class="fu">c</span>(crude_rr<span class="sc">$</span>Estimate, mh_rr<span class="sc">$</span>Estimate, pois_rr<span class="sc">$</span>risk_ratio, ipw_rr<span class="sc">$</span>estimate),</span>
<span id="cb40-10"><a href="#cb40-10" aria-hidden="true" tabindex="-1"></a>  <span class="at">lo     =</span> <span class="fu">c</span>(crude_rr<span class="sc">$</span>Lower,    mh_rr<span class="sc">$</span>Lower,    pois_rr<span class="sc">$</span>conf.low,   ipw_rr<span class="sc">$</span>conf.low),</span>
<span id="cb40-11"><a href="#cb40-11" aria-hidden="true" tabindex="-1"></a>  <span class="at">hi     =</span> <span class="fu">c</span>(crude_rr<span class="sc">$</span>Upper,    mh_rr<span class="sc">$</span>Upper,    pois_rr<span class="sc">$</span>conf.high,  ipw_rr<span class="sc">$</span>conf.high)</span>
<span id="cb40-12"><a href="#cb40-12" aria-hidden="true" tabindex="-1"></a>) <span class="sc">|&gt;</span></span>
<span id="cb40-13"><a href="#cb40-13" aria-hidden="true" tabindex="-1"></a>  <span class="fu">mutate</span>(<span class="at">label  =</span> <span class="fu">paste0</span>(method, <span class="st">"</span><span class="sc">\n</span><span class="st">"</span>, fn),</span>
<span id="cb40-14"><a href="#cb40-14" aria-hidden="true" tabindex="-1"></a>         <span class="at">label  =</span> <span class="fu">factor</span>(label, <span class="at">levels =</span> <span class="fu">rev</span>(label)),</span>
<span id="cb40-15"><a href="#cb40-15" aria-hidden="true" tabindex="-1"></a>         <span class="at">honest =</span> rr <span class="sc">&lt;</span> <span class="dv">1</span>)</span>
<span id="cb40-16"><a href="#cb40-16" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb40-17"><a href="#cb40-17" aria-hidden="true" tabindex="-1"></a><span class="fu">kkplot</span>(estimates, <span class="fu">aes</span>(rr, label, <span class="at">colour =</span> honest)) <span class="sc">+</span></span>
<span id="cb40-18"><a href="#cb40-18" aria-hidden="true" tabindex="-1"></a>  <span class="fu">geom_vline</span>(<span class="at">xintercept =</span> <span class="dv">1</span>, <span class="at">colour =</span> <span class="st">"grey60"</span>) <span class="sc">+</span></span>
<span id="cb40-19"><a href="#cb40-19" aria-hidden="true" tabindex="-1"></a>  <span class="fu">geom_vline</span>(<span class="at">xintercept =</span> <span class="fl">0.70</span>, <span class="at">linetype =</span> <span class="st">"dashed"</span>, <span class="at">colour =</span> <span class="st">"#F77F00"</span>,</span>
<span id="cb40-20"><a href="#cb40-20" aria-hidden="true" tabindex="-1"></a>             <span class="at">linewidth =</span> .<span class="dv">8</span>) <span class="sc">+</span></span>
<span id="cb40-21"><a href="#cb40-21" aria-hidden="true" tabindex="-1"></a>  <span class="fu">annotate</span>(<span class="st">"text"</span>, <span class="at">x =</span> <span class="fl">0.70</span>, <span class="at">y =</span> <span class="fu">levels</span>(estimates<span class="sc">$</span>label)[<span class="dv">4</span>], <span class="at">vjust =</span> <span class="sc">-</span><span class="fl">1.4</span>,</span>
<span id="cb40-22"><a href="#cb40-22" aria-hidden="true" tabindex="-1"></a>           <span class="at">hjust =</span> <span class="fl">1.05</span>, <span class="at">label =</span> <span class="st">"simulated truth"</span>, <span class="at">size =</span> <span class="fl">3.5</span>,</span>
<span id="cb40-23"><a href="#cb40-23" aria-hidden="true" tabindex="-1"></a>           <span class="at">colour =</span> <span class="st">"#B85E00"</span>, <span class="at">family =</span> myfont) <span class="sc">+</span></span>
<span id="cb40-24"><a href="#cb40-24" aria-hidden="true" tabindex="-1"></a>  <span class="fu">geom_pointrange</span>(<span class="fu">aes</span>(<span class="at">xmin =</span> lo, <span class="at">xmax =</span> hi), <span class="at">size =</span> .<span class="dv">55</span>, <span class="at">linewidth =</span> .<span class="dv">8</span>) <span class="sc">+</span></span>
<span id="cb40-25"><a href="#cb40-25" aria-hidden="true" tabindex="-1"></a>  <span class="fu">scale_colour_manual</span>(<span class="at">values =</span> <span class="fu">c</span>(<span class="st">`</span><span class="at">TRUE</span><span class="st">`</span> <span class="ot">=</span> <span class="st">"#003049"</span>, <span class="st">`</span><span class="at">FALSE</span><span class="st">`</span> <span class="ot">=</span> <span class="st">"#D62828"</span>),</span>
<span id="cb40-26"><a href="#cb40-26" aria-hidden="true" tabindex="-1"></a>                      <span class="at">guide =</span> <span class="st">"none"</span>) <span class="sc">+</span></span>
<span id="cb40-27"><a href="#cb40-27" aria-hidden="true" tabindex="-1"></a>  <span class="fu">scale_x_continuous</span>(<span class="at">transform =</span> <span class="st">"log"</span>, <span class="at">breaks =</span> <span class="fu">c</span>(<span class="fl">0.5</span>, <span class="fl">0.7</span>, <span class="dv">1</span>, <span class="fl">1.5</span>, <span class="dv">2</span>)) <span class="sc">+</span></span>
<span id="cb40-28"><a href="#cb40-28" aria-hidden="true" tabindex="-1"></a>  <span class="fu">coord_cartesian</span>(<span class="at">clip =</span> <span class="st">"off"</span>) <span class="sc">+</span></span>
<span id="cb40-29"><a href="#cb40-29" aria-hidden="true" tabindex="-1"></a>  <span class="fu">labs</span>(<span class="at">x =</span> <span class="st">"Risk ratio (log scale)"</span>, <span class="at">y =</span> <span class="cn">NULL</span>,</span>
<span id="cb40-30"><a href="#cb40-30" aria-hidden="true" tabindex="-1"></a>       <span class="at">title =</span> <span class="st">"One contrast, four estimators, one truth"</span>,</span>
<span id="cb40-31"><a href="#cb40-31" aria-hidden="true" tabindex="-1"></a>       <span class="at">subtitle =</span> <span class="st">"Only the crude estimate lands on the wrong side of the null"</span>) <span class="sc">+</span></span>
<span id="cb40-32"><a href="#cb40-32" aria-hidden="true" tabindex="-1"></a>  <span class="fu">theme</span>(<span class="at">plot.margin =</span> <span class="fu">margin</span>(<span class="dv">18</span>, <span class="dv">10</span>, <span class="dv">5</span>, <span class="dv">5</span>))</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output-display">
<div id="fig-summary" class="quarto-float quarto-figure quarto-figure-center anchored" data-fig-align="center">
<figure class="quarto-float quarto-float-fig figure">
<div aria-describedby="fig-summary-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
<img src="kkstatfun-worked-example_files/figure-html/fig-summary-1.png" class="img-fluid quarto-figure quarto-figure-center figure-img" style="width:100.0%">
</div>
<figcaption class="quarto-float-caption-bottom quarto-float-caption quarto-float-fig" id="fig-summary-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
Figure&nbsp;3: Four estimators of the same causal contrast, against the risk ratio of 0.70 written into the data generator. TMLE is not shown because it returns a risk difference; its implied ratio is ey1/ey0 = 0.68.
</figcaption>
</figure>
</div>
</div>
</div>
<div class="callout callout-style-default callout-important callout-titled">
<div class="callout-header d-flex align-content-center">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-title-container flex-fill">
<span class="screen-reader-only">Important</span>What the package cannot do
</div>
</div>
<div class="callout-body-container callout-body">
<p>All of §5 assumes I measured the confounders that matter, and in this dataset I did — because I created them. In a real cohort that assumption is untestable, and no amount of double robustness rescues you from a confounder nobody recorded. That is not a limitation of the software; it is a limitation of the design, and the honest move is to say so in the paper. When the treatment was switched on by a <em>rule</em> rather than by a clinician, §8 gets you an estimate that does not need the assumption at all.</p>
</div>
</div>
</section>
<section id="diagnostics-validating-a-marker" class="level2">
<h2 class="anchored" data-anchor-id="diagnostics-validating-a-marker">6. Diagnostics: validating a marker</h2>
<p>Different question, same grammar. Procalcitonin as a marker of bacterial aetiology:</p>
<div class="cell" data-layout-align="center">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb41"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb41-1"><a href="#cb41-1" aria-hidden="true" tabindex="-1"></a>cap <span class="sc">|&gt;</span> <span class="fu">kk_roc</span>(bacterial, pct) <span class="sc">|&gt;</span> <span class="fu">mutate_round</span>(<span class="dv">3</span>)</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-stdout">
<pre><code>#&gt; # A tibble: 1 × 11
#&gt;     auc auc_low auc_high youden_j optimal_threshold sensitivity specificity
#&gt;   &lt;dbl&gt;   &lt;dbl&gt;    &lt;dbl&gt;    &lt;dbl&gt;             &lt;dbl&gt;       &lt;dbl&gt;       &lt;dbl&gt;
#&gt; 1 0.898   0.887    0.909    0.625              1.68       0.767       0.858
#&gt;     ppv   npv     n conf.level
#&gt;   &lt;dbl&gt; &lt;dbl&gt; &lt;dbl&gt;      &lt;dbl&gt;
#&gt; 1 0.847 0.782  3000       0.95</code></pre>
</div>
</div>
<p>AUC with a DeLong interval, the Youden-optimal cut-off, and the sensitivity, specificity, PPV and NPV <em>at that cut-off</em>, in one row. And because the function is grouped-data-aware, discrimination across severity strata is the same call plus one line:</p>
<div class="cell" data-layout-align="center">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb43"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb43-1"><a href="#cb43-1" aria-hidden="true" tabindex="-1"></a>cap <span class="sc">|&gt;</span></span>
<span id="cb43-2"><a href="#cb43-2" aria-hidden="true" tabindex="-1"></a>  <span class="fu">group_by</span>(curb65) <span class="sc">|&gt;</span></span>
<span id="cb43-3"><a href="#cb43-3" aria-hidden="true" tabindex="-1"></a>  <span class="fu">kk_roc</span>(bacterial, pct) <span class="sc">|&gt;</span></span>
<span id="cb43-4"><a href="#cb43-4" aria-hidden="true" tabindex="-1"></a>  <span class="fu">select</span>(curb65, auc, auc_low, auc_high, n) <span class="sc">|&gt;</span></span>
<span id="cb43-5"><a href="#cb43-5" aria-hidden="true" tabindex="-1"></a>  <span class="fu">mutate_round</span>(<span class="dv">3</span>)</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-stdout">
<pre><code>#&gt; # A tibble: 5 × 5
#&gt;   curb65   auc auc_low auc_high     n
#&gt;    &lt;dbl&gt; &lt;dbl&gt;   &lt;dbl&gt;    &lt;dbl&gt; &lt;dbl&gt;
#&gt; 1      0 0.889   0.869    0.91    962
#&gt; 2      1 0.894   0.876    0.912  1179
#&gt; 3      2 0.908   0.886    0.929   656
#&gt; 4      3 0.9     0.855    0.946   178
#&gt; 5      4 0.984   0.946    1        25</code></pre>
</div>
</div>
<p>For a binary test rather than a continuous marker, <code>kk_diagnostic()</code> gives the confusion-matrix work-up:</p>
<div class="cell" data-layout-align="center">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb45"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb45-1"><a href="#cb45-1" aria-hidden="true" tabindex="-1"></a>cap <span class="sc">|&gt;</span> <span class="fu">kk_diagnostic</span>(bacterial, rapid_ag) <span class="sc">|&gt;</span> <span class="fu">mutate_round</span>(<span class="dv">3</span>)</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-stdout">
<pre><code>#&gt; # A tibble: 7 × 2
#&gt;   Metric      Value
#&gt;   &lt;chr&gt;       &lt;dbl&gt;
#&gt; 1 Sensitivity 0.75 
#&gt; 2 Specificity 0.928
#&gt; 3 PPV         0.914
#&gt; 4 NPV         0.784
#&gt; 5 Accuracy    0.838
#&gt; 6 F1 Score    0.824
#&gt; 7 AUC         0.839</code></pre>
</div>
</div>
<p>A model is not finished when it discriminates. <code>kk_reg()</code> auto-detects the outcome type and keeps the fitted object attached, so <code>kk_model()</code> hands it back for anything downstream instead of forcing a refit:</p>
<div class="cell" data-layout-align="center">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb47"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb47-1"><a href="#cb47-1" aria-hidden="true" tabindex="-1"></a>fit <span class="ot">&lt;-</span> <span class="fu">kk_reg</span>(cap <span class="sc">|&gt;</span> <span class="fu">mutate</span>(<span class="at">death30 =</span> <span class="fu">factor</span>(death30)),</span>
<span id="cb47-2"><a href="#cb47-2" aria-hidden="true" tabindex="-1"></a>              <span class="at">outcome    =</span> <span class="st">"death30"</span>,</span>
<span id="cb47-3"><a href="#cb47-3" aria-hidden="true" tabindex="-1"></a>              <span class="at">predictors =</span> <span class="fu">c</span>(<span class="st">"early_abx"</span>, <span class="st">"curb65"</span>, <span class="st">"age"</span>, <span class="st">"charlson"</span>))</span>
<span id="cb47-4"><a href="#cb47-4" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb47-5"><a href="#cb47-5" aria-hidden="true" tabindex="-1"></a>cap<span class="sc">$</span>p_death <span class="ot">&lt;-</span> <span class="fu">predict</span>(<span class="fu">kk_model</span>(fit), <span class="at">type =</span> <span class="st">"response"</span>)</span>
<span id="cb47-6"><a href="#cb47-6" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb47-7"><a href="#cb47-7" aria-hidden="true" tabindex="-1"></a><span class="fu">kk_calibration</span>(cap, death30, p_death) <span class="sc">|&gt;</span></span>
<span id="cb47-8"><a href="#cb47-8" aria-hidden="true" tabindex="-1"></a>  <span class="fu">select</span>(hl_chi2, df, p.value, oe_ratio, calib_slope, calib_intercept) <span class="sc">|&gt;</span></span>
<span id="cb47-9"><a href="#cb47-9" aria-hidden="true" tabindex="-1"></a>  <span class="fu">mutate_round</span>(<span class="dv">3</span>)</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-stdout">
<pre><code>#&gt; # A tibble: 1 × 6
#&gt;   hl_chi2    df p.value oe_ratio calib_slope calib_intercept
#&gt;     &lt;dbl&gt; &lt;dbl&gt;   &lt;dbl&gt;    &lt;dbl&gt;       &lt;dbl&gt;           &lt;dbl&gt;
#&gt; 1    7.71     8   0.462        1           1               0</code></pre>
</div>
</div>
<p>And discrimination plus calibration still does not tell you whether using the model helps anyone. Decision-curve analysis asks the clinical question directly — across the range of threshold probabilities at which a clinician would act, does the model beat treating everybody and treating nobody?</p>
<div class="cell" data-layout-align="center">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb49"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb49-1"><a href="#cb49-1" aria-hidden="true" tabindex="-1"></a><span class="fu">kk_decision_curve</span>(cap, death30, p_death, <span class="at">thresholds =</span> <span class="fu">seq</span>(.<span class="dv">05</span>, .<span class="dv">35</span>, .<span class="dv">05</span>)) <span class="sc">|&gt;</span></span>
<span id="cb49-2"><a href="#cb49-2" aria-hidden="true" tabindex="-1"></a>  tidyr<span class="sc">::</span><span class="fu">pivot_wider</span>(<span class="at">names_from =</span> strategy, <span class="at">values_from =</span> <span class="fu">c</span>(net_benefit, std_net_benefit)) <span class="sc">|&gt;</span></span>
<span id="cb49-3"><a href="#cb49-3" aria-hidden="true" tabindex="-1"></a>  <span class="fu">select</span>(threshold, net_benefit_Model, <span class="st">`</span><span class="at">net_benefit_Treat all</span><span class="st">`</span>) <span class="sc">|&gt;</span></span>
<span id="cb49-4"><a href="#cb49-4" aria-hidden="true" tabindex="-1"></a>  <span class="fu">mutate_round</span>(<span class="dv">4</span>)</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-stdout">
<pre><code>#&gt; # A tibble: 7 × 3
#&gt;   threshold net_benefit_Model `net_benefit_Treat all`
#&gt;       &lt;dbl&gt;             &lt;dbl&gt;                   &lt;dbl&gt;
#&gt; 1      0.05            0.0819                  0.0772
#&gt; 2      0.1             0.0595                  0.0259
#&gt; 3      0.15            0.048                  -0.0314
#&gt; 4      0.2             0.034                  -0.0958
#&gt; 5      0.25            0.0251                 -0.169 
#&gt; 6      0.3             0.0218                 -0.252 
#&gt; 7      0.35            0.0195                 -0.349</code></pre>
</div>
</div>
<p>Above a threshold of about 10 %, treat-all goes negative and the model does not. That is the sentence a clinical reader needs, and it is not derivable from an AUC.</p>
</section>
<section id="time-to-event" class="level2">
<h2 class="anchored" data-anchor-id="time-to-event">7. Time to event</h2>
<p><code>kk_survival_plot(cap, time, status, timing)</code> draws the curves, the confidence bands, the log-rank <em>p</em> and a risk table in a single call, and that is what I use while exploring. It is not what I put in a paper. The object it returns is a <code>ggsurvfit</code> composite that carries its own theme, so it ignores the font and palette set in §1, and its risk table has no rules to guide the eye across the row.</p>
<p>For the figure that ships, I rebuild it with <code>kkplot()</code> — which is simply <code>ggplot()</code> with capped axes, already wearing the house font and palette — and stack the risk table underneath with <code>patchwork</code>, with visible rules between the strata:</p>
<div class="cell" data-layout-align="center">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb51"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb51-1"><a href="#cb51-1" aria-hidden="true" tabindex="-1"></a>km   <span class="ot">&lt;-</span> <span class="fu">survfit</span>(<span class="fu">Surv</span>(time, status) <span class="sc">~</span> timing, <span class="at">data =</span> cap)</span>
<span id="cb51-2"><a href="#cb51-2" aria-hidden="true" tabindex="-1"></a>lvls <span class="ot">&lt;-</span> <span class="fu">levels</span>(cap<span class="sc">$</span>timing)</span>
<span id="cb51-3"><a href="#cb51-3" aria-hidden="true" tabindex="-1"></a>lab  <span class="ot">&lt;-</span> <span class="cf">function</span>(x) <span class="fu">factor</span>(<span class="fu">sub</span>(<span class="st">".*="</span>, <span class="st">""</span>, x), <span class="at">levels =</span> lvls)</span>
<span id="cb51-4"><a href="#cb51-4" aria-hidden="true" tabindex="-1"></a>xsc  <span class="ot">&lt;-</span> <span class="fu">scale_x_continuous</span>(<span class="at">breaks =</span> <span class="fu">seq</span>(<span class="dv">0</span>, <span class="dv">90</span>, <span class="dv">15</span>),</span>
<span id="cb51-5"><a href="#cb51-5" aria-hidden="true" tabindex="-1"></a>                           <span class="at">expand =</span> <span class="fu">expansion</span>(<span class="at">add =</span> <span class="fu">c</span>(<span class="dv">4</span>, <span class="dv">6</span>)))</span>
<span id="cb51-6"><a href="#cb51-6" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb51-7"><a href="#cb51-7" aria-hidden="true" tabindex="-1"></a><span class="co"># curves</span></span>
<span id="cb51-8"><a href="#cb51-8" aria-hidden="true" tabindex="-1"></a>km_dat <span class="ot">&lt;-</span> broom<span class="sc">::</span><span class="fu">tidy</span>(km) <span class="sc">|&gt;</span> <span class="fu">mutate</span>(<span class="at">timing =</span> <span class="fu">lab</span>(strata))</span>
<span id="cb51-9"><a href="#cb51-9" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb51-10"><a href="#cb51-10" aria-hidden="true" tabindex="-1"></a>p_km <span class="ot">&lt;-</span> <span class="fu">kkplot</span>(km_dat, <span class="fu">aes</span>(time, estimate, <span class="at">colour =</span> timing, <span class="at">fill =</span> timing)) <span class="sc">+</span></span>
<span id="cb51-11"><a href="#cb51-11" aria-hidden="true" tabindex="-1"></a>  <span class="fu">geom_ribbon</span>(<span class="fu">aes</span>(<span class="at">ymin =</span> conf.low, <span class="at">ymax =</span> conf.high), <span class="at">alpha =</span> .<span class="dv">15</span>, <span class="at">colour =</span> <span class="cn">NA</span>) <span class="sc">+</span></span>
<span id="cb51-12"><a href="#cb51-12" aria-hidden="true" tabindex="-1"></a>  <span class="fu">geom_step</span>(<span class="at">linewidth =</span> .<span class="dv">9</span>) <span class="sc">+</span></span>
<span id="cb51-13"><a href="#cb51-13" aria-hidden="true" tabindex="-1"></a>  <span class="fu">scale_color_kk</span>() <span class="sc">+</span> <span class="fu">scale_fill_kk</span>() <span class="sc">+</span> xsc <span class="sc">+</span></span>
<span id="cb51-14"><a href="#cb51-14" aria-hidden="true" tabindex="-1"></a>  <span class="fu">scale_y_continuous</span>(<span class="at">labels =</span> <span class="fu">label_percent</span>(<span class="dv">1</span>), <span class="at">limits =</span> <span class="fu">c</span>(.<span class="dv">7</span>, <span class="dv">1</span>)) <span class="sc">+</span></span>
<span id="cb51-15"><a href="#cb51-15" aria-hidden="true" tabindex="-1"></a>  <span class="fu">labs</span>(<span class="at">x =</span> <span class="cn">NULL</span>, <span class="at">y =</span> <span class="st">"Survival"</span>, <span class="at">colour =</span> <span class="cn">NULL</span>, <span class="at">fill =</span> <span class="cn">NULL</span>,</span>
<span id="cb51-16"><a href="#cb51-16" aria-hidden="true" tabindex="-1"></a>       <span class="at">title =</span> <span class="st">"Ninety-day survival by antibiotic timing"</span>,</span>
<span id="cb51-17"><a href="#cb51-17" aria-hidden="true" tabindex="-1"></a>       <span class="at">subtitle =</span> <span class="st">"Unadjusted — the same confounding as before, in survival form"</span>) <span class="sc">+</span></span>
<span id="cb51-18"><a href="#cb51-18" aria-hidden="true" tabindex="-1"></a>  <span class="fu">theme</span>(<span class="at">legend.position =</span> <span class="st">"top"</span>,</span>
<span id="cb51-19"><a href="#cb51-19" aria-hidden="true" tabindex="-1"></a>        <span class="at">axis.text.x =</span> <span class="fu">element_blank</span>(), <span class="at">axis.ticks.x =</span> <span class="fu">element_blank</span>())</span>
<span id="cb51-20"><a href="#cb51-20" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb51-21"><a href="#cb51-21" aria-hidden="true" tabindex="-1"></a><span class="co"># risk table</span></span>
<span id="cb51-22"><a href="#cb51-22" aria-hidden="true" tabindex="-1"></a>s   <span class="ot">&lt;-</span> <span class="fu">summary</span>(km, <span class="at">times =</span> <span class="fu">seq</span>(<span class="dv">0</span>, <span class="dv">90</span>, <span class="dv">15</span>))</span>
<span id="cb51-23"><a href="#cb51-23" aria-hidden="true" tabindex="-1"></a>tab <span class="ot">&lt;-</span> <span class="fu">tibble</span>(<span class="at">time =</span> s<span class="sc">$</span>time, <span class="at">timing =</span> <span class="fu">lab</span>(<span class="fu">as.character</span>(s<span class="sc">$</span>strata)),</span>
<span id="cb51-24"><a href="#cb51-24" aria-hidden="true" tabindex="-1"></a>              <span class="at">n_risk =</span> s<span class="sc">$</span>n.risk, <span class="at">n_event =</span> s<span class="sc">$</span>n.event) <span class="sc">|&gt;</span></span>
<span id="cb51-25"><a href="#cb51-25" aria-hidden="true" tabindex="-1"></a>  <span class="fu">group_by</span>(timing) <span class="sc">|&gt;</span></span>
<span id="cb51-26"><a href="#cb51-26" aria-hidden="true" tabindex="-1"></a>  <span class="fu">mutate</span>(<span class="at">deaths =</span> <span class="fu">cumsum</span>(n_event)) <span class="sc">|&gt;</span></span>
<span id="cb51-27"><a href="#cb51-27" aria-hidden="true" tabindex="-1"></a>  <span class="fu">ungroup</span>()</span>
<span id="cb51-28"><a href="#cb51-28" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb51-29"><a href="#cb51-29" aria-hidden="true" tabindex="-1"></a>p_tab <span class="ot">&lt;-</span> <span class="fu">kkplot</span>(tab, <span class="fu">aes</span>(time, <span class="fu">factor</span>(timing, <span class="at">levels =</span> <span class="fu">rev</span>(lvls)))) <span class="sc">+</span></span>
<span id="cb51-30"><a href="#cb51-30" aria-hidden="true" tabindex="-1"></a>  <span class="fu">geom_hline</span>(<span class="at">yintercept =</span> <span class="fu">c</span>(<span class="fl">0.5</span>, <span class="fl">1.5</span>, <span class="fl">2.5</span>), <span class="at">colour =</span> <span class="st">"grey80"</span>, <span class="at">linewidth =</span> .<span class="dv">4</span>) <span class="sc">+</span></span>
<span id="cb51-31"><a href="#cb51-31" aria-hidden="true" tabindex="-1"></a>  <span class="fu">geom_text</span>(<span class="fu">aes</span>(<span class="at">label =</span> <span class="fu">paste0</span>(n_risk, <span class="st">" ("</span>, deaths, <span class="st">")"</span>), <span class="at">colour =</span> timing),</span>
<span id="cb51-32"><a href="#cb51-32" aria-hidden="true" tabindex="-1"></a>            <span class="at">size =</span> <span class="fl">3.3</span>, <span class="at">family =</span> myfont, <span class="at">show.legend =</span> <span class="cn">FALSE</span>) <span class="sc">+</span></span>
<span id="cb51-33"><a href="#cb51-33" aria-hidden="true" tabindex="-1"></a>  <span class="fu">scale_color_kk</span>() <span class="sc">+</span> xsc <span class="sc">+</span></span>
<span id="cb51-34"><a href="#cb51-34" aria-hidden="true" tabindex="-1"></a>  <span class="fu">labs</span>(<span class="at">x =</span> <span class="st">"Days since admission"</span>, <span class="at">y =</span> <span class="cn">NULL</span>,</span>
<span id="cb51-35"><a href="#cb51-35" aria-hidden="true" tabindex="-1"></a>       <span class="at">caption =</span> <span class="st">"Number at risk (cumulative deaths)"</span>) <span class="sc">+</span></span>
<span id="cb51-36"><a href="#cb51-36" aria-hidden="true" tabindex="-1"></a>  <span class="fu">theme</span>(<span class="at">panel.grid =</span> <span class="fu">element_blank</span>(),</span>
<span id="cb51-37"><a href="#cb51-37" aria-hidden="true" tabindex="-1"></a>        <span class="at">axis.text.y =</span> <span class="fu">element_text</span>(<span class="at">hjust =</span> <span class="dv">0</span>),</span>
<span id="cb51-38"><a href="#cb51-38" aria-hidden="true" tabindex="-1"></a>        <span class="at">plot.caption =</span> <span class="fu">element_text</span>(<span class="at">hjust =</span> <span class="dv">0</span>, <span class="at">colour =</span> <span class="st">"grey40"</span>))</span>
<span id="cb51-39"><a href="#cb51-39" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb51-40"><a href="#cb51-40" aria-hidden="true" tabindex="-1"></a>p_km <span class="sc">/</span> p_tab <span class="sc">+</span> <span class="fu">plot_layout</span>(<span class="at">heights =</span> <span class="fu">c</span>(<span class="dv">4</span>, <span class="dv">1</span>))</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output-display">
<div id="fig-km" class="quarto-float quarto-figure quarto-figure-center anchored" data-fig-align="center">
<figure class="quarto-float quarto-float-fig figure">
<div aria-describedby="fig-km-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
<img src="kkstatfun-worked-example_files/figure-html/fig-km-1.png" class="img-fluid quarto-figure quarto-figure-center figure-img" style="width:100.0%">
</div>
<figcaption class="quarto-float-caption-bottom quarto-float-caption quarto-float-fig" id="fig-km-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
Figure&nbsp;4: Kaplan–Meier curves with the risk table built as a second panel: rules between strata, counts coloured to match their curve, one shared axis. Unadjusted, so it carries the same confounding as the crude 2×2.
</figcaption>
</figure>
</div>
</div>
</div>
<p>The log-rank test itself is a separate function, because a figure is not a result:</p>
<div class="cell" data-layout-align="center">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb52"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb52-1"><a href="#cb52-1" aria-hidden="true" tabindex="-1"></a><span class="fu">kk_logrank</span>(cap, time, status, timing) <span class="sc">|&gt;</span></span>
<span id="cb52-2"><a href="#cb52-2" aria-hidden="true" tabindex="-1"></a>  <span class="fu">select</span>(group, n, observed, expected, oe_ratio, chisq, p_value) <span class="sc">|&gt;</span></span>
<span id="cb52-3"><a href="#cb52-3" aria-hidden="true" tabindex="-1"></a>  <span class="fu">mutate_round</span>(<span class="dv">3</span>)</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-stdout">
<pre><code>#&gt; # A tibble: 2 × 7
#&gt;   group                 n observed expected oe_ratio chisq p_value
#&gt;   &lt;chr&gt;             &lt;dbl&gt;    &lt;dbl&gt;    &lt;dbl&gt;    &lt;dbl&gt; &lt;dbl&gt;   &lt;dbl&gt;
#&gt; 1 Antibiotics ≥ 4 h  1617      258     315.    0.819  22.9       0
#&gt; 2 Antibiotics &lt; 4 h  1383      316     259.    1.22   22.9       0</code></pre>
</div>
</div>
<div class="cell" data-layout-align="center">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb54"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb54-1"><a href="#cb54-1" aria-hidden="true" tabindex="-1"></a>cox <span class="ot">&lt;-</span> <span class="fu">kk_coxph</span>(cap, time, status,</span>
<span id="cb54-2"><a href="#cb54-2" aria-hidden="true" tabindex="-1"></a>                <span class="fu">c</span>(<span class="st">"early_abx"</span>, <span class="st">"curb65"</span>, <span class="st">"age"</span>, <span class="st">"charlson"</span>))</span>
<span id="cb54-3"><a href="#cb54-3" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb54-4"><a href="#cb54-4" aria-hidden="true" tabindex="-1"></a>cox <span class="sc">|&gt;</span></span>
<span id="cb54-5"><a href="#cb54-5" aria-hidden="true" tabindex="-1"></a>  <span class="fu">filter</span>(model_type <span class="sc">==</span> <span class="st">"multivariable"</span>) <span class="sc">|&gt;</span></span>
<span id="cb54-6"><a href="#cb54-6" aria-hidden="true" tabindex="-1"></a>  <span class="fu">select</span>(term, hazard_ratio, conf.low, conf.high, ph_p, ph_global_p) <span class="sc">|&gt;</span></span>
<span id="cb54-7"><a href="#cb54-7" aria-hidden="true" tabindex="-1"></a>  <span class="fu">mutate_round</span>(<span class="dv">4</span>)</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-stdout">
<pre><code>#&gt; # A tibble: 4 × 6
#&gt;   term      hazard_ratio conf.low conf.high   ph_p ph_global_p
#&gt;   &lt;chr&gt;            &lt;dbl&gt;    &lt;dbl&gt;     &lt;dbl&gt;  &lt;dbl&gt;       &lt;dbl&gt;
#&gt; 1 early_abx        0.728    0.607     0.873 0.517       0.0058
#&gt; 2 curb65           2.06     1.88      2.27  0.554       0.0058
#&gt; 3 age              1.03     1.02      1.04  0.031       0.0058
#&gt; 4 charlson         1.02     0.964     1.08  0.0023      0.0058</code></pre>
</div>
</div>
<p>Adjusted hazard ratio for early treatment: 0.73. Note the columns you did not ask for. <code>ph_p</code> is the Schoenfeld test per term and <code>ph_global_p</code> the global one, returned <em>beside</em> the estimate rather than left to a separate <code>cox.zph()</code> call — and here the global test is significant, driven by age. Proportional hazards does not hold, which means the hazard ratio is an average over a changing effect.</p>
<p>The reasonable response is an estimand that does not need the assumption. Restricted mean survival time is the area under the curve to a horizon you choose, in days:</p>
<div class="cell" data-layout-align="center">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb56"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb56-1"><a href="#cb56-1" aria-hidden="true" tabindex="-1"></a><span class="fu">kk_rmst</span>(cap, time, status, timing, <span class="at">tau =</span> <span class="dv">90</span>) <span class="sc">|&gt;</span> <span class="fu">mutate_round</span>(<span class="dv">3</span>)</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-stdout">
<pre><code>#&gt; # A tibble: 4 × 8
#&gt;   group                                                     tau   rmst     se
#&gt;   &lt;chr&gt;                                                   &lt;dbl&gt;  &lt;dbl&gt;  &lt;dbl&gt;
#&gt; 1 Antibiotics ≥ 4 h                                          90 82.5    0.498
#&gt; 2 Antibiotics &lt; 4 h                                          90 79.3    0.621
#&gt; 3 RMST difference (Antibiotics &lt; 4 h - Antibiotics ≥ 4 h)    90 -3.23   0.796
#&gt; 4 RMST ratio (Antibiotics &lt; 4 h / Antibiotics ≥ 4 h)         90  0.961 NA    
#&gt;   conf.low conf.high p.value conf.level
#&gt;      &lt;dbl&gt;     &lt;dbl&gt;   &lt;dbl&gt;      &lt;dbl&gt;
#&gt; 1   81.6       83.5       NA       0.95
#&gt; 2   78.1       80.5       NA       0.95
#&gt; 3   -4.79      -1.67       0       0.95
#&gt; 4    0.942      0.98       0       0.95</code></pre>
</div>
</div>
<p>Reported as “on average, X fewer days alive out of 90”, this is both assumption-free and comprehensible to a non-statistician — two properties that rarely travel together. (Unadjusted, it still carries the confounding; the point here is the estimand, not the estimate.)</p>
</section>
<section id="when-assignment-was-a-rule-not-a-judgement" class="level2">
<h2 class="anchored" data-anchor-id="when-assignment-was-a-rule-not-a-judgement">8. When assignment was a rule, not a judgement</h2>
<p>The functions above all need the no-unmeasured-confounding assumption. The quasi-experimental family, new in 1.3.0, does not: when an intervention was switched on by a policy date, an eligibility threshold or a staggered rollout, that rule identifies the effect on its own.</p>
<p>A stewardship programme introduced in month 25 of a 48-month series of antibiotic consumption:</p>
<div class="cell" data-layout-align="center">
<details class="code-fold">
<summary>Monthly stewardship series (click to expand)</summary>
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb58"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb58-1"><a href="#cb58-1" aria-hidden="true" tabindex="-1"></a><span class="fu">set.seed</span>(<span class="dv">11</span>)</span>
<span id="cb58-2"><a href="#cb58-2" aria-hidden="true" tabindex="-1"></a>steward <span class="ot">&lt;-</span> <span class="fu">tibble</span>(</span>
<span id="cb58-3"><a href="#cb58-3" aria-hidden="true" tabindex="-1"></a>  <span class="at">month =</span> <span class="dv">1</span><span class="sc">:</span><span class="dv">48</span>,</span>
<span id="cb58-4"><a href="#cb58-4" aria-hidden="true" tabindex="-1"></a>  <span class="at">ddd   =</span> <span class="fu">round</span>(<span class="dv">92</span> <span class="sc">-</span> <span class="fl">0.18</span> <span class="sc">*</span> month <span class="sc">+</span></span>
<span id="cb58-5"><a href="#cb58-5" aria-hidden="true" tabindex="-1"></a>                <span class="fu">ifelse</span>(month <span class="sc">&gt;</span> <span class="dv">24</span>, <span class="sc">-</span><span class="fl">9.5</span> <span class="sc">-</span> <span class="fl">0.75</span> <span class="sc">*</span> (month <span class="sc">-</span> <span class="dv">24</span>), <span class="dv">0</span>) <span class="sc">+</span></span>
<span id="cb58-6"><a href="#cb58-6" aria-hidden="true" tabindex="-1"></a>                <span class="fl">3.2</span> <span class="sc">*</span> <span class="fu">sin</span>(<span class="dv">2</span> <span class="sc">*</span> pi <span class="sc">*</span> month <span class="sc">/</span> <span class="dv">12</span>) <span class="sc">+</span> <span class="fu">rnorm</span>(<span class="dv">48</span>, <span class="dv">0</span>, <span class="fl">2.4</span>), <span class="dv">1</span>)</span>
<span id="cb58-7"><a href="#cb58-7" aria-hidden="true" tabindex="-1"></a>)</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
</details>
</div>
<div class="cell" data-layout-align="center">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb59"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb59-1"><a href="#cb59-1" aria-hidden="true" tabindex="-1"></a>its <span class="ot">&lt;-</span> <span class="fu">kk_its</span>(steward, ddd, month,</span>
<span id="cb59-2"><a href="#cb59-2" aria-hidden="true" tabindex="-1"></a>              <span class="at">intervention_time =</span> <span class="dv">24</span>,</span>
<span id="cb59-3"><a href="#cb59-3" aria-hidden="true" tabindex="-1"></a>              <span class="at">harmonic =</span> <span class="dv">1</span>, <span class="at">period =</span> <span class="dv">12</span>)</span>
<span id="cb59-4"><a href="#cb59-4" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb59-5"><a href="#cb59-5" aria-hidden="true" tabindex="-1"></a>its <span class="sc">|&gt;</span> <span class="fu">select</span>(term, estimate, conf.low, conf.high, p.value) <span class="sc">|&gt;</span> <span class="fu">mutate_round</span>(<span class="dv">3</span>)</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-stdout">
<pre><code>#&gt; # A tibble: 6 × 5
#&gt;   term           estimate conf.low conf.high p.value
#&gt;   &lt;chr&gt;             &lt;dbl&gt;    &lt;dbl&gt;     &lt;dbl&gt;   &lt;dbl&gt;
#&gt; 1 intercept        91.3     89.4      93.2     0    
#&gt; 2 baseline_trend   -0.192   -0.312    -0.072   0.002
#&gt; 3 level_change     -6.92   -11.3      -2.57    0.003
#&gt; 4 trend_change     -0.828   -1.05     -0.61    0    
#&gt; 5 sin1              2.92     1.84      4.00    0    
#&gt; 6 cos1              0.206   -1.04      1.45    0.74</code></pre>
</div>
</div>
<p>Segmented regression with Newey–West standard errors and a seasonal harmonic, separating the two things a policy can do: an immediate <strong>level change</strong> of -6.9 DDD per 100 bed-days, and a <strong>trend change</strong> of -0.83 per month on top of the pre-existing decline. Reporting only the first would badly understate the programme; reporting only their sum would overstate the launch.</p>
<p>The counterfactual series and the cumulative impact come attached as attributes:</p>
<div class="cell" data-layout-align="center">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb61"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb61-1"><a href="#cb61-1" aria-hidden="true" tabindex="-1"></a><span class="fu">attr</span>(its, <span class="st">"impact"</span>) <span class="sc">|&gt;</span></span>
<span id="cb61-2"><a href="#cb61-2" aria-hidden="true" tabindex="-1"></a>  <span class="fu">select</span>(final_observed, final_counterfactual, final_relative,</span>
<span id="cb61-3"><a href="#cb61-3" aria-hidden="true" tabindex="-1"></a>         cumulative_difference) <span class="sc">|&gt;</span></span>
<span id="cb61-4"><a href="#cb61-4" aria-hidden="true" tabindex="-1"></a>  <span class="fu">mutate_round</span>(<span class="dv">1</span>)</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-stdout">
<pre><code>#&gt; # A tibble: 1 × 4
#&gt;   final_observed final_counterfactual final_relative cumulative_difference
#&gt;            &lt;dbl&gt;                &lt;dbl&gt;          &lt;dbl&gt;                 &lt;dbl&gt;
#&gt; 1           54.7                 82.3           -0.3                 -442.</code></pre>
</div>
</div>
<div class="cell" data-layout-align="center">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb63"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb63-1"><a href="#cb63-1" aria-hidden="true" tabindex="-1"></a>cf <span class="ot">&lt;-</span> <span class="fu">attr</span>(its, <span class="st">"counterfactual"</span>)</span>
<span id="cb63-2"><a href="#cb63-2" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb63-3"><a href="#cb63-3" aria-hidden="true" tabindex="-1"></a><span class="fu">kkplot</span>(cf, <span class="fu">aes</span>(time)) <span class="sc">+</span></span>
<span id="cb63-4"><a href="#cb63-4" aria-hidden="true" tabindex="-1"></a>  <span class="fu">geom_ribbon</span>(<span class="fu">aes</span>(<span class="at">ymin =</span> cf.low, <span class="at">ymax =</span> cf.high), <span class="at">fill =</span> <span class="st">"grey80"</span>, <span class="at">alpha =</span> .<span class="dv">5</span>) <span class="sc">+</span></span>
<span id="cb63-5"><a href="#cb63-5" aria-hidden="true" tabindex="-1"></a>  <span class="fu">geom_line</span>(<span class="fu">aes</span>(<span class="at">y =</span> counterfactual), <span class="at">linetype =</span> <span class="st">"dashed"</span>, <span class="at">colour =</span> <span class="st">"#003049"</span>) <span class="sc">+</span></span>
<span id="cb63-6"><a href="#cb63-6" aria-hidden="true" tabindex="-1"></a>  <span class="fu">geom_point</span>(<span class="fu">aes</span>(<span class="at">y =</span> observed), <span class="at">colour =</span> <span class="st">"#D62828"</span>, <span class="at">size =</span> <span class="fl">1.5</span>) <span class="sc">+</span></span>
<span id="cb63-7"><a href="#cb63-7" aria-hidden="true" tabindex="-1"></a>  <span class="fu">geom_line</span>(<span class="fu">aes</span>(<span class="at">y =</span> fitted), <span class="at">colour =</span> <span class="st">"#D62828"</span>, <span class="at">linewidth =</span> .<span class="dv">8</span>) <span class="sc">+</span></span>
<span id="cb63-8"><a href="#cb63-8" aria-hidden="true" tabindex="-1"></a>  <span class="fu">geom_vline</span>(<span class="at">xintercept =</span> <span class="fl">24.5</span>, <span class="at">colour =</span> <span class="st">"grey40"</span>) <span class="sc">+</span></span>
<span id="cb63-9"><a href="#cb63-9" aria-hidden="true" tabindex="-1"></a>  <span class="fu">annotate</span>(<span class="st">"text"</span>, <span class="at">x =</span> <span class="fl">25.5</span>, <span class="at">y =</span> <span class="dv">95</span>, <span class="at">hjust =</span> <span class="dv">0</span>, <span class="at">size =</span> <span class="fl">3.6</span>, <span class="at">colour =</span> <span class="st">"grey30"</span>,</span>
<span id="cb63-10"><a href="#cb63-10" aria-hidden="true" tabindex="-1"></a>           <span class="at">family =</span> myfont, <span class="at">label =</span> <span class="st">"Stewardship programme"</span>) <span class="sc">+</span></span>
<span id="cb63-11"><a href="#cb63-11" aria-hidden="true" tabindex="-1"></a>  <span class="fu">labs</span>(<span class="at">x =</span> <span class="st">"Month"</span>, <span class="at">y =</span> <span class="st">"DDD per 100 bed-days"</span>,</span>
<span id="cb63-12"><a href="#cb63-12" aria-hidden="true" tabindex="-1"></a>       <span class="at">title =</span> <span class="st">"Interrupted time series: antibiotic consumption"</span>,</span>
<span id="cb63-13"><a href="#cb63-13" aria-hidden="true" tabindex="-1"></a>       <span class="at">subtitle =</span> <span class="st">"Dashed line and band: the counterfactual, had nothing changed"</span>)</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output-display">
<div id="fig-its" class="quarto-float quarto-figure quarto-figure-center anchored" data-fig-align="center">
<figure class="quarto-float quarto-float-fig figure">
<div aria-describedby="fig-its-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
<img src="kkstatfun-worked-example_files/figure-html/fig-its-1.png" class="img-fluid quarto-figure quarto-figure-center figure-img" style="width:100.0%">
</div>
<figcaption class="quarto-float-caption-bottom quarto-float-caption quarto-float-fig" id="fig-its-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
Figure&nbsp;5: Observed series against the modelled counterfactual — what consumption would have been had the pre-intervention level, trend and seasonality simply continued.
</figcaption>
</figure>
</div>
</div>
</div>
<p>With a control group instead of a single series, the same question becomes difference-in-differences — four hospitals adopting in 2021, four not:</p>
<div class="cell" data-layout-align="center">
<details class="code-fold">
<summary>Hospital panel (click to expand)</summary>
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb64"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb64-1"><a href="#cb64-1" aria-hidden="true" tabindex="-1"></a><span class="fu">set.seed</span>(<span class="dv">77</span>)</span>
<span id="cb64-2"><a href="#cb64-2" aria-hidden="true" tabindex="-1"></a>panel <span class="ot">&lt;-</span> <span class="fu">expand.grid</span>(<span class="at">hospital =</span> hospitals, <span class="at">year =</span> <span class="dv">2018</span><span class="sc">:</span><span class="dv">2024</span>,</span>
<span id="cb64-3"><a href="#cb64-3" aria-hidden="true" tabindex="-1"></a>                     <span class="at">stringsAsFactors =</span> <span class="cn">FALSE</span>) <span class="sc">|&gt;</span></span>
<span id="cb64-4"><a href="#cb64-4" aria-hidden="true" tabindex="-1"></a>  <span class="fu">as_tibble</span>() <span class="sc">|&gt;</span></span>
<span id="cb64-5"><a href="#cb64-5" aria-hidden="true" tabindex="-1"></a>  <span class="fu">mutate</span>(<span class="at">treated =</span> <span class="fu">as.integer</span>(hospital <span class="sc">%in%</span> hospitals[<span class="dv">1</span><span class="sc">:</span><span class="dv">4</span>]),</span>
<span id="cb64-6"><a href="#cb64-6" aria-hidden="true" tabindex="-1"></a>         <span class="at">post    =</span> <span class="fu">as.integer</span>(year <span class="sc">&gt;=</span> <span class="dv">2021</span>),</span>
<span id="cb64-7"><a href="#cb64-7" aria-hidden="true" tabindex="-1"></a>         <span class="at">resist  =</span> <span class="fu">round</span>(<span class="dv">22</span> <span class="sc">+</span> <span class="fl">2.1</span> <span class="sc">*</span> treated <span class="sc">-</span> <span class="fl">0.55</span> <span class="sc">*</span> (year <span class="sc">-</span> <span class="dv">2018</span>) <span class="sc">+</span></span>
<span id="cb64-8"><a href="#cb64-8" aria-hidden="true" tabindex="-1"></a>                         <span class="fu">rnorm</span>(<span class="fu">n</span>(), <span class="dv">0</span>, <span class="fl">1.6</span>) <span class="sc">-</span> <span class="fl">3.4</span> <span class="sc">*</span> treated <span class="sc">*</span> post, <span class="dv">1</span>))</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
</details>
</div>
<div class="cell" data-layout-align="center">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb65"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb65-1"><a href="#cb65-1" aria-hidden="true" tabindex="-1"></a><span class="fu">kk_did</span>(panel, resist, treated, post, <span class="at">unit =</span> hospital, <span class="at">time =</span> year) <span class="sc">|&gt;</span></span>
<span id="cb65-2"><a href="#cb65-2" aria-hidden="true" tabindex="-1"></a>  <span class="fu">select</span>(term, estimate, conf.low, conf.high, p.value, n_clusters) <span class="sc">|&gt;</span></span>
<span id="cb65-3"><a href="#cb65-3" aria-hidden="true" tabindex="-1"></a>  <span class="fu">mutate_round</span>(<span class="dv">3</span>)</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-stdout">
<pre><code>#&gt; # A tibble: 1 × 6
#&gt;   term  estimate conf.low conf.high p.value n_clusters
#&gt;   &lt;chr&gt;    &lt;dbl&gt;    &lt;dbl&gt;     &lt;dbl&gt;   &lt;dbl&gt;      &lt;dbl&gt;
#&gt; 1 did      -4.26    -7.27     -1.25   0.012          8</code></pre>
</div>
</div>
<p>Two-way fixed effects with standard errors clustered on the hospital, recovering the −3.4 percentage-point effect I built in. What makes this family usable rather than merely available is that each function returns its own identifying diagnostic: <code>kk_event_study()</code> for the parallel-trends leads, <code>kk_rd_density()</code> for manipulation at an RD threshold, the first-stage <em>F</em> for an instrument, the placebo distribution for a synthetic control. The assumption and the estimate arrive together, which makes leaving the assumption out of the paper a deliberate act rather than an oversight.</p>
</section>
<section id="costing-it" class="level2">
<h2 class="anchored" data-anchor-id="costing-it">9. Costing it</h2>
<p>Suppose the stewardship programme comes with a diagnostic strategy decision. Three options, their costs in euro and their QALYs:</p>
<div class="cell" data-layout-align="center">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb67"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb67-1"><a href="#cb67-1" aria-hidden="true" tabindex="-1"></a>strategies <span class="ot">&lt;-</span> <span class="fu">tibble</span>(</span>
<span id="cb67-2"><a href="#cb67-2" aria-hidden="true" tabindex="-1"></a>  <span class="at">strategy =</span> <span class="fu">c</span>(<span class="st">"Standard care"</span>, <span class="st">"PCT-guided therapy"</span>, <span class="st">"Rapid PCR panel"</span>),</span>
<span id="cb67-3"><a href="#cb67-3" aria-hidden="true" tabindex="-1"></a>  <span class="at">cost     =</span> <span class="fu">c</span>(<span class="dv">2840</span>, <span class="dv">3260</span>, <span class="dv">4510</span>),</span>
<span id="cb67-4"><a href="#cb67-4" aria-hidden="true" tabindex="-1"></a>  <span class="at">qaly     =</span> <span class="fu">c</span>(<span class="fl">6.42</span>, <span class="fl">6.61</span>, <span class="fl">6.73</span>)</span>
<span id="cb67-5"><a href="#cb67-5" aria-hidden="true" tabindex="-1"></a>)</span>
<span id="cb67-6"><a href="#cb67-6" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb67-7"><a href="#cb67-7" aria-hidden="true" tabindex="-1"></a><span class="fu">kk_icer</span>(strategies, cost, qaly, strategy) <span class="sc">|&gt;</span> <span class="fu">mutate_round</span>(<span class="dv">1</span>)</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-stdout">
<pre><code>#&gt; # A tibble: 3 × 7
#&gt;   strategy            cost effect inc_cost inc_effect   icer status  
#&gt;   &lt;chr&gt;              &lt;dbl&gt;  &lt;dbl&gt;    &lt;dbl&gt;      &lt;dbl&gt;  &lt;dbl&gt; &lt;chr&gt;   
#&gt; 1 Standard care       2840    6.4       NA       NA      NA  frontier
#&gt; 2 PCT-guided therapy  3260    6.6      420        0.2  2210. frontier
#&gt; 3 Rapid PCR panel     4510    6.7     1250        0.1 10417. frontier</code></pre>
</div>
</div>
<p>Strategies ranked by effect, incremental ratios computed against the next-best non-dominated option, and dominance flagged. All three sit on the efficiency frontier here. At a willingness to pay of €32,000 per QALY — roughly twice Bulgarian GDP per capita, the upper end of the WHO-CHOICE convention — net monetary benefit picks the winner:</p>
<div class="cell" data-layout-align="center">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb69"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb69-1"><a href="#cb69-1" aria-hidden="true" tabindex="-1"></a><span class="fu">kk_nmb</span>(strategies, cost, qaly, <span class="at">wtp =</span> <span class="dv">32000</span>, <span class="at">strategy =</span> strategy) <span class="sc">|&gt;</span></span>
<span id="cb69-2"><a href="#cb69-2" aria-hidden="true" tabindex="-1"></a>  <span class="fu">mutate_round</span>(<span class="dv">2</span>)</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-stdout">
<pre><code>#&gt; # A tibble: 3 × 7
#&gt;   strategy             wtp  cost effect    nmb   nhb optimal
#&gt;   &lt;chr&gt;              &lt;dbl&gt; &lt;dbl&gt;  &lt;dbl&gt;  &lt;dbl&gt; &lt;dbl&gt; &lt;lgl&gt;  
#&gt; 1 Standard care      32000  2840   6.42 202600  6.33 FALSE  
#&gt; 2 PCT-guided therapy 32000  3260   6.61 208260  6.51 FALSE  
#&gt; 3 Rapid PCR panel    32000  4510   6.73 210850  6.59 TRUE</code></pre>
</div>
</div>
<p>A point estimate is not a decision, though. With probabilistic draws over cost and effect, the acceptability curve shows how much of that ranking is real and how much is noise:</p>
<div class="cell" data-layout-align="center">
<details class="code-fold">
<summary>PSA draws (click to expand)</summary>
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb71"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb71-1"><a href="#cb71-1" aria-hidden="true" tabindex="-1"></a><span class="fu">set.seed</span>(<span class="dv">303</span>)</span>
<span id="cb71-2"><a href="#cb71-2" aria-hidden="true" tabindex="-1"></a>psa <span class="ot">&lt;-</span> <span class="fu">bind_rows</span>(<span class="fu">lapply</span>(<span class="fu">seq_len</span>(<span class="dv">2000</span>), <span class="cf">function</span>(i) {</span>
<span id="cb71-3"><a href="#cb71-3" aria-hidden="true" tabindex="-1"></a>  <span class="fu">tibble</span>(<span class="at">sim      =</span> i,</span>
<span id="cb71-4"><a href="#cb71-4" aria-hidden="true" tabindex="-1"></a>         <span class="at">strategy =</span> strategies<span class="sc">$</span>strategy,</span>
<span id="cb71-5"><a href="#cb71-5" aria-hidden="true" tabindex="-1"></a>         <span class="at">cost     =</span> <span class="fu">rnorm</span>(<span class="dv">3</span>, strategies<span class="sc">$</span>cost, <span class="fu">c</span>(<span class="dv">320</span>, <span class="dv">380</span>, <span class="dv">520</span>)),</span>
<span id="cb71-6"><a href="#cb71-6" aria-hidden="true" tabindex="-1"></a>         <span class="at">qaly     =</span> <span class="fu">rnorm</span>(<span class="dv">3</span>, strategies<span class="sc">$</span>qaly, <span class="fu">c</span>(<span class="fl">0.42</span>, <span class="fl">0.44</span>, <span class="fl">0.48</span>)))</span>
<span id="cb71-7"><a href="#cb71-7" aria-hidden="true" tabindex="-1"></a>}))</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
</details>
</div>
<div class="cell" data-layout-align="center">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb72"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb72-1"><a href="#cb72-1" aria-hidden="true" tabindex="-1"></a>ce <span class="ot">&lt;-</span> <span class="fu">kk_ceac</span>(psa, sim, strategy, cost, qaly, <span class="at">wtp =</span> <span class="fu">seq</span>(<span class="dv">0</span>, <span class="dv">80000</span>, <span class="dv">2000</span>))</span>
<span id="cb72-2"><a href="#cb72-2" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb72-3"><a href="#cb72-3" aria-hidden="true" tabindex="-1"></a><span class="fu">kkplot</span>(ce, <span class="fu">aes</span>(wtp, prob_ce, <span class="at">colour =</span> strategy)) <span class="sc">+</span></span>
<span id="cb72-4"><a href="#cb72-4" aria-hidden="true" tabindex="-1"></a>  <span class="fu">geom_line</span>(<span class="at">linewidth =</span> .<span class="dv">9</span>) <span class="sc">+</span></span>
<span id="cb72-5"><a href="#cb72-5" aria-hidden="true" tabindex="-1"></a>  <span class="fu">geom_vline</span>(<span class="at">xintercept =</span> <span class="dv">32000</span>, <span class="at">linetype =</span> <span class="st">"dashed"</span>, <span class="at">colour =</span> <span class="st">"grey45"</span>) <span class="sc">+</span></span>
<span id="cb72-6"><a href="#cb72-6" aria-hidden="true" tabindex="-1"></a>  <span class="fu">annotate</span>(<span class="st">"text"</span>, <span class="at">x =</span> <span class="dv">33000</span>, <span class="at">y =</span> .<span class="dv">05</span>, <span class="at">hjust =</span> <span class="dv">0</span>, <span class="at">size =</span> <span class="fl">3.6</span>, <span class="at">colour =</span> <span class="st">"grey35"</span>,</span>
<span id="cb72-7"><a href="#cb72-7" aria-hidden="true" tabindex="-1"></a>           <span class="at">family =</span> myfont, <span class="at">label =</span> <span class="st">"2 × GDP per capita"</span>) <span class="sc">+</span></span>
<span id="cb72-8"><a href="#cb72-8" aria-hidden="true" tabindex="-1"></a>  <span class="fu">scale_color_kk</span>() <span class="sc">+</span></span>
<span id="cb72-9"><a href="#cb72-9" aria-hidden="true" tabindex="-1"></a>  <span class="fu">scale_y_continuous</span>(<span class="at">labels =</span> <span class="fu">label_percent</span>(<span class="dv">1</span>), <span class="at">limits =</span> <span class="fu">c</span>(<span class="dv">0</span>, <span class="dv">1</span>)) <span class="sc">+</span></span>
<span id="cb72-10"><a href="#cb72-10" aria-hidden="true" tabindex="-1"></a>  <span class="fu">scale_x_continuous</span>(<span class="at">labels =</span> <span class="fu">label_number</span>(<span class="at">scale =</span> <span class="fl">1e-3</span>, <span class="at">suffix =</span> <span class="st">"k"</span>)) <span class="sc">+</span></span>
<span id="cb72-11"><a href="#cb72-11" aria-hidden="true" tabindex="-1"></a>  <span class="fu">labs</span>(<span class="at">x =</span> <span class="st">"Willingness to pay (EUR per QALY)"</span>, <span class="at">y =</span> <span class="st">"Probability cost-effective"</span>,</span>
<span id="cb72-12"><a href="#cb72-12" aria-hidden="true" tabindex="-1"></a>       <span class="at">colour =</span> <span class="cn">NULL</span>, <span class="at">title =</span> <span class="st">"Cost-effectiveness acceptability curve"</span>,</span>
<span id="cb72-13"><a href="#cb72-13" aria-hidden="true" tabindex="-1"></a>       <span class="at">subtitle =</span> <span class="st">"2,000 probabilistic draws per strategy"</span>) <span class="sc">+</span></span>
<span id="cb72-14"><a href="#cb72-14" aria-hidden="true" tabindex="-1"></a>  <span class="fu">theme</span>(<span class="at">legend.position =</span> <span class="st">"top"</span>)</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output-display">
<div id="fig-ceac" class="quarto-float quarto-figure quarto-figure-center anchored" data-fig-align="center">
<figure class="quarto-float quarto-float-fig figure">
<div aria-describedby="fig-ceac-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
<img src="kkstatfun-worked-example_files/figure-html/fig-ceac-1.png" class="img-fluid quarto-figure quarto-figure-center figure-img" style="width:100.0%">
</div>
<figcaption class="quarto-float-caption-bottom quarto-float-caption quarto-float-fig" id="fig-ceac-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
Figure&nbsp;6: Cost-effectiveness acceptability curve from 2,000 probabilistic draws. The optimal strategy is never more than 45 % likely to be optimal — the honest headline.
</figcaption>
</figure>
</div>
</div>
</div>
<p>The rapid panel has the best expected net benefit at €32,000 and is optimal in only about 44 % of draws. Both statements are true, and a decision-maker needs the second one.</p>
</section>
<section id="everything-else-briefly" class="level2">
<h2 class="anchored" data-anchor-id="everything-else-briefly">10. Everything else, briefly</h2>
<p>The same conventions run through parts of the package this cohort has no use for. Sample size for the study I have just pretended to analyse:</p>
<div class="cell" data-layout-align="center">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb73"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb73-1"><a href="#cb73-1" aria-hidden="true" tabindex="-1"></a><span class="fu">kk_sample_size_epi</span>(<span class="at">design =</span> <span class="st">"cohort"</span>, <span class="at">p0 =</span> <span class="fl">0.12</span>, <span class="at">rr_or =</span> <span class="fl">0.7</span>,</span>
<span id="cb73-2"><a href="#cb73-2" aria-hidden="true" tabindex="-1"></a>                   <span class="at">power =</span> <span class="fl">0.8</span>, <span class="at">alpha =</span> <span class="fl">0.05</span>) <span class="sc">|&gt;</span></span>
<span id="cb73-3"><a href="#cb73-3" aria-hidden="true" tabindex="-1"></a>  <span class="fu">select</span>(design, p0, p1, alpha, power, n_group1, n_total)</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-stdout">
<pre><code>#&gt; # A tibble: 1 × 7
#&gt;   design    p0    p1 alpha power n_group1 n_total
#&gt;   &lt;chr&gt;  &lt;dbl&gt; &lt;dbl&gt; &lt;dbl&gt; &lt;dbl&gt;    &lt;dbl&gt;   &lt;dbl&gt;
#&gt; 1 cohort  0.12 0.084  0.05   0.8     1109    2218</code></pre>
</div>
</div>
<p>Outbreak dynamics, where the reproduction number and the final attack rate follow from the transmission parameters:</p>
<div class="cell" data-layout-align="center">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb75"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb75-1"><a href="#cb75-1" aria-hidden="true" tabindex="-1"></a><span class="fu">kk_r0</span>(<span class="at">beta =</span> <span class="fl">0.42</span>, <span class="at">gamma =</span> <span class="fl">0.2</span>)</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-stdout">
<pre><code>#&gt; # A tibble: 1 × 2
#&gt;      R0 method
#&gt;   &lt;dbl&gt; &lt;chr&gt; 
#&gt; 1   2.1 params</code></pre>
</div>
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb77"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb77-1"><a href="#cb77-1" aria-hidden="true" tabindex="-1"></a><span class="fu">kk_final_size</span>(<span class="at">R0 =</span> <span class="fl">2.1</span>)</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-stdout">
<pre><code>#&gt; # A tibble: 1 × 3
#&gt;      R0 attack_rate herd_immunity
#&gt;   &lt;dbl&gt;       &lt;dbl&gt;         &lt;dbl&gt;
#&gt; 1   2.1       0.822         0.524</code></pre>
</div>
</div>
<p>And, because most of my data comes out of Bulgarian national systems, the registry helpers: <code>extract_egn_info()</code> parses date of birth, sex, age and birth region out of an EGN; <code>kk_std_rates()</code> and <code>kk_smr()</code> do direct and indirect standardisation; <code>kk_nb_scan()</code> looks for space–time clusters under overdispersion.</p>
</section>
<section id="the-philosophy-stated-plainly" class="level2">
<h2 class="anchored" data-anchor-id="the-philosophy-stated-plainly">11. The philosophy, stated plainly</h2>
<p>Having shown it, let me name it. Four commitments, in the order they matter.</p>
<p><strong>Tidy data in, tidy data out.</strong> Every function takes a data frame first and returns a tibble. Never a print-only object you have to scrape, never a list of matrices, never a <code>summary()</code> you parse with regular expressions. This is why §5 could collect four estimates from four different estimators into one figure without a number being retyped, and why any result in this post could be written to a CSV and included in a manuscript with no step in between.</p>
<p><strong><code>group_by()</code> is not decoration.</strong> Stratified analysis is the default posture of epidemiology, not an advanced option. When running an analysis by site, by sex or by severity costs one line, you actually do it — and effect modification stops being something you notice at peer review.</p>
<p><strong>Decide once, then reuse.</strong> Which confidence-interval method for a rate? Which correction for a sparse cell? Which test when the assumption fails? Each of those was decided once, tested against the worked examples in Rothman, Zar and Sheskin, and frozen in a function. The value is not brevity. It is that my 2023 paper and my 2026 paper used the same method, and a reviewer asking “which one?” gets an answer rather than an archaeology project.</p>
<p><strong>Return the diagnostic beside the estimate.</strong> <code>kk_coxph()</code> hands back the Schoenfeld test with the hazard ratio. <code>kk_stratified_2x2()</code> hands back Breslow–Day with the pooled estimate. <code>kk_pal_check()</code> fails my own palette. The design principle is that the check you would rather skip should arrive unrequested, in the same object, so that omitting it from the write-up is a choice you have to make on purpose.</p>
<div class="callout callout-style-default callout-warning callout-titled">
<div class="callout-header d-flex align-content-center">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-title-container flex-fill">
<span class="screen-reader-only">Warning</span>What this is not
</div>
</div>
<div class="callout-body-container callout-body">
<p>It is not a replacement for understanding the method. <code>kk_tmle()</code> will happily estimate an average treatment effect from a dataset where the exchangeability assumption is nonsense, and it will do so with a tidy confidence interval and no complaint. Convenience functions lower the cost of doing an analysis, including a bad one. The books remain the load-bearing part; the package is only the part that stops me re-deriving them at midnight.</p>
</div>
</div>
</section>
<section id="where-this-actually-gets-used-nhis-data" class="level2">
<h2 class="anchored" data-anchor-id="where-this-actually-gets-used-nhis-data">12. Where this actually gets used: NHIS data</h2>
<p>None of the above is hypothetical tooling. The synthetic cohort is a teaching device. The real work is population-level, and the analysis is its <em>last</em> step. A public-health question here — how many people were treated for a condition, where, with what, and what changed after a policy — is answered from the <strong>National Health Information System</strong> (НЗИС, NHIS): the national e-health infrastructure through which prescriptions, referrals, hospitalisations and immunisations are recorded. It covers the country rather than a sample, and it is where most of my data comes from.</p>
<p>That coverage is also its main analytical hazard. The NHIS records what clinicians entered into it, which is not the same as what happened to patients: completeness differs by module, by year and by how strongly a given field was enforced when the record was made. A count that rises in 2022 may be a rise in disease, a rise in reporting, or a change in what the system required — and you cannot tell which from the file. So the first analysis on any NHIS extract is always the same one: plot the raw counts by month and look for the step change that corresponds to a software release rather than an epidemic.</p>
<p>Where the question is about money rather than activity, the <strong>National Health Insurance Fund</strong> (НЗОК, NHIF) is the second source: claims under clinical pathways (КП), reimbursed medicines by ATC code, dialysis, dental. The two are not interchangeable. The NHIS records clinical activity; the NHIF records what was paid for. Care that generates no claim exists only in the first, and a claim that was never clinically recorded exists only in the second, so which one you ask decides what your denominator means.</p>
<section id="asking-for-the-data" class="level3">
<h3 class="anchored" data-anchor-id="asking-for-the-data">Asking for the data</h3>
<p>Very little of either is published in usable form, so the work starts with a written request under the Access to Public Information Act (ЗДОИ). After a fair number of these I would say the request itself is a skill, with rules:</p>
<ul>
<li><strong>Ask for aggregates, never person-level records.</strong> Counts by code, month, district (област), age band and sex. That is not only the lawful form of the request — it removes the institution’s best reason to refuse, because with no personal data there is no data-protection ground for saying no.</li>
<li><strong>Name the fields and the period exactly.</strong> “Брой хоспитализации по КП 39 за периода 2019–2024 г., по области и по пол” is answerable by a clerk running a query. “Data on hospitalisations” is answerable only by a meeting.</li>
<li><strong>Say the format in the request.</strong> Write <code>.csv</code> or <code>.xlsx</code> explicitly, or the answer arrives as a scan of a printed table and the institution has complied.</li>
<li><strong>Ask for the codelist alongside the data</strong> — the version of the МКБ, КП or ATC list in force in each year of the period. Otherwise you will spend a week reconstructing which code was renumbered when.</li>
<li><strong>Pre-empt the small-cell refusal.</strong> Propose the suppression rule yourself: cells below five reported as “&lt;5”. It turns a likely refusal into a qualified release.</li>
<li><strong>Keep the reference number and the response date.</strong> They become the provenance record in the deposit metadata, and they are what makes the resulting dataset citable rather than anecdotal.</li>
</ul>
<p>The reply usually arrives inside the statutory two weeks, and it is usually incomplete in some interesting way. That is normal, and it is why the next step exists.</p>
</section>
<section id="the-pipeline" class="level3">
<h3 class="anchored" data-anchor-id="the-pipeline">The pipeline</h3>
<p>What arrives is never clean. Merged header cells, footer totals rows, comma decimal separators, Cyrillic and Latin mixed inside one column, МКБ codes that Excel has helpfully converted to dates, and a schema that changes between years. So the pipeline is four numbered scripts and one rule:</p>
<pre><code>scripts/01-ingest.R      # raw -&gt; tidy, one function per source file
scripts/02-clean.R       # validation, deduplication, type resolution
scripts/03-standardise.R # currency, encoding, codelist crosswalks
scripts/04-publish.R     # sha256 hashes, metadata, deposit package</code></pre>
<p>The rule is that <code>data/raw/</code> is never edited. Every correction happens in a script, with a comment saying what was wrong — which means the pipeline can always be re-run from the true origin and “what exactly did you change?” has an answer.</p>
<p>Three conventions do most of the work. Money is stored in <strong>both BGN and EUR</strong> at the fixed rate of 1.95583, which matters across the 2025–2026 adoption boundary, where a careless join double-converts a column and nobody notices. CSV output is <strong>UTF-8 with BOM</strong>, so Cyrillic survives the round trip through Excel. And every dataset ships a <code>data-dictionary.csv</code> with one row per column: Bulgarian label, English label, type, unit, codelist, the original Cyrillic field name from the source, and the caveats. The dictionary is the artefact that survives schema drift. The code is comparatively disposable.</p>
<p>Alongside it goes a <code>data-quality-report.md</code> logging, per source file, the rows ingested, the rows surviving, and each irreversible decision. That log is more valuable than perfect code, because it is the only record of judgements that the data itself no longer shows.</p>
<p>The finished product is deposited on Zenodo with a DOI, CC-BY, and a <code>CITATION.cff</code> — which turns a cleaning job into a citable output, and means the next person (often me, two years later) starts from the clean version.</p>
</section>
<section id="then-and-only-then-the-analysis" class="level3">
<h3 class="anchored" data-anchor-id="then-and-only-then-the-analysis">Then, and only then, the analysis</h3>
<p>At this point the file is a tidy panel of counts by district, year, age band and code, and everything in §§3–9 applies, with the population-health functions doing the work the clinical ones did above. Rates per person-time with exact Poisson intervals from <code>kk_incidence_rate()</code>. Direct age-standardisation against the European Standard Population with <code>kk_std_rates()</code>, or <code>kk_std_rates_ci()</code> where the counts are sparse enough that the Gamma interval matters. Indirect standardisation and an SMR by district with <code>kk_smr()</code>. Period trends with <code>kk_apc()</code>. The spatial-temporal outlier hunt with <code>kk_nb_scan()</code>.</p>
<p>When the question is about a policy — a new reimbursement rule, a pathway price change, a programme rolled out in some districts before others — it is §8 verbatim: <code>kk_its()</code> on the national monthly series, <code>kk_did()</code> or <code>kk_did_staggered()</code> across districts, with <code>kk_event_study()</code> for whether the parallel-trends story survives contact with the pre-period. National data suits those designs unusually well, because the intervention really was switched on by a rule with a date, and the date is in the <em>Държавен вестник</em>.</p>
<p>That is the argument for building the package. The interesting part of a public-health analysis is deciding what to ask for and what the resulting estimate can carry. The part in between should be a function call I have already tested.</p>
</section>
<section id="where-ai-fits-and-where-it-does-not" class="level3">
<h3 class="anchored" data-anchor-id="where-ai-fits-and-where-it-does-not">Where AI fits, and where it does not</h3>
<p>I run this with <a href="https://claude.com/claude-code">Claude Code</a>, and what made it useful rather than merely fast is <strong>skills</strong>: plain Markdown files in <code>~/.claude/skills/</code>, one per recurring task, each stating the conventions for that task. The data-pipeline skill holds the directory layout, the currency rule, the encoding rule and the data-dictionary schema. <code>kkstatfun-epi</code> says to reach for <code>kk_*</code> functions over <code>epitools</code> or <code>gtsummary</code>, and how they compose. <code>bibliography-management</code> holds the citation rules below. <code>humanizer-bg</code> strips the English calques out of Bulgarian prose, and <code>humanizer-en</code> does the same job in the other direction — this post went through it.</p>
<p>The distinction I would insist on is this: <strong>the conventions are written by me, in version control, once. The model applies them.</strong> That is a different activity from asking a chatbot how to clean health data. The model is fast at the mechanical middle: parsing a malformed sheet, writing the ingest function for the twelfth source file, drafting the data dictionary from the column names, catching the year the schema changed, putting a ЗДОИ request into the register’s own idiom. It is not the thing deciding whether a join is legitimate or what an estimate means. Every number it produces gets checked against the source, because a fluent wrong answer is the characteristic failure mode and costs nothing to generate.</p>
<p>The small tools around it matter more than they sound. <code>anydoc</code> converts the legacy <code>.doc</code> and <code>.xls</code> files institutions still send; pandoc will silently emit binary garbage for an <code>.xls</code> instead of failing, which is exactly the class of error that ends up in a published table. DBeaver is where I check a join before writing analysis code against it. Local models through Ollama take the bulk mechanical passes — summarising, extracting, first-draft translation — for text that should not leave the machine. And all of it is in Git, because the value of version control here is not collaboration but a record of my own reasoning: the commit that dropped 1,400 rows says why it dropped them.</p>
</section>
<section id="writing-it-up" class="level3">
<h3 class="anchored" data-anchor-id="writing-it-up">Writing it up</h3>
<p>The manuscript is Quarto, the bibliography is a plain <code>.bib</code> file next to it, and entries are fetched by DOI or PMID rather than typed:</p>
<div class="code-copy-outer-scaffold"><div class="sourceCode" id="cb80"><pre class="sourceCode bash code-with-copy"><code class="sourceCode bash"><span id="cb80-1"><a href="#cb80-1" aria-hidden="true" tabindex="-1"></a><span class="ex">getbib</span> 10.1016/S0140-6736<span class="er">(</span><span class="ex">20</span><span class="kw">)</span><span class="ex">30183-5</span> 33301246</span>
<span id="cb80-2"><a href="#cb80-2" aria-hidden="true" tabindex="-1"></a><span class="ex">getbib</span> <span class="at">-c</span>    <span class="co"># audit: duplicate keys, and entries with no abstract</span></span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<p><code>getbib</code> populates the <code>abstract</code> field automatically, and that field is the point. <strong>Each entry stores what the source actually found</strong>, so when I need support for a claim I search my own bibliography and what comes back is a finding rather than a title. A claim followed by <code>[@key]</code> has to be supported by the abstract recorded in that entry. It is the best guard I have against citing a paper for something it does not say, which fluent drafting makes easier rather than harder. Bulgarian sources — NHIS and NHIF releases, legal acts, NCPHA reports — are not in PubMed and have no abstract to fetch, so I write the findings statement by hand or the entry does not get cited at all.</p>
<p>The rest follows the structure in my <a href="../blog/academic-writing-setup.html">writing setup post</a>: numbered scripts produce <code>output/figures/</code> and <code>output/tables/</code>, the manuscript consumes them, no number is ever transcribed by hand, and <code>00_run_all.R</code> regenerates everything from the raw files in one command. <code>kkstatfun</code> occupies exactly one layer of that stack — the layer between a cleaned dataset and a defensible estimate. It is a small layer. It is also the one where the mistakes are hardest to see afterwards, which is why it is the one I automated first.</p>
</section>
</section>
<section id="reproducing-this-post" class="level2">
<h2 class="anchored" data-anchor-id="reproducing-this-post">Reproducing this post</h2>
<p>Everything here runs from a clean R session with the package installed:</p>
<div class="code-copy-outer-scaffold"><div class="sourceCode" id="cb81"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb81-1"><a href="#cb81-1" aria-hidden="true" tabindex="-1"></a><span class="cf">if</span> (<span class="sc">!</span><span class="fu">require</span>(<span class="st">"devtools"</span>)) <span class="fu">install.packages</span>(<span class="st">"devtools"</span>)</span>
<span id="cb81-2"><a href="#cb81-2" aria-hidden="true" tabindex="-1"></a>devtools<span class="sc">::</span><span class="fu">install_github</span>(<span class="st">"kostadinoff/kkstatfun"</span>)</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<p>The <code>.qmd</code> source for this page is in the <a href="https://github.com/kostadinoff/kostadinoff.github.io">website repository</a>; every figure and every number above was produced when it rendered. If you cite the package, the concept DOI <a href="https://doi.org/10.5281/zenodo.18936019">10.5281/zenodo.18936019</a> always resolves to the latest release, or run <code>citation("kkstatfun")</code> for the version you actually used.</p>
<div class="cell" data-layout-align="center">
<details class="code-fold">
<summary>Session info</summary>
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb82"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb82-1"><a href="#cb82-1" aria-hidden="true" tabindex="-1"></a><span class="fu">sessionInfo</span>()<span class="sc">$</span>otherPkgs <span class="sc">|&gt;</span> <span class="fu">names</span>()</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
</details>
<div class="cell-output cell-output-stdout">
<pre><code>#&gt; [1] "survival"  "patchwork" "scales"    "ggplot2"   "dplyr"     "kkstatfun"</code></pre>
</div>
<details class="code-fold">
<summary>Session info</summary>
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb84"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb84-1"><a href="#cb84-1" aria-hidden="true" tabindex="-1"></a><span class="fu">packageVersion</span>(<span class="st">"kkstatfun"</span>)</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
</details>
<div class="cell-output cell-output-stdout">
<pre><code>#&gt; [1] '1.3.0'</code></pre>
</div>
</div>
<div class="callout callout-style-default callout-note callout-titled">
<div class="callout-header d-flex align-content-center">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-title-container flex-fill">
<span class="screen-reader-only">Note</span>Colophon
</div>
</div>
<div class="callout-body-container callout-body">
<p>Written in Quarto, rendered with knitr against R 4.6.0 and <code>kkstatfun</code> 1.3.0. The cohort is synthetic and the hospitals are fictional; the confounding is not. Corrections and disagreements to <a href="mailto:kostadinr.kostadinov@mu-plovdiv.bg">my inbox</a>.</p>
</div>
</div>


</section>

</main> <!-- /main -->
<script id="quarto-html-after-body" type="application/javascript">
  window.document.addEventListener("DOMContentLoaded", function (event) {
    // Ensure there is a toggle, if there isn't float one in the top right
    if (window.document.querySelector('.quarto-color-scheme-toggle') === null) {
      const a = window.document.createElement('a');
      a.classList.add('top-right');
      a.classList.add('quarto-color-scheme-toggle');
      a.href = "";
      a.onclick = function() { try { window.quartoToggleColorScheme(); } catch {} return false; };
      const i = window.document.createElement("i");
      i.classList.add('bi');
      a.appendChild(i);
      window.document.body.appendChild(a);
    }
    setColorSchemeToggle(hasAlternateSentinel())
    const icon = "";
    const anchorJS = new window.AnchorJS();
    anchorJS.options = {
      placement: 'right',
      icon: icon
    };
    anchorJS.add('.anchored');
    const isCodeAnnotation = (el) => {
      for (const clz of el.classList) {
        if (clz.startsWith('code-annotation-')) {                     
          return true;
        }
      }
      return false;
    }
    const onCopySuccess = function(e) {
      // button target
      const button = e.trigger;
      // don't keep focus
      button.blur();
      // flash "checked"
      button.classList.add('code-copy-button-checked');
      var currentTitle = button.getAttribute("title");
      button.setAttribute("title", "Copied!");
      let tooltip;
      if (window.bootstrap) {
        button.setAttribute("data-bs-toggle", "tooltip");
        button.setAttribute("data-bs-placement", "left");
        button.setAttribute("data-bs-title", "Copied!");
        tooltip = new bootstrap.Tooltip(button, 
          { trigger: "manual", 
            customClass: "code-copy-button-tooltip",
            offset: [0, -8]});
        tooltip.show();    
      }
      setTimeout(function() {
        if (tooltip) {
          tooltip.hide();
          button.removeAttribute("data-bs-title");
          button.removeAttribute("data-bs-toggle");
          button.removeAttribute("data-bs-placement");
        }
        button.setAttribute("title", currentTitle);
        button.classList.remove('code-copy-button-checked');
      }, 1000);
      // clear code selection
      e.clearSelection();
    }
    const getTextToCopy = function(trigger) {
      const outerScaffold = trigger.parentElement.cloneNode(true);
      const codeEl = outerScaffold.querySelector('code');
      for (const childEl of codeEl.children) {
        if (isCodeAnnotation(childEl)) {
          childEl.remove();
        }
      }
      return codeEl.innerText;
    }
    const clipboard = new window.ClipboardJS('.code-copy-button:not([data-in-quarto-modal])', {
      text: getTextToCopy
    });
    clipboard.on('success', onCopySuccess);
    if (window.document.getElementById('quarto-embedded-source-code-modal')) {
      const clipboardModal = new window.ClipboardJS('.code-copy-button[data-in-quarto-modal]', {
        text: getTextToCopy,
        container: window.document.getElementById('quarto-embedded-source-code-modal')
      });
      clipboardModal.on('success', onCopySuccess);
    }
      var localhostRegex = new RegExp(/^(?:http|https):\/\/localhost\:?[0-9]*\//);
      var mailtoRegex = new RegExp(/^mailto:/);
        var filterRegex = new RegExp("https:\/\/kostadinoff\.github\.io");
      var isInternal = (href) => {
          return filterRegex.test(href) || localhostRegex.test(href) || mailtoRegex.test(href);
      }
      // Inspect non-navigation links and adorn them if external
     var links = window.document.querySelectorAll('a[href]:not(.nav-link):not(.navbar-brand):not(.toc-action):not(.sidebar-link):not(.sidebar-item-toggle):not(.pagination-link):not(.no-external):not([aria-hidden]):not(.dropdown-item):not(.quarto-navigation-tool):not(.about-link)');
      for (var i=0; i<links.length; i++) {
        const link = links[i];
        if (!isInternal(link.href)) {
          // undo the damage that might have been done by quarto-nav.js in the case of
          // links that we want to consider external
          if (link.dataset.originalHref !== undefined) {
            link.href = link.dataset.originalHref;
          }
        }
      }
    function tippyHover(el, contentFn, onTriggerFn, onUntriggerFn) {
      const config = {
        allowHTML: true,
        maxWidth: 500,
        delay: 100,
        arrow: false,
        appendTo: function(el) {
            return el.parentElement;
        },
        interactive: true,
        interactiveBorder: 10,
        theme: 'quarto',
        placement: 'bottom-start',
      };
      if (contentFn) {
        config.content = contentFn;
      }
      if (onTriggerFn) {
        config.onTrigger = onTriggerFn;
      }
      if (onUntriggerFn) {
        config.onUntrigger = onUntriggerFn;
      }
      window.tippy(el, config); 
    }
    const noterefs = window.document.querySelectorAll('a[role="doc-noteref"]');
    for (var i=0; i<noterefs.length; i++) {
      const ref = noterefs[i];
      tippyHover(ref, function() {
        // use id or data attribute instead here
        let href = ref.getAttribute('data-footnote-href') || ref.getAttribute('href');
        try { href = new URL(href).hash; } catch {}
        const id = href.replace(/^#\/?/, "");
        const note = window.document.getElementById(id);
        if (note) {
          return note.innerHTML;
        } else {
          return "";
        }
      });
    }
    const xrefs = window.document.querySelectorAll('a.quarto-xref');
    const processXRef = (id, note) => {
      // Strip column container classes
      const stripColumnClz = (el) => {
        el.classList.remove("page-full", "page-columns");
        if (el.children) {
          for (const child of el.children) {
            stripColumnClz(child);
          }
        }
      }
      stripColumnClz(note)
      if (id === null || id.startsWith('sec-')) {
        // Special case sections, only their first couple elements
        const container = document.createElement("div");
        if (note.children && note.children.length > 2) {
          container.appendChild(note.children[0].cloneNode(true));
          for (let i = 1; i < note.children.length; i++) {
            const child = note.children[i];
            if (child.tagName === "P" && child.innerText === "") {
              continue;
            } else {
              container.appendChild(child.cloneNode(true));
              break;
            }
          }
          if (window.Quarto?.typesetMath) {
            window.Quarto.typesetMath(container);
          }
          return container.innerHTML
        } else {
          if (window.Quarto?.typesetMath) {
            window.Quarto.typesetMath(note);
          }
          return note.innerHTML;
        }
      } else {
        // Remove any anchor links if they are present
        const anchorLink = note.querySelector('a.anchorjs-link');
        if (anchorLink) {
          anchorLink.remove();
        }
        if (window.Quarto?.typesetMath) {
          window.Quarto.typesetMath(note);
        }
        if (note.classList.contains("callout")) {
          return note.outerHTML;
        } else {
          return note.innerHTML;
        }
      }
    }
    for (var i=0; i<xrefs.length; i++) {
      const xref = xrefs[i];
      tippyHover(xref, undefined, function(instance) {
        instance.disable();
        let url = xref.getAttribute('href');
        let hash = undefined; 
        if (url.startsWith('#')) {
          hash = url;
        } else {
          try { hash = new URL(url).hash; } catch {}
        }
        if (hash) {
          const id = hash.replace(/^#\/?/, "");
          const note = window.document.getElementById(id);
          if (note !== null) {
            try {
              const html = processXRef(id, note.cloneNode(true));
              instance.setContent(html);
            } finally {
              instance.enable();
              instance.show();
            }
          } else {
            // See if we can fetch this
            fetch(url.split('#')[0])
            .then(res => res.text())
            .then(html => {
              const parser = new DOMParser();
              const htmlDoc = parser.parseFromString(html, "text/html");
              const note = htmlDoc.getElementById(id);
              if (note !== null) {
                const html = processXRef(id, note);
                instance.setContent(html);
              } 
            }).finally(() => {
              instance.enable();
              instance.show();
            });
          }
        } else {
          // See if we can fetch a full url (with no hash to target)
          // This is a special case and we should probably do some content thinning / targeting
          fetch(url)
          .then(res => res.text())
          .then(html => {
            const parser = new DOMParser();
            const htmlDoc = parser.parseFromString(html, "text/html");
            const note = htmlDoc.querySelector('main.content');
            if (note !== null) {
              // This should only happen for chapter cross references
              // (since there is no id in the URL)
              // remove the first header
              if (note.children.length > 0 && note.children[0].tagName === "HEADER") {
                note.children[0].remove();
              }
              const html = processXRef(null, note);
              instance.setContent(html);
            } 
          }).finally(() => {
            instance.enable();
            instance.show();
          });
        }
      }, function(instance) {
      });
    }
        let selectedAnnoteEl;
        const selectorForAnnotation = ( cell, annotation) => {
          let cellAttr = 'data-code-cell="' + cell + '"';
          let lineAttr = 'data-code-annotation="' +  annotation + '"';
          const selector = 'span[' + cellAttr + '][' + lineAttr + ']';
          return selector;
        }
        const selectCodeLines = (annoteEl) => {
          const doc = window.document;
          const targetCell = annoteEl.getAttribute("data-target-cell");
          const targetAnnotation = annoteEl.getAttribute("data-target-annotation");
          const annoteSpan = window.document.querySelector(selectorForAnnotation(targetCell, targetAnnotation));
          const lines = annoteSpan.getAttribute("data-code-lines").split(",");
          const lineIds = lines.map((line) => {
            return targetCell + "-" + line;
          })
          let top = null;
          let height = null;
          let parent = null;
          if (lineIds.length > 0) {
              //compute the position of the single el (top and bottom and make a div)
              const el = window.document.getElementById(lineIds[0]);
              top = el.offsetTop;
              height = el.offsetHeight;
              parent = el.parentElement.parentElement;
            if (lineIds.length > 1) {
              const lastEl = window.document.getElementById(lineIds[lineIds.length - 1]);
              const bottom = lastEl.offsetTop + lastEl.offsetHeight;
              height = bottom - top;
            }
            if (top !== null && height !== null && parent !== null) {
              // cook up a div (if necessary) and position it 
              let div = window.document.getElementById("code-annotation-line-highlight");
              if (div === null) {
                div = window.document.createElement("div");
                div.setAttribute("id", "code-annotation-line-highlight");
                div.style.position = 'absolute';
                parent.appendChild(div);
              }
              div.style.top = top - 2 + "px";
              div.style.height = height + 4 + "px";
              div.style.left = 0;
              let gutterDiv = window.document.getElementById("code-annotation-line-highlight-gutter");
              if (gutterDiv === null) {
                gutterDiv = window.document.createElement("div");
                gutterDiv.setAttribute("id", "code-annotation-line-highlight-gutter");
                gutterDiv.style.position = 'absolute';
                const codeCell = window.document.getElementById(targetCell);
                const gutter = codeCell.querySelector('.code-annotation-gutter');
                gutter.appendChild(gutterDiv);
              }
              gutterDiv.style.top = top - 2 + "px";
              gutterDiv.style.height = height + 4 + "px";
            }
            selectedAnnoteEl = annoteEl;
          }
        };
        const unselectCodeLines = () => {
          const elementsIds = ["code-annotation-line-highlight", "code-annotation-line-highlight-gutter"];
          elementsIds.forEach((elId) => {
            const div = window.document.getElementById(elId);
            if (div) {
              div.remove();
            }
          });
          selectedAnnoteEl = undefined;
        };
          // Handle positioning of the toggle
      window.addEventListener(
        "resize",
        throttle(() => {
          elRect = undefined;
          if (selectedAnnoteEl) {
            selectCodeLines(selectedAnnoteEl);
          }
        }, 10)
      );
      function throttle(fn, ms) {
      let throttle = false;
      let timer;
        return (...args) => {
          if(!throttle) { // first call gets through
              fn.apply(this, args);
              throttle = true;
          } else { // all the others get throttled
              if(timer) clearTimeout(timer); // cancel #2
              timer = setTimeout(() => {
                fn.apply(this, args);
                timer = throttle = false;
              }, ms);
          }
        };
      }
        // Attach click handler to the DT
        const annoteDls = window.document.querySelectorAll('dt[data-target-cell]');
        for (const annoteDlNode of annoteDls) {
          annoteDlNode.addEventListener('click', (event) => {
            const clickedEl = event.target;
            if (clickedEl !== selectedAnnoteEl) {
              unselectCodeLines();
              const activeEl = window.document.querySelector('dt[data-target-cell].code-annotation-active');
              if (activeEl) {
                activeEl.classList.remove('code-annotation-active');
              }
              selectCodeLines(clickedEl);
              clickedEl.classList.add('code-annotation-active');
            } else {
              // Unselect the line
              unselectCodeLines();
              clickedEl.classList.remove('code-annotation-active');
            }
          });
        }
    const findCites = (el) => {
      const parentEl = el.parentElement;
      if (parentEl) {
        const cites = parentEl.dataset.cites;
        if (cites) {
          return {
            el,
            cites: cites.split(' ')
          };
        } else {
          return findCites(el.parentElement)
        }
      } else {
        return undefined;
      }
    };
    var bibliorefs = window.document.querySelectorAll('a[role="doc-biblioref"]');
    for (var i=0; i<bibliorefs.length; i++) {
      const ref = bibliorefs[i];
      const citeInfo = findCites(ref);
      if (citeInfo) {
        tippyHover(citeInfo.el, function() {
          var popup = window.document.createElement('div');
          citeInfo.cites.forEach(function(cite) {
            var citeDiv = window.document.createElement('div');
            citeDiv.classList.add('hanging-indent');
            citeDiv.classList.add('csl-entry');
            var biblioDiv = window.document.getElementById('ref-' + cite);
            if (biblioDiv) {
              citeDiv.innerHTML = biblioDiv.innerHTML;
            }
            popup.appendChild(citeDiv);
          });
          return popup.innerHTML;
        });
      }
    }
  });
  </script>
</div> <!-- /content -->
<footer class="footer">
  <div class="nav-footer">
    <div class="nav-footer-left">
<p>Email me at <a href="mailto:kostadinr.kostadinov@mu-plovdiv.bg">kostadinr.kostadinov@mu-plovdiv.bg</a> or book a <a href="https://tinyurl.com/whentomeetme" target="_blank">meeting</a></p>
</div>   
    <div class="nav-footer-center">
      &nbsp;
    </div>
    <div class="nav-footer-right">
<p>Built with <a href="https://quarto.org" target="_blank">Quarto</a></p>
</div>
  </div>
</footer>




</body></html>