---
title: "Medical ethics - Introduction and principles"
author: "Kostadin Kostadinov"
date: 2024-11-04
description: "The first practical class on medical ethics. Introduction to the field and the basic principles of medical ethics."
categories: 
  - "English"
  - "Ethics"
  - "Class 1"
  - "Principles"
  - "Terminology"
title-meta: "Medical ethics - Introduction and principles"
author-meta: "Kostadin Kostadinov"
date-meta: 2024-11-03
---

# Ethics - definition and principles

## Background

Doctors have been concerted with ethics since the earliest days of medical practice. Traditionally, medical practitioners have been expected to be motivated by a desire to help their patients. Ethical codes and systems, such as the **Hippocratic oath**, have emphasized this.

During the latter half of the twentieth century, advances in medical science, in conjunction with social and political changes, meant that the accepted conventions of the doctor-patient relationship were increasingly being questioned. After the *Nuremberg trials*, in which the crimes of Nazi doctors, among others, were exposed, it became clear that doctors cannot be assumed to be good simply by virtue of their profession.

## Definitions

### Ethics

Ethics is a study of **morality** and defining what is right or wrong. One's first experience with ethics comes from family, religion, background, historical perspective, personal training, and education.

#### Medical ethics vs. Bioethics

**'Medical ethics'** is one subset of the broader disciplines of 'healthcare ethics' and 'bioethics'. It overlaps with both but focuses on the duties of doctors. The original Greek and Latin expressions for 'ethics' and 'morals' conveyed the same idea of a code of conduct acceptable to a particular group.

Nowadays,'ethics' can either mean **conforming to recognized standards of practice** or describe the general **study of morality**. Traditionally, professional ethics was what doctors defined for themselves, from their own perspective. Their duty was to work to the standards established by their peers and avoid any action that would bring the profession into disrepute. Ethics, in this sense, has always been a central concern of medicine.

The key difference between **bioethics** and medical ethics is that bioethics generally is concerned the moral principles of all **biomedical technologies**, such as cloning, stem cell therapy, xenotransplantation and the use of animal models in research while medical ethics is more specific and focused on everyday clinical practice.

#### Ethical Theories

##### Utilitarian Ethics/ Consequentialism

Consequentialism, as its name suggests, is a theory whose focus is purely on the **outcome of an action**. For a consequentialist, the only question to be asked when seeking a moral reason for doing something is *'What is the result?'* The most famous form of consequentialism is utilitarianism: 'an act is morally right if it maximizes the good' (the terms consequentialism and utilitarianism are commonly used interchangeably).

::: {.callout-note collapse="false" appearance="default" icon="false"}
## Utilitarian Ethics {.unnumbered}

*Using the available means, act in such a way as to do as much good as possible*
:::

The basic principle of utilitarian ethics is do good, which is the oldest and most straightforward ethical principle. Utilitarian ethic is useful primarily in catastrophic situations. In times of war, earthquakes, or other major accidents, we have to save as many lives as possible in the shortest amount of time with very limited means. In a rational triage, one would group the wounded into those with minor wounds and injuries who can wait and those who require that we urgently stop their bleeding, clear their airways or prevent further aggravation of their health condition. Utilitarian ethics also offers appropriate advice to activities in the field of public health and preventive medicine.

Consequentialism makes no distinction between acts and omissions. The outcome of choosing not to do something is just as significant for a consequentialist as the outcome of an act that one has chosen to perform. This means that the scope of our moral obligations may seem unfeasibly large[^1]

[^1]: If I fail to send food to a starving person in a distant country who then dies, I may feel that this is very different from deliberately ending that person's life. Yet the consequences are the same in both cases.

Another counterintuitive aspect of consequentialism is its apparent imperviousness to considerations of justice. Suppose that we knew for a fact that capital punishment functions effectively as a deterrent: for each person executed, five murderers are deterred. To save resources, we might seize upon any random person, decree that they are the murderer, and execute them. Not only would this have the same deterrent effect, but it would also save police time and money since they would not need to track down the real culprit. A consequentialist would not worry about this, since the overall outcome may be deemed to outweigh the fact that one innocent person has been killed. But for many people, the injustice committed on the innocent man outweighs the beneficial consequences.

##### Communitarian ethics

Communitarianism focuses on the fact that people have responsibilities as well as rights. It advocates policies based on consensus rather than compromise. It asserts that individuals need to concentrate not only on their own rights, but also their responsibilities to people close to them and to community. Communitarian arguments expect a concern for others to be taken into account when decisions are made. This approach comes to the fore when considering the health of communities rather than individuals. It is particularly relevant to public health ethics, genetics and any situation in which an important factor is the interrelatedness of individuals and of their interests.

##### Deontological Ethics

The word 'deontology' stems from the Greek for 'duty'. **In contrast to consequentialism**, a deontologist approaches ethical questions by identifying and adhering to predefined moral rules, or duties. Once we have established what our duty is, we must perform it, regardless of what the outcome may be. However, this raises the question of how we establish what our duties are.

The German philosopher **Immanuel Kant** argues that we can establish our moral duty purely through the exercise of reason without having to derive them from any theological source. This is known as 'the categorical imperative'. To achieve this, Kant urges that in all of our decisions we should always behave in such a way that we could will for what we do to become a universal law. This means that we cannot treat our own interests as being superior to those of others. It also means that moral duties are consistent and non-arbitrary - they apply to everyone equally.

In utilitarian ethics, the most prominent status is given to the principle of **beneficence**. Kantian ethics, however, leads us to appreciate the individual, one's free will, and rational responsibility for one's decisions - the most important is, therefore, the ethical principle of the respect for **autonomy**. By requiring one to follow, without exception, universal rules, Kant excluded emotions and interpersonal relations from entering ethical reflections. Even more: an act is ethical only if the motivation comes from the general rule. If done from fear or love, the ethical value of the same act is neutral. In Kantian ethics, there is no place for compromise and no weighing of motivations for acting against the consequences, regardless of how predictable, and thus avoidable, the latter could be.

##### Virtue Ethics

In ethical assessment, utilitarians look at the consequences of a particular act, and deontological ethicists at the conformity of the act with pre-defined rules. Virtue ethics stands in a different position: **it's foundation is the ethical characteristics of a person**. Certain personal characteristics are recognized as virtues[^2] and others as vices. Honesty, generosity, compassion, courage, justice, fidelity, and veracity are virtues that characterize an ethical person, while deception, selfishness, cruelty, infidelity, and disingenuousness are some of the many characteristics that denote a vicious person.Virtue ethics is now regarded as being one of the three key moral theories, along with consequentialism and deontology.

[^2]: Virtue ethicists regard virtues as being a balance between extremes. Courage, for example, lies midway between the extremes of cowardice on the one hand, and recklessness on the other. Applying this to medical ethics, we might say that a doctor who lacks courage may not fulfil our idea of what it means to be a virtuous doctor; they might not be willing to challenge accepted practices or protocols. A doctor who is overly courageous on the other hand might be unable to recognize the risks that she is embracing. She may become arrogant in her conviction that her way is right.

However, virtue ethics requires fundamentally that we have an idea of what the virtues are, and this can be difficult to establish. Certainly, Aristotle's idea of the virtues does not necessarily harmonize with twenty-first century values. (Along with many other Greeks of his time, Aristotle thought that keeping slaves was perfectly compatible with being virtuous, and believed that women were intrinsically inferior to men.)

Virtue ethics may be seen as an upgrading of utilitarian and deontological ethics. While virtues are in a central position, the incorporation of practical wisdom also rings consequences into virtue ethics. The rules of deontological ethics are important, yet not unbreakable. Finally, the main advantage of virtue ethics over the other two theories is that it includes human relations, and indeed gives a central position to them, a factor that has a decisive role in the practical reasoning of all of us.

##### Narrative ethics

Another practical approach is to use **narrative** or storytelling in order to give the problem context and clarify the ethical crux of it. This has been described as 'the oldest way of exploring and expounding ethical issues' through myth, parable or biography. It approaches problems by looking at the patient's situation as a whole rather than considering a particular facet in isolation. It can involve an overview of the patient's life, values and experiences of illness. Different health professionals and family members may present the picture from different angles and considering the same dilemma from such various viewpoints provides a way of ensuring that all relevant perspectives and perceptions are considered.

### Medical law vs. Medical ethics.

While laws are influenced by ethics, the two can contradict one another in a healthcare setting. Law is based on explicit, written norms with a clear system for enacting such norms. Legal norms (approved international agreements, national constitutions, laws, and regulations) are organized hierarchically, should be mutually consistent, have a clearly defined spatial scope of their enactment, and can only apply to actions committed after the legal norm has been enacted. When an individual violates a specific legal norm, clearly defined procedures for establishing guilt and prescribed sanctions are in place.

Sometimes,legal duties as a healthcare professional can conflict with ethical responsibilities. The law may force ones do things their ethics just don't condone. Or ones may want to do something because it's ethical, but the law isn't on their side.

## The Four Principles and Common Morality Ethics

Existing ethical theories do not necessarily give easy answers to moral problems and, indeed, can yield counterintuitive results if pushed to their logical extremes. There is also the problem that moral values differ according to culture and context. What if the doctor is a deontologist, and the patient a consequentialist? Increasingly, in modern medicine, doctors may be treating patients who speak a different language, come from a different country, or practise a different religion. In short, patients' values may be radically different from those of the doctor, and those of one doctor may differ from those of their colleagues.

The 'four principles' approach was developed partly in response to this problems, however the approach is not an ethical theory per se. Rather, it attempts to set out certain key considerations which are independent of social, cultural, or religious contexts. Since its inception in the twentieth century, the four principles approach has become extremely influential and is now the **dominant framework** for medical ethics teaching.

The principles in question are:

1.  Autonomy of the individual
2.  Non-maleficence
3.  Beneficence
4.  Justice

As suggested, these principles are more properly understood as a distillation of other ethical theories, synthesized and reformatted for use in the medical setting.

### Autonomy

::: {.callout-note collapse="false" appearance="default" icon="false"}
## Autonomy {.unnumbered}

*Providing information to patients and allowing them to make their own decisions*
:::

Autonomy means **self-governance**: making and carrying out one's own decisions. The importance of respect for autonomy is implicit or explicit in nearly all moral theories. With changing social expectations and, arguably, less hierarchical social and political structures, respect for autonomy has grown in importance, and is regarded by some as the **cornerstone of the four principles**. Autonomy is at the **root of many of the fundamental requirements of good medical practice**.

The autonomy of the individual includes the **right to being informed** (for there is no autonomy without information) and the **right to confidentiality and privacy** (otherwise other parties might influence an individual's decisions without considering his or her will).

The principle of respect for autonomy **is not absolute**, but there is heated debate about how and when it should be overridden by other principles. What does seem clear is that it will inevitably clash with one or more of the other three principles at times. Resolving these clashes is one of the major preoccupations of medical ethicists and medical practitioners.

### Beneficence

Beneficence is the act of helping people, or benefiting them.

::: {.callout-note collapse="false" appearance="default" icon="false"}
## Beneficence {.unnumbered}

*Undertaking actions intended to benefit the patient*
:::

Beneficence encapsulates what many people regard as **the essence of medicine**. Doctors are not here to function as servants, mechanics, shopkeepers, or teachers for their patients. Rather, their unique and special role is **to help people, cure disease, relieve distress and suffering, prolong lives, and improve health**. It has been argued that in this respect, doctors are radically different from other professionals.[^3]

[^3]: An off-duty plumber has no moral obligation to fix a dripping radiator in a restaurant where he is eating. But an off-duty doctor, it is commonly assumed, does have a moral obligation to attend to someone who suffers a heart attack at the restaurant where he is eating.

As medical technology and life-preserving interventions have proliferated, it has become evident that patients and doctors have extremely **divergent views on the beneficence** of life-prolonging measures. Some argue passionately for the continuance of treatment, while others argue that there are situations in which the patient cannot be benefited by being kept alive. Problems arise when a patient's view of what is 'beneficent' differs from that of the doctor. We have seen that respect for autonomy is an essential component of the four principles. But a doctor may find it difficult, if not impossible, to respect the autonomy of a patient whose concept of beneficence is radically different

### Non-maleficence

Non-maleficence is the principle of preventing or **avoiding harm** to others.

::: {.callout-note collapse="false" appearance="default" icon="false"}
## Non-maleficence {.unnumbered}

*Acting so as to avoid harming the patient*
:::

Non-maleficence is sometimes regarded as the **primary ethical principle** to which doctors should adhere. It features in the Hippocratic oath, and it reappears in the common phrase *'primum non nocere'* (from Latin: first, do no harm). The importance of this principle stems largely from the recognition that those same skills which allow a doctor to improve a patient's health or well-being, can in themselves cause damage, pain, or sickness. Yet the injunction 'first do no harm' is perhaps too extreme. After all, if this really were a doctor's first and primary obligation, they would not be able to do anything at all. It is impossible to think of any medical procedure or intervention that is entirely without risk. A simple vaccination causes harm by puncturing the skin; even screening may cause harm in the form of anxiety or a false-positive result. For this reason, it is clear that **non-maleficence cannot function as medicine's primary principle**; rather, it serves as a **balance against beneficence**. Beneficence is an active principle - it calls for doctors to intervene to benefit their patients. Non-maleficence is a **passive and cautionary principle** that reminds doctors to think about the harm they may cause by intervening. 

Questions of how to interpret "*harm*" also arise in the public health context. In recent years, some criticisms have been raised regarding breast screening. Frequently, screening programmes are justified on the ground that they save lives by detecting diseases which might otherwise have gone unnoticed until too late. However, in the breast screening context, it has been suggested that the screening programme causes excessive and unjustified interventions. In short, it causes harm. Some patients have biopsies only to discover there was nothing wrong. Others may have cancer detected, but in circumstances where the disease would never have become symptomatic. For example, if a very elderly patient has a very slow-growing cancer, it is highly unlikely that it will kill her. The question of whether such inadvertent harms outweigh the benefits of screening programmes is fraught. These problems, of course, also affect other moral theories that rely on concepts of harm, in particular consequentialism

### Justice

Justice is the principle of treating others **fairly**, avoiding discrimination and distributing resources equally.

::: {.callout-note collapse="false" appearance="default" icon="false"}
## Non-maleficence {.unnumbered}

*Avoiding discrimination, distributing re- sources fairly*
:::

Justice differs from the three principles already discussed. Autonomy, beneficence, and non-maleficence are highly patient centred. However, most moral theories recognize that the individual is not the sole ethical concern. By its very nature, ethics is a social phenomenon, meaning that questions of fairness come into play. There are two primary ways in which the principle of justice affects ethical decision-making in medicine. Firstly, there is the issue of how other people may be affected by a particular decision. Secondly, there is the question of discrimination: do some patients receive better or worse treatment than others?

To comply with the requirements of justice, it is important that decision - making is **transparent and consistent**. This can be difficult in complex healthcare systems, serving patients whose needs and values vary widely.

The other facet of justice is **discrimination**. It is often assumed that discrimination is intrinsically wrong. Yet, if we never discriminated, we would be unable to function at all. Remembering Aristotle's injunction, '*treat equals equally and unequals unequally'*, it is clear that discrimination in itself is not a problem. It would be unjust to treat a patient with a broken neck exactly the same as one with a broken finger. Where needs are different, we should treat people differently. This involves discriminating: noticing those differences and making decisions accordingly.

**Discrimination is only a problem when it is unjust**. We have suggested it is appropriate to discriminate between patients with different needs; however, if it were decided that only dark-haired patients would be treated, this would clearly be unjust, since there is no connection between hair colour and need for treatment. The challenge, therefore, is **to be able to recognize what are, and what are not, the sorts of inequalities that justify treating people differently**

## Ethical Analysis

Real ethical dilemmas are those for which every possible action (including the omission of action) brings some ethical costs to a person, or to a group of people involved. Ethical analysis **begins with a list of persons involved** and then explores, for each of them, the **ethical benefits and costs of a certain action** according to the **four ethical principles**: autonomy, beneficence, non-maleficence, and justice. In this way, two or more possible actions with their ethical benefits and costs are compared. Ethical analysis **does not** automatically lead to the recommended action; rather, it is a practical approach to analyse a dilemma, identify the problematic aspects of each of the possible actions, and alleviate the related ethical costs.

If an act exists that will benefit all concerned and will not offend anybody, including oneself, then ethics or ethical analysis is not needed. Ethical consideration is also not applicable to situations in which the actor has no choice. Very often, however, we do have a choice; nevertheless, each act brings some benefits and some burdens to the persons whom the act involves. 

Ethical analysis is helpful in such situations. The three steps of ethical analysis are:

1.  A **list of possible actions**
2.  **List of persons or groups of persons** whom the actions concern
3.  Preparing a **table** with rows for each person or group of persons concerned and columns for the four ethical principles: autonomy, non-maleficence, beneficence, and justice

::: {.callout-tip collapse="false" appearance="default" icon="false"}
## Example 1 {.unnumbered}

Marco, aged 3, was seriously hurt in a traffic accident. Upon arrival to the intensive-care unit, he is in severe hemorrhagic shock. His father, a **Jehovah's Witness**, prohibits blood transfusion, even after being told that immediate blood transfusion, followed by an operation is the only possibility for survival. The physician has to decide whether he will order blood transfusion or follow the father's demand.
:::

1. The possible actions are **blood transfusion** against the father's will or **no transfusion**. 
2. The persons involved are **Marco, his family, and the physician**. In addition, we will also add to the list the community of Jehovah's Witnesses since they might be hurt if they learn that their religious belief was ignored. This brings us to the following table:

+----------------------------+------------+-----------------+-------------+------------+
|                            | Autonomy   | Non-maleficence | Beneficence | Justice    |
+:===========================+:==========:+:===============:+:===========:+:==========:+
| Marco                      |            |                 |             |            |
+----------------------------+------------+-----------------+-------------+------------+
| Marco's family             |            |                 |             |            |
+----------------------------+------------+-----------------+-------------+------------+
| Physician                  |            |                 |             |            |
+----------------------------+------------+-----------------+-------------+------------+
| The community of Jehovah's |            |                 |             |            |
|                            |            |                 |             |            |
| Witnesses                  |            |                 |             |            |
+----------------------------+------------+-----------------+-------------+------------+

The physician's decision to apply blood transfusion against the father's will is to be compared to the alternative option - no transfusion, which would almost certainly lead to Marco's death. We will now insert ethical benefits, marked with a **"+"**, and ethical costs, marked with a **"−"**. Assessment of ethical benefits and costs is clearly subjective; however, **subjectivity is an unavoidable characteristic of every ethical deliberation**.

+--------------------------------------+-----------+-----------------+-------------+-----------+
|                                      | Autonomy  | Non-maleficence | Beneficence | Justice   |
+:=====================================+:=========:+:===============:+:===========:+:=========:+
| Marco                                | ?         | +++             | +++         | ++        |
+--------------------------------------+-----------+-----------------+-------------+-----------+
| Marco's family                       | \-\--     | +++             | +++         | ++        |
+--------------------------------------+-----------+-----------------+-------------+-----------+
| Physician                            | +++       | ++              | ++          |           |
+--------------------------------------+-----------+-----------------+-------------+-----------+
| The community of Jehovah's Witnesses | --        | \+              | \+          | \+        |
+--------------------------------------+-----------+-----------------+-------------+-----------+

As we can see, the ethical benefits of a transfusion against the father's demand **greatly outweigh the ethical costs**. The physician in the intensive-care unit has to make decisions without delay which gives Marco a chance for survival.

::: {.callout-tip collapse="false" appearance="default" icon="false"}
# Example 2 {.unnumbered}

Damian, aged 12, has been treated for neuroblastoma for two years. Despite intensive treatment with three lines of cytotoxic drugs, he is now in relapse. Physicians agree that there is no indication for further active treatment and recommend only supportive and palliative treatment. Due to anaemia, Damian is weak and dizzy. A blood transfusion might lead to short-term improvement of his symptoms but clearly cannot reverse the course of the disease. As Jehovah's Witnesses, his parents refuse blood transfusion.
:::

The possible actions are a transfusion against the parents' will or no transfusion. The persons involved are Damian, his family, the physician, and the community of Jehovah's Witnesses. Here is the table, as prepared for the decision to order blood transfusion against the will of the parents.

+--------------------------------------+-----------+-----------------+-------------+-----------+
|                                      | Autonomy  | Non-maleficence | Beneficence | Justice   |
+:=====================================+:=========:+:===============:+:===========:+:=========:+
| Damian                               | \--       | ?               | \+          | ?         |
+--------------------------------------+-----------+-----------------+-------------+-----------+
| Damian's family                      | \-\--     | \--             | \--         | \-\--     |
+--------------------------------------+-----------+-----------------+-------------+-----------+
| Physician                            | \+        | ?               | ?           | ?         |
+--------------------------------------+-----------+-----------------+-------------+-----------+
| The community of Jehovah's Witnesses | \-\--     | \-\--           | \--         | \-\--     |
+--------------------------------------+-----------+-----------------+-------------+-----------+

As we can see, the transfusion brings very **few benefits** and **severe ethical costs**, which no lengthy explanation can reduce. As a teenager, Damian understands the religion in which he was raised. For the parents, the extremely painful experience of the imminent death of their child would be even worse due to a lack of respect from physician's side. Their sorrow and anger might spread to the whole community of Jehovah's Witnesses.

It is clear that ethical analysis involves both **ethical and professional arguments** and it is a strong tool against one-sided presentation of ethical dilemmas. Attention to a single dimension, most often to respect for individual autonomy, should not obscure the ethical benefits and costs for other persons whose interests are also at stake. It is clear that ethical benefits and costs are **subject to individual interpretation**. **Ethics is not mathematics**, and conclusions from an ethical analysis may be debatable, based on different professional arguments. Thus, ethical analysis **does not provide a single answer**, but rather a framework for balancing and reaching a rational conclusion.

## Case Study 

Ten medical students are learning how to perform rectal examinations. This is important for their education. However, no one likes undergoing a rectal examination unnecessarily. To ensure that students get the necessary practice, the consultant who is teaching them is trying to decide whether to allow these ten students to practise a rectal examination on 96-year-old anaesthetized woman who is undergoing surgery for an unrelated issue. The woman, who has mental capacity, has not been informed nor has she given consent. Is this ethically acceptable?

### Virtue ethics

Performing a medical procedure on a patient who has not agreed to this may seem deceptive. Doctors are usually expected to be **honest and trust-worthy** and act with integrity. These are **virtues** that are explicitly required by the General Medical Council (GMC). Nevertheless, students may be well motivated in wanting to carry out the procedure: doing so should enable them to be better doctors in future. It seems reasonable to suppose that no one has ill intentions towards the patient in question; the procedure is not intended to harm her, and she need never know what has been done to her. However, a wise consultant may be able to exercise a more discerning judgement. Although no ill intention is involved, harm may come to the patient. Such harm, if she was not asked for her consent, will come as a shock. Though a very low-risk procedure, a rectal examination is something that carries a strong taboo in our society. The patient if she discovers she has undergone this may feel outraged or violated. We can never be entirely sure that a patient will not discover something we would prefer was kept secret. The patient's virtues should also be considered here. If she had been asked, and had agreed to let the students examine her, this would have been a virtuous decision on her part. However, if the students examine her without her knowledge or consent, she has no opportunity to exercise virtue.

### Consequentialist Ethics

For a consequentialist, the question of whether the patient agrees to undergo the procedure is irrelevant. As long as she never finds out, **no harm is done**. If the action benefits ten medical students, this may be enough. Although, of course, it would be different if the procedure causes the patient harm (as it might on a 96-year-old patient), then the procedure could not be justified. However, a utilitarian must also consider the harm that might arise if the patient does find out - the patient may be distressed and angry. Patient negative experience could outweigh the benefit to the medical students. There are also broader harms and benefits to consider. If patients learn that they may be 'practised on' while under anaesthetic, they may lose trust in hospitals. But if no one ever finds out, perhaps overall large numbers of patients could benefit, since students will have the chance to improve their skills. If we could be 100% certain that the patient would never find out, the consequentialist would be completely happy to advise the ten students to proceed with their examination

### Deontology

It should immediately be apparent that a deontologist would not allow medical students to practise on an unconscious patient without her consent. This would be disregarding her autonomy, as well as being deceptive. However, would obtaining consent in advance make a difference, given that students would still be 'using' the patient for their own practice? Given the previous points about autonomy and consent, it seems plausible that a deontologist would be happy for the students to practise on the patient if she had consented in advance. If the patient consents, she shares in the ends of the students, that is, their desire to become better doctors, and this becomes one of her own ends.

### The four principles

Clearly, performing examinations on a patient without her consent is not in keeping with respect for autonomy. However, if this is known to be a teaching hospital, perhaps we could assume that consent to training is implied by this patient's presence in the hospital. If so, then the procedure may not be deemed to breach the patient's autonomy at all.

One might argue that the procedure is non-maleficent, and could even be beneficent if by chance it picks up something that would otherwise have gone unnoticed. It could also be argued that the broader benefits of carrying out such training in terms of improving population health could be taken to outweigh the other principles, that is, justice might decree that all patients should be willing to undergo this kind of thing for the sake of a wider population benefit.

However, there are a number of issues to consider here. The first issue is whether it is reasonable to infer consent from a patient's presence in a teaching hospital. Doctors often make this argument, but it is highly questionable. Many members of the public may not be aware of whether their nearest hospital is a teaching hospital or not. Even if they are, there is no reason to assume that they will know that this means they will be exposed to students' examinations. Therefore, unless the patient has been explicitly consulted, it is not reasonable to suppose that she has somehow consented to being examined while under anaesthetic.

The arguments related to beneficence and non-maleficence likewise seem weak when probed further. It is unlikely that the examinations will cause harm; yet there is always some degree of risk and this may be exacerbated by the patient's anger and distress if she feels she's been abused or deceived.

The question about beneficence is very significant here. Some patients do not wish to know if they have a particular condition, and would choose not to attend screening programmes for this reason. The know-ledge of having a serious medical condition, though regarded as beneficial by many people, can be regarded as harmful by others. This is why people are offered screening, rather than being compelled to participate. If something sinister were identified in this woman, we do not know if she would be grateful or angry and upset about having been denied a choice.

Finally, it is undoubtedly an admirable thing to participate in research or training. Surprisingly many patients are willing to do this when asked directly. Their choice to be involved may be described as truly altruistic. But when no choice is given, the act is not altruistic. There may also be questions to ask about why this patient in particular is being selected for this training. This is where considerations of justice can be extremely useful in identifying hidden ethical problems. What role is this patient's age playing here? Has she been chosen as an 'easy' option?

+----------------------+-----------+-----------------+-------------+-----------+
|                      | Autonomy  | Non-maleficence | Beneficence | Justice   |
+:=====================+:=========:+:===============:+:===========:+:=========:+
| Patient              | -/?       | \-              | \+          | \-\--     |
+----------------------+-----------+-----------------+-------------+-----------+
| Students             | \+        | \-\--           | +++         | \+        |
+----------------------+-----------+-----------------+-------------+-----------+

