---
title: "Ethical issues in organ transplantation"
author: "Kostadin Kostadinov"
date: 2024-12-08
description: "Organ transplantation replaces failing organs with functioning ones from donors, either living, deceased, or animals. Brain death confirmation, is crucial before cadaveric donation. Types of transplantation include living, cadaveric, and xenotransplants, as well as autotransplants (within the same person) and allotransplants (between humans). Ethical challenges include donor risks, consent, organ scarcity, and resource allocation. Advances like paired donations, bioengineering, and xenotransplantation aim to expand the donor pool while addressing medical, ethical, and social concerns"
categories: 
  - "English"
  - "Medical Ethics"
  - "Medicine | 2nd year"
  - "Dental medicine | 5th year"
title-meta: "Ethical issues in organ transplantation"
author-meta: "Kostadin Kostadinov"
date-meta: 2024-12-08
---

# Definition of organ transplantation

**Medical and other activities of obtaining organs, tissues and cells from human cadaver or living person and their implantation to other person for treatment, as well as obtaining organs, tissues and cells  from animals and their implantation in human body**

Organ transplantation is both a **life-extending and a life-saving medical procedure** in which a whole or partial organ (or cells in cell therapy) from a deceased or living person is transplanted into another individual, replacing the recipient’s non-functioning organ with the donor’s functioning organ. Advances in the science of organ transplantation since the 1980's have significantly broadened the range of transplantable organs and improved transplant outcomes. Transplant centers in different parts of the world successfully transplant kidneys, livers, lungs, hearts, pancreases, and intestinal organs, and the procedure is considered the preferred treatment for several indications. 

# Organ donation from a human cadaver

In most patients, death is determined without any special diagnostics. Determining death becomes important in comatose patients sustained by mechanical ventilation and other auxiliary intensive care. If a **radioisotope examination** confirms the complete loss of blood supply to the brain, there is no doubt: the patient has died. We do not refer to **brain death**, but **death**. *The patient is dead even if the heart will remain active for some time*. Even with appropriate levels of compassion, it is not always easy to explain the situation to the relatives; many find it hard to reconcile themselves to the death of their loved one whose appearance is the same as the day before and whose heart is still beating. **Only after death has been confirmed, can we open discussion on possible organ donation.**

## Brain death 

Medicine and society continue to struggle thoughtfully with the definition of death, particularly with the progression of sophisticated life-support systems that challenge traditional concepts. The questions of when a disease is irreversible, when further treatment is ineffective, or when death has occurred are of great consequence. These questions are independent of, and galvanized by, the practice of **organ donation**. 

Brain death is defined as the **absence of all brain function demonstrated by profound coma with the irreversible loss of capacity for consciousness, loss of the ability to breathe and absence of all brain stem reflexes**. Analogous to a cardiac arrest, it is better understood as **brain arrest** – the loss of all clinical brain function. If a proximate cause is known and there are no reversible conditions present, death is determined by documenting the absence of brain function by clinical examination. In most cases, brain death can be diagnosed at the bedside. *Common causes* include trauma, intracranial hemorrhage, cerebrovascular accidents, hypoxia owing to resuscitation after cardiac arrest, drug overdose or near drowning, primary brain tumor, meningitis, homicide, and suicide. 

The concept of brain death was influenced by two major health care advances in the 1960s: the development of *intensive care units*, with artificial airways and mechanical ventilators to treat irreversible apnea, thus interrupting the natural evolution from brain failure to cardiac arrest, and **the emergence of organ donation** arising from the new discipline of transplant surgery. An ethical consensus existed that the donation itself must not cause the death of the donor, commonly referred to as the "dead donor" rule. Advanced technologies also revealed the existing limitations in the lexicon of death. The word *death* may be inadequate to describe the event or process in the various domains in which it can be defined, including medical–biological, legal, social, bioethical, philosophical, religious, spiritual, and existential. Brain death as a criterion for determining the death of a person is a medicolegal and social formulation. It implies a notion of irreversible loss of personhood and integrative functions of the brain. The diagnosis uncovers cultural and religious diversity in a pluralistic society.

The concept of brain death was influenced by two major health care advances in the 1960s: the development of *intensive care units*, with artificial airways and mechanical ventilators to treat irreversible apnea, thus interrupting the natural evolution from brain failure to cardiac arrest, and **the emergence of organ donation** arising from the new discipline of transplant surgery. An ethical consensus existed that the donation itself must not cause the death of the donor, commonly referred to as the "dead donor" rule. Advanced technologies also revealed the existing limitations in the lexicon of death. The word *death* may be inadequate to describe the event or process in the various domains in which it can be defined, including medical–biological, legal, social, bioethical, philosophical, religious, spiritual, and existential. Brain death as a criterion for determining the death of a person is a medicolegal and social formulation. It implies a notion of irreversible loss of personhood and integrative functions of the brain. The diagnosis uncovers cultural and religious diversity in a pluralistic society.

Brain death is a detailed clinical examination that documents the complete and irreversible loss of consciousness and absence of brainstem function, including the capacity to breathe. The following criteria apply 

1. Established etiology capable of causing brain death in the absence of reversible conditions capable of mimicking brain death
2. Deep unresponsive coma
3. Absent brainstem reflexes as defined by absent gag and cough reflexes, corneal responses, pupillary responses to light with pupils at mid size or greater and vestibulo-ocular responses
4. Bilateral absence of motor responses, excluding spinal reflexes
5. Absent respiratory effort based on the apnea test
6. Absent confounding factors.

## Ethical considerations 

Since the first kidney transplant in 1954, the increasing success of, and innovations in, transplantation have created a **demand for organs that greatly exceeds the supply in most countries**. The scarcity of organs is a major impetus behind the continuing search for, and development of, alternative ways to **expand the pool of organs and tissues available for transplantation**. A major development is the procurement of organs from family members, and most recently from friends and even from strangers. We are also witnessing desperate patients soliciting organs on the Internet, the compensation of living donors for related expenses or even the bestowing of **financial rewards** for donation, and the experimental use of organs from animals (i.e., xenotransplantation). These recent trends are at the forefront of current ethical debate on transplantation, and they are gaining varying levels of acceptance in different countries by both the public and the transplant community. The sale of organs is another highly complex subject that has received much attention 

# Types of organ transplantation

There are two different types of living donor transplants. In the first, an organ becomes available as a result of a procedure carried out **primarily for the benefit of the donor**. The most common scenario is what is known as a **‘domino’ transplant**, in which a patient needing new lungs has his or her heart and lungs removed and replaced by organs from a **cadaveric donor**. The patient’s own heart **is then available for transplantation to another person**. Recipients are asked to consent both to the clinical procedure itself and to the donation of other organs removed in the course of the treatment. The second type of live donation – **altruistic donation** from healthy donors – raises more issues around consent.

**The main concern** about living donation from healthy volunteers is that **it exposes donors to the small but significant risks of major surgery for no personal physical benefit**. Living donation does, however, carry significant advantages for recipients. Donation from a healthy volunteer – both related and unrelated – carries a higher chance of success for the recipient compared with cadaveric donors. Living donation has other advantages: 

- it facilitates pre-emptive transplantation for someone with progressive renal failure, so avoiding the need for dialysis; 
- it allows the transplant to proceed at the optimal time for the recipient; 
- and it allows those with end-stage renal failure to escape the long wait for a kidney from a cadaveric donor. 
 
Although the physical benefit is all for the recipient, **those who donate to people close to them may achieve psychological and practical benefits** from the recipient’s recovery, such as their ability to return to work or participate more in everyday activities. Many medical interventions carry a risk of harm, **but this is outweighed by the anticipated benefit for the individual**. Nevertheless, it has long been accepted that, **with limited exceptions, adults with capacity are entitled to put themselves at risk to help other people**. Bone marrow and oocyte donation, for example, are accepted even though they put the donor at some degree of risk with no personal physical benefit. 

## Paired and pooled donation

Under this system, where someone needs a donor organ and has a friend or relative willing to donate but the two are not compatible with each other, they can pair up with one or more other incompatible donor and recipient pairs in an organ exchange. 

- In **paired donation**, donor *A* gives an organ to recipient *B* and donor *B* gives to recipient *A*. 
- In **pooled** donation, more **than two donor–recipient pairs** take part in an organ exchange, coordinated by the medical agencies (so, for example, donor A’s kidney goes to recipient B, donor B’s kidney goes to recipient C and donor C’s kidney goes to recipient A). 

## Altruistic non-directed donation

Donation of **blood, gametes or bone marrow** by strangers is commonplace and accepted as a autuistic act. However, organ donation is under strict regulation. Medical commission is entitled to **evaluate donor wishes** in such cases. 

## According to the source of the organ

Organ donation can be categorized based on the source of the organ, and there are various types of organ transplantation methods. 

1. Heterotransplantation, or xenotransplantation, is the practice of transplanting organs or tissues from one species to another.
   1. *Cross-Species Organ Transplants*: Xenotransplantation involves transplanting organs or tissues from animals (e.g., pigs) into humans to address the shortage of human organ donors.
   2. *Risks of Disease Transmission*: Critics argue that xenotransplantation may lead to the transmission of new viral diseases from animals to humans, posing ethical and public health concerns.
   3. *Loss of Human Identity*: Concerns exist about the psychological impact on recipients, as they may struggle with the idea of having animal organs. Pre- and post-operation counseling is seen as important to address these concerns.
   4. *Informed Consent Challenges*: Patients facing life-threatening situations may feel pressured to consent to xenotransplantation, raising questions about the validity of their consent.
   5. *Resource Allocation Dilemma*: Xenotransplantation is expensive, and the allocation of resources in healthcare becomes an ethical issue, as it affects overall healthcare distribution.
   6. *Instrumental Use of Animals*: Using animals for organ transplantation should be justified based on aspects where humans are superior to animals. This raises questions about the ethics of using animals for the benefit of humans.
   7. *Animal Suffering*: Donor animals may undergo increased suffering due to isolation and rigorous testing to prevent disease transmission. Genetic modifications are made to increase compatibility, further raising ethical concerns.
   8. *Blurred Boundaries*: Genetic alterations could make the boundary between humans and animals less distinct, challenging our understanding of species distinctions.
   9. *Differences Among Animals*: Ethical perspectives differ on which animals are suitable donors. Some consider all animals equally acceptable, while others base acceptability on genetic similarity to humans.
2. Homotransplantation / Allotransplantation:
   - Homotransplantation, or allotransplantation, is the most common type of organ transplantation. It involves transplanting organs or tissues **from one human to another** of the same species. 
   - For instance, a kidney transplant from a living or deceased human donor to a recipient is a common example of allotransplantation.
3. Isotransplantation:
   - Isotransplantation is a hypothetical term used to describe a situation where an organ or tissue is transplanted from one individual to another **who is genetically identical**. 
   - This could occur, for example, in the case of an identical twin donating an organ to their sibling.
4. Autotransplantation:
   - Autotransplantation involves transplanting tissues or organs **from one part of an individual's body to another part of their own body**. 
   - An example of autotransplantation is a *skin graft*, where skin is taken from one area of a person's body and transplanted to another area, often to treat burn injuries.
5. Biotransplantation:
   - Biotransplantation is a relatively uncommon term that can refer to any transplantation involving **technologically modified tissues or organs** or entirely artificial organs.
   -  For example, a biotransplantation could involve transplanting a tissue or organ that has been modified using genetic engineering techniques or 3D bio-printing.

# Case studies

## Case 1

Mr. L is a 35-year-old man who has a sudden, excruciating headache and collapses in his chair at dinner. At the emergency department, a CT scan reveals a subarachnoid hemorrhage. Mr. L is admitted to the intensive care unit for monitoring and supportive measures aimed at controlling the intracranial pressure. The next morning he is noted to be unresponsive, with non-reactive, mid-position pupils.

- What is the ethical course of action if Mr. L's condition deteriorates, and he remains unresponsive? Should the medical team discuss end-of-life decisions with his family or healthcare proxy?
- How should the medical team and family approach the concept of medical futility? When, if at all, should treatment be considered futile, and how does this impact the ethical decisions surrounding Mr. L's care?

## Case 2

You are a fourth-year medical student with a patient who has been in a severe motor vehicle accident. The patient has a subdural hematoma that led to cerebral herniation before it could be drained. Over the last few days, the patient has lost all brainstem reflexes and is now brain dead. You have the closest relationship with the family of anyone on the team. The ventilator is to be removed soon and organ donation is considered. 
Who should ask for consent for organ donation in this case? 


## Case 3

A man arrives at the emergency department on a ventilator after an accident. He is brain dead by all criteria. He has an organ-donor card in his wallet indicating his desire to donate. The organ-donor team contacts the family. The family refuses to sign consent for the donation. What should be done?


## Case 4

A 63-year-old widower has advanced renal failure due to type II diabetes mellitus and has been evaluated for kidney transplantation. His testing shows that he is blood group O, and he is told that his donor will also need to be blood group O. He speaks with friends and family member about living donation. Four people, including his 35-year-old daughter, want to be considered as donors. Preliminary screening consists of a telephone interview and a blood group test. The interview raises no concerns, but the blood test reveals that the daughter is blood group AB.


## Case 5 

A 56-year-old man has advanced cirrhosis due to alcoholism and has been sober for 4 years. He has been on the liver transplant waiting list for 1 year but has now been diagnosed with hepatocellular carcinoma. He has been told that he will be removed from the list and offered other forms of treatment. Two weeks later, he informs his physician that he will be traveling to another country where he will be able to receive a liver transplant within a month. He has initiated a Web site to help him raise the money. He requests to make follow-up appointments so that he can proactively arrange aftercare upon his return to the United States.

## Case 6

Abdul, a 41-year-old accountant, is married and has three young children. He was diagnosed with type 1 diabetes at the age of 24, which led to chronic kidney disease. Abdul’s kidney function has deteriorated rapidly over the past several years, leaving him with end-stage renal disease. Six months ago he started dialysis treatment three times a week. Each session would last more than 4 hours, leaving Abdul feeling exhausted and drained.

Abdul’s condition and medical treatment has impacted his work life; he can now only work part-time due to his regular hospital dialysis appointments and fatigue. This has implications on the family’s financial situation, as his income is greatly reduced. Furthermore, he is spending less time with his children due to the hospital appointments and constant exhaustion. At his last renal appointment, the topic of kidney transplantation was discussed, however, the waiting list of around 3 years worried Abdul. When discussing this appointment with his family, his brother, Farhan, became concerned as to how his brother would cope with 3 more years of dialysis and part-time work. A week later, Farhan told Abdul that he wanted to donate a kidney to him.

Questions

1. How can consent be obtained for organ transplantation?
2. What are the different types of organ donation?

## Case 7

Mike is a 36-year-old banker with a passion for motorbikes. One winter evening when he is travelling back from a conference down the M1, his bike skids on a patch of black ice. He was driving at 90 mph. He hits the windscreen of an oncoming car and his helmet splits in half. An ambulance arrives at the scene within minutes and Mike is intubated and rushed to hospital. He has sustained severe injuries – he has fractured his pelvis and several vertebrae. At hospital he is assessed on the intensive care unit. Attempts to resuscitate him are unsuccessful, and when he is weaned off the ventilator he does not make any respiratory effort. Tests performed by two different consultants confirm that he has had massive brainstem injuries, and he is declared brainstem dead despite the ventilator continuing to keep his heart and lungs working and consequently the rest of his organs perfused. Mike is registered on the national organ donation database and was carrying an organ donor card on him. It is decided to keep him ventilated until his next of kin are traced and contacted, so that Mike’s wish to donate his organs can be discussed with them.

Questions

- How can someone donate his or her organs after death?
- Can the next of kin prevent organ donation?

## Case 8

Dave, a 35-year-old healthy man, has been made redundant by the factory he used to work in. His wife has recently left him, as he cannot support her, and he has become depressed due to losing her respect. He is also still grieving the death of his son, who died from leukaemia at the age of 5. As he is wandering the streets, he notices an advertisement in a shop window.

> **WANTED !** *One functioning kidney to save the life of a 15-year-old girl! Potential donors will be morally and financially rewarded*

The advertisement makes Dave think. He has two kidneys and he is healthy. He knows that donating one of his kidneys will not be without risk, but he also knows that it could potentially save the life of a child and ease some of the guilt he feels following the death of his own son It would also give him enough money to get back on his feet, try to win his wife back, and se up a business of his own. It seems that all parties in the transaction would benefit.

Questions

- What are the ethical implications of creating a market in organ donation?
- What other methods could be introduced to increase the availability of organs for transplant in your country?